# Generated by Django 5.0.6 on 2025-08-25 06:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0003_alter_account_currency'),
        ('stakeholders', '0002_alter_supplier_contact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RawsFilesRHE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', models.CharField(blank=True, choices=[('0', 'Procesando'), ('1', 'Completado'), ('2', 'Error')], max_length=1, null=True, verbose_name='Estado')),
                ('archivo', models.FileField(upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt'])])),
                ('procesado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Archivo Original',
                'verbose_name_plural': 'Archivos Originales',
            },
        ),
        migrations.CreateModel(
            name='FinancialDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('typeInvoice', models.CharField(blank=True, choices=[('0', 'Factura'), ('1', 'RHE'), ('2', 'Doc del exterior'), ('3', 'Impuesto'), ('4', 'Planilla'), ('5', 'Nota de credito'), ('10', 'Liq'), ('7', 'Diario'), ('8', 'DUA'), ('9', 'Boleto Aéreo'), ('10', 'Liquidacion'), ('11', 'percepcion'), ('12', 'Otros'), ('13', 'Boleta de venta')], max_length=2, null=True, verbose_name='Tipo de Doc. Emisor')),
                ('doc_status', models.CharField(blank=True, choices=[('0', 'No Anulado'), ('1', 'Anulado'), ('2', 'Revertido')], max_length=1, null=True, verbose_name='Estado Doc. Emitido')),
                ('doc_emisor', models.CharField(blank=True, choices=[('0', 'RUC'), ('1', 'DNI'), ('2', 'DNI'), ('2', 'Carnet de Extranjería')], max_length=1, null=True, verbose_name='Tipo de Doc. Emisor')),
                ('typeCurrency', models.CharField(blank=True, choices=[('0', 'PEN'), ('1', 'USD'), ('2', 'EUR')], max_length=1, null=True, verbose_name='Moneda de Operación')),
                ('month_dec', models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], null=True, verbose_name='Mes de declaración')),
                ('year_dec', models.PositiveIntegerField(blank=True, null=True, verbose_name='Año de declaración')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Fecha de emisión')),
                ('idInvoice', models.CharField(blank=True, max_length=50, null=True, verbose_name='Id de comprobante')),
                ('detraction', models.CharField(choices=[('0', 'No requiere'), ('1', 'Pendiente'), ('2', 'Completado')], default='0', max_length=1, verbose_name='Detracción - Factura')),
                ('shippingGuide', models.CharField(choices=[('0', 'No requiere'), ('1', 'Pendiente'), ('2', 'Completado')], default='0', max_length=1, verbose_name='Guia de remisión - Factura')),
                ('retention', models.CharField(choices=[('0', 'No requiere'), ('1', 'Pendiente'), ('2', 'Completado')], default='0', max_length=1, verbose_name='Retención - RHE')),
                ('annotation', models.CharField(blank=True, choices=[('0', 'anticipo'), ('1', 'pago final'), ('2', 'total')], max_length=2, null=True, verbose_name='Anotaciones')),
                ('contabilidad', models.CharField(blank=True, choices=[('0', 'Agente de aduana'), ('1', 'Caja chica'), ('2', 'Caja General'), ('3', 'Caja General ventas'), ('4', 'RHE general'), ('5', 'Adicional'), ('6', 'Personal'), ('7', 'PL'), ('8', 'renta')], max_length=2, null=True, verbose_name='Sub Categoria contabilidad')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('shortDescription', models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripción corta')),
                ('declareFlag', models.BooleanField(default=True, verbose_name='Declaracion?')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto bruto')),
                ('incomeTax', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Impuesto')),
                ('netAmount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto neto')),
                ('pendingNetPayment', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto Neto Pendiente de Pago')),
                ('equivalentAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto equivalente')),
                ('amountReconcilied', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto conciliado')),
                ('xml_file', models.FileField(blank=True, null=True, upload_to='financialDocs_xlms/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='financialDocs_pdfs/')),
                ('idClient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stakeholders.client')),
                ('idTin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuentas.tin')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finantialDocumentes_user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Documento financiero',
                'verbose_name_plural': 'Documentos financieros',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='OthersDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('typeDoc', models.CharField(blank=True, choices=[('0', 'Guia de remisión'), ('1', 'Liquidación'), ('2', 'Retencion'), ('3', 'Detraccion'), ('5', 'Otros')], default='9', max_length=1, null=True, verbose_name='Tipo de documento')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Fecha de emisión')),
                ('idOtherDocument', models.CharField(blank=True, max_length=200, null=True, verbose_name='Id documento')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Monto')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='othersDocuments_pdfs/')),
                ('idFinacialDocuments', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documentos.financialdocuments')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OthersDocuments_user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Documento generico',
                'verbose_name_plural': 'Documentos genericos',
            },
        ),
    ]
