# Generated by Django 5.0.6 on 2025-09-10 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
        ('purchase', '0028_requirementitems_idcontainer_and_more'),
        ('sales', '0010_trafos_idcontainer_alter_incomes_idclient'),
        ('stakeholders', '0005_alter_supplier_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialdocuments',
            name='idQuote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.quotes'),
        ),
        migrations.AddField(
            model_name='financialdocuments',
            name='idRequirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase.requirements'),
        ),
        migrations.AddField(
            model_name='financialdocuments',
            name='idSupplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stakeholders.supplier'),
        ),
        migrations.AddField(
            model_name='financialdocuments',
            name='typeMovement',
            field=models.CharField(blank=True, choices=[('0', 'Egreso'), ('1', 'Ingreso')], max_length=1, null=True, verbose_name='Tipo movimiento'),
        ),
    ]
