# Generated by Django 5.0.6 on 2025-09-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_financialdocuments_idquote_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialdocuments',
            name='typeMovement',
        ),
        migrations.AddField(
            model_name='financialdocuments',
            name='expenseFlag',
            field=models.BooleanField(default=True, verbose_name='Egreso?'),
        ),
    ]
