# Generated by Django 5.0.6 on 2025-12-04 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0003_remove_financialdocuments_typemovement_and_more'),
        ('transport', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialdocuments',
            name='idContainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.container'),
        ),
    ]
