# Generated by Django 5.0.6 on 2024-12-19 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=30, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phoneNumber', models.CharField(blank=True, null=True, verbose_name='Telefono')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tradeName', models.CharField(blank=True, null=True, verbose_name='Razon Social')),
                ('ruc', models.CharField(blank=True, null=True, verbose_name='RUC - DNI')),
                ('brandName', models.CharField(blank=True, null=True, verbose_name='Marca')),
                ('city', models.CharField(blank=True, null=True, verbose_name='Ciudad')),
                ('phoneNumber', models.CharField(blank=True, null=True, verbose_name='Telefono')),
                ('webPage', models.CharField(blank=True, null=True, verbose_name='Página Web')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('bankName', models.CharField(blank=True, choices=[('0', 'BCP'), ('1', 'BBVA'), ('2', 'INTERBANK'), ('3', 'SCOTIABANK'), ('4', 'COMERCIO'), ('5', 'BANBIF'), ('6', 'PICHINCHA'), ('7', 'GNB'), ('8', 'MIBANCO'), ('9', 'FALABELLA'), ('10', 'CITIBANK'), ('11', 'RIPLEY')], max_length=2, null=True, verbose_name='Banco')),
                ('account', models.CharField(blank=True, null=True, verbose_name='Nro Cuenta')),
                ('typeClient', models.CharField(blank=True, choices=[('0', 'cliente'), ('1', 'proveedor')], max_length=1, null=True, verbose_name='Categoria')),
                ('locationClient', models.CharField(blank=True, choices=[('0', 'nacional'), ('1', 'extrangero')], max_length=1, null=True, verbose_name='Por origen')),
                ('contact', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.contacto')),
            ],
        ),
    ]
