# Generated by Django 5.0.6 on 2024-12-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='account',
            field=models.CharField(blank=True, null=True, verbose_name='Nro Cuenta'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='bankName',
            field=models.CharField(blank=True, null=True, verbose_name='Banco'),
        ),
    ]
