# Generated by Django 5.0.6 on 2025-04-25 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='account',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='bankName',
        ),
        migrations.CreateModel(
            name='CuentasBancarias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankName', models.CharField(blank=True, choices=[('0', 'BCP'), ('1', 'BBVA'), ('2', 'INTERBANK'), ('3', 'SCOTIABANK'), ('4', 'COMERCIO'), ('5', 'BANBIF'), ('6', 'PICHINCHA'), ('7', 'GNB'), ('8', 'MIBANCO'), ('9', 'FALABELLA'), ('10', 'CITIBANK'), ('11', 'RIPLEY')], max_length=2, null=True, verbose_name='Banco')),
                ('typeCurrency', models.CharField(blank=True, choices=[('0', 'S/.'), ('1', '$'), ('2', '€')], max_length=1, null=True, verbose_name='Tipo de moneda')),
                ('account', models.CharField(blank=True, null=True, verbose_name='Nro Cuenta')),
                ('accountCCI', models.CharField(blank=True, null=True, verbose_name='Nro CCI')),
                ('idClient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
        ),
    ]
