# Generated by Django 5.0.6 on 2024-12-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_account_cliente_bankname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='bankName',
            field=models.CharField(blank=True, choices=[('0', 'cliente'), ('1', 'proveedor')], max_length=1, null=True, verbose_name='Banco'),
        ),
    ]
