# Generated by Django 5.0.6 on 2025-04-25 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_remove_cliente_account_remove_cliente_bankname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentasbancarias',
            name='typeAccount',
            field=models.CharField(blank=True, choices=[('0', 'Ahorros'), ('1', 'Corriente'), ('2', 'Sueldo')], max_length=1, null=True, verbose_name='Tipo de cuenta'),
        ),
    ]
