# Generated by Django 5.0.6 on 2025-04-25 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_cuentasbancarias_typeaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentasbancarias',
            name='idClient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CuentaBancariaCliente', to='clientes.cliente'),
        ),
    ]
