# Generated by Django 5.0.6 on 2025-04-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_cuentasbancarias_idclient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentasbancarias',
            name='typeAccount',
            field=models.CharField(blank=True, choices=[('0', 'Ahorros'), ('1', 'Corriente'), ('2', 'Sueldo'), ('3', 'Ahorros JSAT'), ('4', 'Ahorros DAVINCHY')], max_length=1, null=True, verbose_name='Tipo de cuenta'),
        ),
    ]
