# Generated by Django 5.0.6 on 2025-04-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_alter_cuentasbancarias_typeaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='ruc',
            field=models.CharField(blank=True, null=True, unique=True, verbose_name='RUC - DNI'),
        ),
    ]
