# Generated by Django 5.0.6 on 2025-05-20 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_alter_cliente_ruc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['tradeName']},
        ),
    ]
