# Generated by Django 5.0.6 on 2025-05-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_alter_cliente_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='city',
        ),
        migrations.AddField(
            model_name='cliente',
            name='channel',
            field=models.CharField(blank=True, choices=[('0', 'Directo'), ('1', 'Partner'), ('2', 'Licitación'), ('3', 'Otro')], max_length=1, null=True, verbose_name='Canal de captación'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='country',
            field=models.CharField(blank=True, null=True, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='electronicSignature',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Firma electrónica'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='internationalBilling',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Facturación internacional'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='languageContract',
            field=models.CharField(blank=True, choices=[('0', 'Español'), ('1', 'Ingles'), ('1', 'Otro')], max_length=1, null=True, verbose_name='Idioma de contrato'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='legalJurisdiction',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Jurisdicción legal aplicable'),
        ),
    ]
