# Generated by Django 5.0.6 on 2025-05-26 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_remove_cliente_city_cliente_channel_cliente_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='electronicSignature',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='internationalBilling',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='legalJurisdiction',
        ),
    ]
