# Generated by Django 5.0.6 on 2025-09-08 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='message',
        ),
        migrations.AddField(
            model_name='container',
            name='shortDescription',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción corta'),
        ),
    ]
