# Generated by Django 5.0.6 on 2025-09-23 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_alter_items_idtrafo_alter_items_options_and_more'),
        ('transport', '0002_remove_container_message_container_shortdescription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Container',
        ),
    ]
