# Generated by Django 5.0.6 on 2025-12-04 11:20

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transport', '0003_delete_container'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('currency', models.CharField(blank=True, choices=[('0', 'PEN'), ('1', 'USD'), ('2', 'EUR')], max_length=1, null=True, verbose_name='Moneda')),
                ('grossAmount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Monto bruto')),
                ('taxes', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Impuestos')),
                ('netAmount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto neto')),
                ('isOrder', models.BooleanField(default=False, verbose_name='Es orden de compra?')),
                ('shortDescription', models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripción')),
                ('idPetitioner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logistic_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contenedor',
                'verbose_name_plural': 'Contenedores',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='ContainerTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', models.CharField(blank=True, choices=[('0', 'Creado'), ('1', 'Recibido'), ('2', 'Aprobado'), ('3', 'Rechazado'), ('4', 'Observado'), ('5', 'Solicitado'), ('6', 'Enviado a proveedores'), ('7', 'Cotizado por proveedores'), ('8', 'Parcailmente recepcionado'), ('9', 'Recepción total'), ('10', 'Facturado'), ('10', 'Pago parcial'), ('11', 'Pagol total'), ('12', 'Completado')], max_length=2, null=True, verbose_name='Estado de orden')),
                ('area', models.CharField(blank=True, choices=[('1', 'Comercial'), ('2', 'Finanzas'), ('3', 'Producción'), ('4', 'Gerencia'), ('5', 'Logistica')], max_length=2, null=True, verbose_name='Area de seguimiento')),
                ('idContainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.container')),
            ],
            options={
                'verbose_name': 'Tracking contenedor',
                'verbose_name_plural': 'Tracking contenedores',
            },
        ),
    ]
