# Generated by Django 5.0.6 on 2025-12-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='containerName',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre'),
        ),
    ]
