# Generated by Django 5.0.6 on 2026-02-25 14:37

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0005_container_containername'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='containerNumber',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de contenedor'),
        ),
        migrations.AddField(
            model_name='container',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Año'),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('docType', models.CharField(choices=[('0', 'Booking'), ('1', 'Factura'), ('2', 'Guia'), ('3', 'Certificado de origen'), ('4', 'Mandato'), ('5', 'BL'), ('6', 'HBL'), ('7', 'Otro')], max_length=20, verbose_name='Tipo de documento')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de documento')),
                ('con_file', models.FileField(upload_to='container_docs/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'jpg', 'png'])])),
                ('date', models.DateField(verbose_name='Fecha de emisión')),
                ('desription', models.TextField(blank=True, verbose_name='Descripción del documento')),
                ('idContainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.container')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
