# Generated by Django 5.0.6 on 2026-02-25 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0006_container_containernumber_container_year_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='desription',
            new_name='description',
        ),
    ]
