# Generated by Django 5.0.6 on 2025-07-04 09:57

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0011_cliente_electronicsignature_and_more'),
        ('cuentas', '0003_alter_account_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incomes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('typeInvoice', models.CharField(blank=True, choices=[('0', 'Factura'), ('2', 'Doc del exterior'), ('3', 'Impuesto'), ('5', 'Nota de credito'), ('10', 'Liquidacion'), ('11', 'percepcion'), ('12', 'Otros'), ('13', 'Boleta de venta')], max_length=2, null=True, verbose_name='Tipo de Doc. Emisor')),
                ('doc_status', models.CharField(blank=True, choices=[('0', 'No Anulado'), ('1', 'Anulado'), ('2', 'Revertido')], max_length=1, null=True, verbose_name='Estado Doc. Emitido')),
                ('doc_emisor', models.CharField(blank=True, choices=[('0', 'RUC'), ('1', 'TIN'), ('2', 'DNI'), ('2', 'Carnet de Extranjería')], max_length=1, null=True, verbose_name='Tipo de Doc. Emisor')),
                ('typeCurrency', models.CharField(blank=True, choices=[('0', 'PEN'), ('1', 'USD'), ('2', 'EUR')], max_length=1, null=True, verbose_name='Moneda de Operación')),
                ('month_dec', models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], null=True, verbose_name='Mes de declaración')),
                ('year_dec', models.PositiveIntegerField(blank=True, null=True, verbose_name='Año de declaración')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Fecha de emisión')),
                ('idInvoice', models.CharField(blank=True, max_length=50, null=True, verbose_name='Id de comprobante')),
                ('detraction', models.CharField(choices=[('0', 'No requiere'), ('1', 'Pendiente'), ('2', 'Completado')], default='0', max_length=1, verbose_name='Detracción - Factura')),
                ('shippingGuide', models.CharField(choices=[('0', 'No requiere'), ('1', 'Pendiente'), ('2', 'Completado')], default='0', max_length=1, verbose_name='Guia de remisión - Factura')),
                ('retention', models.CharField(choices=[('0', 'No requiere'), ('1', 'Pendiente'), ('2', 'Completado')], default='0', max_length=1, verbose_name='Retención - RHE')),
                ('annotation', models.CharField(blank=True, choices=[('0', 'anticipo'), ('1', 'pago final'), ('2', 'total')], max_length=2, null=True, verbose_name='Anotaciones')),
                ('contabilidad', models.CharField(blank=True, choices=[('0', 'Agente de aduana'), ('1', 'Caja chica'), ('2', 'Caja General'), ('3', 'Caja General ventas'), ('4', 'RHE general'), ('5', 'Adicional'), ('6', 'Personal'), ('7', 'PL'), ('8', 'renta')], max_length=2, null=True, verbose_name='Sub Categoria contabilidad')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('shortDescription', models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripción corta')),
                ('declareFlag', models.BooleanField(default=True, verbose_name='Declaracion?')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto bruto')),
                ('incomeTax', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Impuesto')),
                ('netAmount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto neto')),
                ('pendingNetPayment', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto Neto Pendiente de Pago')),
                ('equivalentAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto equivalente')),
                ('amountReconcilied', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto conciliado')),
                ('xml_file', models.FileField(blank=True, null=True, upload_to='financialDocs_xlms/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='financialDocs_pdfs/')),
                ('idClient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('idTin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuentas.tin')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incomes_user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Documento de venta',
                'verbose_name_plural': 'Documentos de ventas',
                'ordering': ['created'],
            },
        ),
    ]
