# Generated by Django 5.0.6 on 2025-07-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomes',
            name='trackDoc',
            field=models.CharField(blank=True, choices=[('0', 'Recibido'), ('1', 'Contabilidad'), ('2', 'Completado')], default='0', max_length=1, null=True, verbose_name='Seguimiento del documento'),
        ),
        migrations.AlterField(
            model_name='incomes',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='salesDocs_pdfs/'),
        ),
        migrations.AlterField(
            model_name='incomes',
            name='xml_file',
            field=models.FileField(blank=True, null=True, upload_to='salesDocs_xlms/'),
        ),
    ]
