# Generated by Django 5.0.6 on 2025-08-15 12:09

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_alter_account_currency'),
        ('purchase', '0025_purchaseordervouchers'),
        ('sales', '0002_incomes_trackdoc_alter_incomes_pdf_file_and_more'),
        ('stakeholders', '0002_alter_supplier_contact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='quotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('shortDescription', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripción')),
                ('currency', models.CharField(blank=True, choices=[('0', 'PEN'), ('1', 'USD'), ('2', 'EUR')], max_length=1, null=True, verbose_name='Moneda')),
                ('initialAmount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Monto inicial')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Monto')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Fecha de entrega')),
                ('payMethod', models.CharField(blank=True, choices=[('1', 'Contado'), ('0', 'Credito')], default='0', max_length=1, null=True, verbose_name='Método de pago')),
                ('isPO', models.BooleanField(default=False, verbose_name='Es PO?')),
                ('idClient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quote_client', to='stakeholders.client')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
            },
        ),
        migrations.CreateModel(
            name='POvouchers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Fecha de emisión')),
                ('typeCurrency', models.CharField(blank=True, choices=[('0', 'PEN'), ('1', 'USD'), ('2', 'EUR')], max_length=1, null=True, verbose_name='Moneda de Operación')),
                ('shortDescription', models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripción corta')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto bruto')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='POvouchers_pdfs/')),
                ('idAccount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuentas.account')),
                ('idQuote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.quotes')),
            ],
            options={
                'verbose_name': 'Voucher de recepcion de PO',
                'verbose_name_plural': 'Todos los voucher de recepcion de PO',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='POinvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('typeInvoice', models.CharField(blank=True, choices=[('0', 'Factura'), ('1', 'RHE'), ('2', 'Doc del exterior')], max_length=2, null=True, verbose_name='Tipo de Doc. Emisor')),
                ('doc_status', models.CharField(blank=True, choices=[('0', 'No Anulado'), ('1', 'Anulado'), ('2', 'Revertido')], max_length=1, null=True, verbose_name='Estado Doc. Emitido')),
                ('typeCurrency', models.CharField(blank=True, choices=[('0', 'PEN'), ('1', 'USD'), ('2', 'EUR')], max_length=1, null=True, verbose_name='Moneda de Operación')),
                ('month_dec', models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], null=True, verbose_name='Mes de declaración')),
                ('year_dec', models.PositiveIntegerField(blank=True, null=True, verbose_name='Año de declaración')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Fecha de emisión')),
                ('detraction', models.CharField(choices=[('0', 'No requiere'), ('1', 'Pendiente'), ('2', 'Completado')], default='0', max_length=1, verbose_name='Detracción - Factura')),
                ('shippingGuide', models.CharField(choices=[('0', 'No requiere'), ('1', 'Pendiente'), ('2', 'Completado')], default='0', max_length=1, verbose_name='Guia de remisión - Factura')),
                ('retention', models.CharField(choices=[('0', 'No requiere'), ('1', 'Pendiente'), ('2', 'Completado')], default='0', max_length=1, verbose_name='Retención - RHE')),
                ('annotation', models.CharField(blank=True, choices=[('0', 'anticipo'), ('1', 'pago final'), ('2', 'total')], max_length=2, null=True, verbose_name='Anotaciones')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('shortDescription', models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripción corta')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto bruto')),
                ('incomeTax', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Impuesto')),
                ('netAmount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto neto')),
                ('pendingNetPayment', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto Neto Pendiente de Pago')),
                ('equivalentAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto equivalente')),
                ('amountReconcilied', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto conciliado')),
                ('xml_file', models.FileField(blank=True, null=True, upload_to='purchaseDocs_xlms/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='requirementsInvoice_pdfs/')),
                ('idClient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stakeholders.client')),
                ('idTin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuentas.tin')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='POinvoice_user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('idQuote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.quotes')),
            ],
            options={
                'verbose_name': 'Invoice de PO',
                'verbose_name_plural': 'Invoices de POs',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Mensaje')),
                ('idRequirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase.requirements')),
                ('idQuote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.quotes')),
            ],
            options={
                'verbose_name': 'Contenedor',
                'verbose_name_plural': 'Contenedores',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='QuoteTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', models.CharField(blank=True, choices=[('0', 'Creado'), ('1', 'Recibido'), ('2', 'Aprobado'), ('3', 'Rechazado'), ('4', 'Observado'), ('5', 'Solicitado'), ('6', 'Enviado a proveedores'), ('7', 'Cotizado por proveedores'), ('8', 'Parcailmente recepcionado'), ('9', 'Recepción total'), ('10', 'Facturado'), ('10', 'Pago parcial'), ('11', 'Pagol total'), ('12', 'Completado')], max_length=2, null=True, verbose_name='Estado de orden')),
                ('area', models.CharField(blank=True, choices=[('0', 'Area Documentaria'), ('1', 'Area Técnica')], max_length=2, null=True, verbose_name='Area de seguimiento')),
                ('idquote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.quotes')),
            ],
            options={
                'verbose_name': 'seguimiento de requerimiento',
                'verbose_name_plural': 'seguimientos de requerimientos',
            },
        ),
        migrations.CreateModel(
            name='Trafos',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('KVA', models.CharField(blank=True, choices=[('0', '15'), ('1', '30'), ('2', '75'), ('3', '100'), ('4', '167'), ('5', '200'), ('6', '250'), ('7', '400'), ('8', '500'), ('9', '600'), ('10', '750'), ('11', '1000'), ('12', '1500'), ('13', '2000')], max_length=2, null=True, verbose_name='kVA CAPACITY')),
                ('HVTAP', models.CharField(blank=True, choices=[('0', 'K-Tap - HV'), ('1', 'Fix HV')], max_length=2, null=True, verbose_name='HV TAP')),
                ('KTapHV', models.CharField(blank=True, choices=[('0', '12700/7200'), ('1', '24940/14400')], max_length=2, null=True, verbose_name='K Tap HV')),
                ('FIXHV', models.CharField(blank=True, choices=[('0', '7200'), ('1', '12470'), ('2', '22900')], max_length=2, null=True, verbose_name='FIX HV')),
                ('LV', models.CharField(blank=True, choices=[('0', '120/240'), ('1', '277/480')], max_length=2, null=True, verbose_name='LV')),
                ('HZ', models.CharField(blank=True, choices=[('0', '50'), ('1', '60')], max_length=2, null=True, verbose_name='HZ')),
                ('TYPE', models.CharField(blank=True, choices=[('0', 'Mono-phasic'), ('1', 'Three-phasic')], max_length=2, null=True, verbose_name='TYPE')),
                ('MOUNTING', models.CharField(blank=True, choices=[('0', 'Pole'), ('1', 'Standard'), ('2', 'Feed Through Pad')], max_length=2, null=True, verbose_name='MOUNTING TYPE')),
                ('COOLING', models.CharField(blank=True, choices=[('0', 'Oil'), ('1', 'Dry')], max_length=2, null=True, verbose_name='COOLING')),
                ('WINDING', models.CharField(blank=True, choices=[('0', 'Al - Al'), ('1', 'Cu - CU')], max_length=2, null=True, verbose_name='WINDING')),
                ('INSULAT', models.CharField(blank=True, choices=[('0', 'A'), ('1', 'E'), ('2', 'H')], max_length=2, null=True, verbose_name='INSULAT CLASS')),
                ('CONNECTION', models.CharField(blank=True, choices=[('0', 'WEY'), ('1', 'DELTA')], max_length=2, null=True, verbose_name='CONNECTION')),
                ('STANDARD', models.CharField(blank=True, choices=[('0', 'NMX-116'), ('1', 'IEC 61558')], max_length=2, null=True, verbose_name='STANDARD')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Cantidad')),
                ('unitCost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo unitario')),
                ('idTrafoQuote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trafo_Quote', to='sales.quotes')),
            ],
            options={
                'verbose_name': 'Trafos',
                'verbose_name_plural': 'Trafos',
            },
        ),
    ]
