# Generated by Django 5.0.6 on 2025-08-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_quotes_povouchers_poinvoice_container_quotetracking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='containerName',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de contenedor'),
        ),
    ]
