# Generated by Django 5.0.6 on 2025-08-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_container_containername'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafos',
            name='serialNumber',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número serial'),
        ),
        migrations.DeleteModel(
            name='Container',
        ),
    ]
