# Generated by Django 5.0.6 on 2025-08-20 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_alter_account_currency'),
        ('sales', '0005_trafos_serialnumber_delete_container'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='idTin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuentas.tin'),
        ),
    ]
