# Generated by Django 5.0.6 on 2025-09-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_quotes_idtin'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='dateOrder',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de solicitud'),
        ),
    ]
