# Generated by Django 5.0.6 on 2025-09-03 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0005_rename_lastupdatecrm_account_initaldate_and_more'),
        ('sales', '0007_quotes_dateorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotes',
            name='idTin',
        ),
        migrations.AddField(
            model_name='quotes',
            name='idTinExecuting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_executing', to='cuentas.tin'),
        ),
        migrations.AddField(
            model_name='quotes',
            name='idTinReceiving',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_receiving', to='cuentas.tin'),
        ),
    ]
