# Generated by Django 5.0.6 on 2025-09-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_remove_quotes_idtin_quotes_idtinexecuting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotetracking',
            name='area',
            field=models.CharField(blank=True, choices=[('0', 'Cliente'), ('1', 'Comercial - documentos'), ('3', 'Producción - técnico'), ('2', 'Finanzas'), ('4', 'Gerencia'), ('5', 'Logistica')], max_length=2, null=True, verbose_name='Area de seguimiento'),
        ),
    ]
