# Generated by Django 5.0.6 on 2025-09-08 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_alter_quotetracking_area'),
        ('stakeholders', '0005_alter_supplier_status'),
        ('transport', '0002_remove_container_message_container_shortdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafos',
            name='idContainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='container', to='transport.container'),
        ),
        migrations.AlterField(
            model_name='incomes',
            name='idClient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stakeholders.client'),
        ),
    ]
