# Generated by Django 5.0.6 on 2025-09-22 10:53

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_trafos_idcontainer_alter_incomes_idclient'),
        ('stakeholders', '0007_alter_supplier_numberidsupplier'),
        ('transport', '0002_remove_container_message_container_shortdescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trafos',
            name='idContainer',
        ),
        migrations.RemoveField(
            model_name='trafos',
            name='idTrafoQuote',
        ),
        migrations.RemoveField(
            model_name='trafos',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='trafos',
            name='serialNumber',
        ),
        migrations.RemoveField(
            model_name='trafos',
            name='unitCost',
        ),
        migrations.AddField(
            model_name='trafos',
            name='idSupplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_trafo_supplier', to='stakeholders.supplier'),
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('seq', models.IntegerField(blank=True, null=True, verbose_name='Secuencial')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Cantidad')),
                ('unitCost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo unitario')),
                ('idContainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_container', to='transport.container')),
                ('idTrafo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_Trafo', to='sales.trafos')),
                ('idTrafoQuote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_Quote', to='sales.quotes')),
            ],
            options={
                'verbose_name': 'Item Trafo',
                'verbose_name_plural': 'Items Trafos',
            },
        ),
    ]
