# Generated by Django 5.0.6 on 2025-09-23 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCTION', '0002_alter_trafos_options_trafos_iduser'),
        ('purchase', '0030_alter_requirementitems_idtrafos'),
        ('sales', '0011_remove_trafos_idcontainer_remove_trafos_idtrafoquote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='idTrafo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_Trafo', to='PRODUCTION.trafos'),
        ),
        migrations.AlterModelOptions(
            name='items',
            options={'verbose_name': 'Item Transformador', 'verbose_name_plural': 'Items Transformadores'},
        ),
        migrations.AlterModelOptions(
            name='quotetracking',
            options={'verbose_name': 'seguimiento de requerimiento', 'verbose_name_plural': 'Tracking Cotizaciones'},
        ),
        migrations.RemoveField(
            model_name='items',
            name='idContainer',
        ),
        migrations.AlterField(
            model_name='items',
            name='seq',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numero secuencial'),
        ),
        migrations.DeleteModel(
            name='Trafos',
        ),
    ]
