# Generated by Django 5.0.6 on 2025-09-24 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_alter_items_idtrafo_alter_items_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='quantity',
        ),
    ]
