# Generated by Django 5.0.6 on 2025-11-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_remove_items_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='fat_file',
            field=models.FileField(blank=True, null=True, upload_to='fats_docss/'),
        ),
        migrations.AlterField(
            model_name='items',
            name='seq',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Serial'),
        ),
    ]
