# Generated by Django 5.0.6 on 2025-11-16 09:43

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_items_fat_file_alter_items_seq'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('statusItem', models.CharField(blank=True, choices=[('0', 'Required'), ('1', 'Assembled'), ('4', 'On the way'), ('5', 'At destination'), ('6', 'Delivered')], max_length=2, null=True, verbose_name='Estado de orden')),
                ('statusPlate', models.CharField(blank=True, choices=[('0', 'Required'), ('1', 'Assembled'), ('4', 'On the way'), ('5', 'At destination'), ('6', 'Delivered')], max_length=2, null=True, verbose_name='Estado de orden')),
                ('idItem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.items')),
            ],
            options={
                'verbose_name': 'Seguimiento de Transformador',
                'verbose_name_plural': 'Tracking TRansformadores',
            },
        ),
    ]
