# Generated by Django 5.0.6 on 2025-11-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_itemtracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtracking',
            name='statusItem',
            field=models.CharField(blank=True, choices=[('0', 'Required'), ('1', 'Assembled'), ('4', 'On the way'), ('5', 'At destination'), ('6', 'Delivered')], default='0', max_length=2, null=True, verbose_name='Estado de orden'),
        ),
        migrations.AlterField(
            model_name='itemtracking',
            name='statusPlate',
            field=models.CharField(blank=True, choices=[('0', 'Required'), ('1', 'Assembled'), ('4', 'On the way'), ('5', 'At destination'), ('6', 'Delivered')], default='0', max_length=2, null=True, verbose_name='Estado de orden'),
        ),
    ]
