# Generated by Django 5.0.6 on 2025-11-16 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_alter_itemtracking_statusitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtracking',
            name='idItem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itemTracking', to='sales.items'),
        ),
    ]
