# Generated by Django 5.0.6 on 2025-11-23 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_alter_itemtracking_statusitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtracking',
            name='statusItem',
            field=models.CharField(blank=True, choices=[('0', 'Required'), ('1', 'Assembled'), ('2', 'On the way'), ('3', 'At destination'), ('4', 'Delivered')], max_length=2, null=True, verbose_name='Estado de orden'),
        ),
        migrations.AlterField(
            model_name='itemtracking',
            name='statusPlate',
            field=models.CharField(blank=True, choices=[('0', 'Required'), ('1', 'Assembled'), ('2', 'On the way'), ('3', 'At destination'), ('4', 'Delivered')], max_length=2, null=True, verbose_name='Estado de placa'),
        ),
    ]
