# Generated by Django 5.0.6 on 2025-11-24 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_alter_itemtracking_statusitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='CONNECTION',
            field=models.CharField(blank=True, choices=[('0', 'Dyn1'), ('1', 'Dyn11'), ('2', 'Yyn0'), ('3', 'YNyn0'), ('4', 'Dzn0'), ('5', 'Yd11'), ('6', 'lio')], max_length=2, null=True, verbose_name='CONNECTION'),
        ),
        migrations.AddField(
            model_name='items',
            name='COOLING',
            field=models.CharField(blank=True, choices=[('0', 'ONAN'), ('1', 'ONAF'), ('2', 'KNAN'), ('3', 'KNAF'), ('4', 'AN'), ('5', 'AF'), ('6', 'OFAN'), ('7', 'OFAF'), ('8', 'ONWF'), ('9', 'OFWF')], max_length=2, null=True, verbose_name='COOLING'),
        ),
        migrations.AddField(
            model_name='items',
            name='HV',
            field=models.CharField(blank=True, choices=[('0', '4160'), ('1', '7200'), ('2', '8320'), ('3', '12470'), ('4', '13200'), ('5', '13800'), ('6', '14400'), ('7', '21600'), ('8', '22860'), ('9', '23960'), ('10', '24940'), ('11', '34500')], max_length=2, null=True, verbose_name='HV'),
        ),
        migrations.AddField(
            model_name='items',
            name='HZ',
            field=models.CharField(blank=True, choices=[('0', '50'), ('1', '60')], max_length=2, null=True, verbose_name='FREQUENCY'),
        ),
        migrations.AddField(
            model_name='items',
            name='KVA',
            field=models.CharField(blank=True, choices=[('0', '75'), ('1', '100'), ('2', '150'), ('3', '167'), ('4', '225'), ('5', '250'), ('6', '300'), ('7', '500'), ('8', '750'), ('9', '1000'), ('10', '1500'), ('11', '2000'), ('12', '2000/3000'), ('13', '2500'), ('14', '2600'), ('15', '3000'), ('16', '3000/3750'), ('17', '3750'), ('18', '5000')], max_length=2, null=True, verbose_name='kVA CAPACITY'),
        ),
        migrations.AddField(
            model_name='items',
            name='LV',
            field=models.CharField(blank=True, choices=[('0', '240/120'), ('1', '480Y/277'), ('2', '208Y/120'), ('3', '4160Y/2400'), ('4', '277/480Y')], max_length=2, null=True, verbose_name='LV'),
        ),
        migrations.AddField(
            model_name='items',
            name='MOUNTING',
            field=models.CharField(blank=True, choices=[('0', 'Pole'), ('1', 'Pedestal'), ('2', 'Platform'), ('3', 'Underground'), ('4', 'Substation')], max_length=2, null=True, verbose_name='MOUNTING TYPE'),
        ),
        migrations.AddField(
            model_name='items',
            name='PHASE',
            field=models.CharField(blank=True, choices=[('0', 'Mono-phasic'), ('1', 'Three-phasic')], max_length=2, null=True, verbose_name='PHASE'),
        ),
        migrations.AddField(
            model_name='items',
            name='STANDARD',
            field=models.CharField(blank=True, choices=[('0', 'IEEE C57.12.00'), ('1', 'IEEE C57.12.20'), ('2', 'IEEE C57.12.21'), ('3', 'IEEE C57.12.34')], max_length=2, null=True, verbose_name='STANDARD'),
        ),
        migrations.AddField(
            model_name='items',
            name='WINDING',
            field=models.CharField(blank=True, choices=[('0', 'Al'), ('1', 'Cu')], max_length=2, null=True, verbose_name='WINDING'),
        ),
    ]
