# Generated by Django 5.0.6 on 2025-11-24 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_items_connection_items_cooling_items_hv_items_hz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='idTrafo',
        ),
    ]
