# Generated by Django 5.0.6 on 2025-11-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0021_remove_items_idtrafo'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='drawing_file',
            field=models.FileField(blank=True, null=True, upload_to='drawing_docss/'),
        ),
        migrations.AddField(
            model_name='items',
            name='plate_file',
            field=models.FileField(blank=True, null=True, upload_to='plate_docss/'),
        ),
    ]
