# Generated by Django 5.0.6 on 2025-11-27 12:21

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0022_items_drawing_file_items_plate_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('image', models.ImageField(upload_to='item_images/', verbose_name='Imagen del producto')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden de visualización')),
                ('is_main', models.BooleanField(default=False, verbose_name='Imagen principal')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sales.items')),
            ],
            options={
                'verbose_name': 'Imagen del Item',
                'verbose_name_plural': 'Imágenes del Item',
                'ordering': ['order', '-is_main', '-created_at'],
            },
        ),
    ]
