# Generated by Django 5.0.6 on 2025-11-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0023_itemimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='poNumber',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='PO number'),
        ),
        migrations.AlterField(
            model_name='items',
            name='LV',
            field=models.CharField(blank=True, choices=[('0', '240/120'), ('1', '480Y/277'), ('2', '208Y/120'), ('3', '4160Y/2400'), ('4', '277/480Y'), ('5', '277')], max_length=2, null=True, verbose_name='LV'),
        ),
        migrations.AlterField(
            model_name='items',
            name='PHASE',
            field=models.CharField(blank=True, choices=[('0', 'Single-phase'), ('1', 'Three-phase')], max_length=2, null=True, verbose_name='PHASE'),
        ),
    ]
