# Generated by Django 5.0.6 on 2025-12-02 11:51

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0024_quotes_ponumber_alter_items_lv_alter_items_phase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trafo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('drawing_file', models.FileField(blank=True, null=True, upload_to='drawing_docss/')),
                ('PHASE', models.CharField(blank=True, choices=[('0', 'Single-phase'), ('1', 'Three-phase')], max_length=2, null=True, verbose_name='PHASE')),
                ('COOLING', models.CharField(blank=True, choices=[('0', 'ONAN'), ('1', 'ONAF'), ('2', 'KNAN'), ('3', 'KNAF'), ('4', 'AN'), ('5', 'AF'), ('6', 'OFAN'), ('7', 'OFAF'), ('8', 'ONWF'), ('9', 'OFWF')], max_length=2, null=True, verbose_name='COOLING')),
                ('MOUNTING', models.CharField(blank=True, choices=[('0', 'Pole'), ('1', 'Pedestal'), ('2', 'Platform'), ('3', 'Underground'), ('4', 'Substation')], max_length=2, null=True, verbose_name='MOUNTING TYPE')),
                ('KVA', models.CharField(blank=True, choices=[('0', '75'), ('1', '100'), ('2', '150'), ('3', '167'), ('4', '225'), ('5', '250'), ('6', '300'), ('7', '500'), ('8', '750'), ('9', '1000'), ('10', '1500'), ('11', '2000'), ('12', '2000/3000'), ('13', '2500'), ('14', '2600'), ('15', '3000'), ('16', '3000/3750'), ('17', '3750'), ('18', '5000')], max_length=2, null=True, verbose_name='kVA CAPACITY')),
                ('HV', models.CharField(blank=True, choices=[('0', '4160'), ('1', '7200'), ('2', '8320'), ('3', '12470'), ('4', '13200'), ('5', '13800'), ('6', '14400'), ('7', '21600'), ('8', '22860'), ('9', '23960'), ('10', '24940'), ('11', '34500'), ('12', '34500'), ('13', '34500')], max_length=2, null=True, verbose_name='HV')),
                ('LV', models.CharField(blank=True, choices=[('0', '240/120'), ('1', '480Y/277'), ('2', '208Y/120'), ('3', '4160Y/2400'), ('4', '277/480Y'), ('5', '277'), ('6', '480')], max_length=2, null=True, verbose_name='LV')),
                ('HZ', models.CharField(blank=True, choices=[('0', '50'), ('1', '60')], max_length=2, null=True, verbose_name='FREQUENCY')),
                ('WINDING', models.CharField(blank=True, choices=[('0', 'Al'), ('1', 'Cu')], max_length=2, null=True, verbose_name='WINDING')),
                ('CONNECTION', models.CharField(blank=True, choices=[('0', 'Dyn1'), ('1', 'Dyn11'), ('2', 'Yyn0'), ('3', 'YNyn0'), ('4', 'Dzn0'), ('5', 'Yd11'), ('6', 'lio'), ('6', 'Dyn1/YNyn0')], max_length=2, null=True, verbose_name='CONNECTION')),
                ('STANDARD', models.CharField(blank=True, choices=[('0', 'IEEE C57.12.00'), ('1', 'IEEE C57.12.20'), ('2', 'IEEE C57.12.21'), ('3', 'IEEE C57.12.34')], max_length=2, null=True, verbose_name='STANDARD')),
            ],
            options={
                'verbose_name': 'Transformador',
                'verbose_name_plural': 'Transformadores',
            },
        ),
        migrations.AlterModelOptions(
            name='items',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
        migrations.RemoveField(
            model_name='items',
            name='CONNECTION',
        ),
        migrations.RemoveField(
            model_name='items',
            name='COOLING',
        ),
        migrations.RemoveField(
            model_name='items',
            name='HV',
        ),
        migrations.RemoveField(
            model_name='items',
            name='HZ',
        ),
        migrations.RemoveField(
            model_name='items',
            name='KVA',
        ),
        migrations.RemoveField(
            model_name='items',
            name='LV',
        ),
        migrations.RemoveField(
            model_name='items',
            name='MOUNTING',
        ),
        migrations.RemoveField(
            model_name='items',
            name='PHASE',
        ),
        migrations.RemoveField(
            model_name='items',
            name='STANDARD',
        ),
        migrations.RemoveField(
            model_name='items',
            name='WINDING',
        ),
        migrations.RemoveField(
            model_name='items',
            name='drawing_file',
        ),
        migrations.AlterField(
            model_name='items',
            name='seq',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Serial'),
        ),
        migrations.AddField(
            model_name='items',
            name='idTrafo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_Quote', to='sales.trafo'),
        ),
    ]
