# Generated by Django 5.0.6 on 2025-12-04 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0025_trafo_alter_items_options_remove_items_connection_and_more'),
        ('transport', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='idContainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_container', to='transport.container'),
        ),
        migrations.AlterField(
            model_name='trafo',
            name='HV',
            field=models.CharField(blank=True, choices=[('0', '4160'), ('1', '7200'), ('2', '8320'), ('3', '12470'), ('4', '13200'), ('5', '13800'), ('6', '14400'), ('7', '21600'), ('8', '22860'), ('9', '23960'), ('10', '24940'), ('11', '34500'), ('12', '2400Delta X 7200Delta X 4160GY/2400 X 12470GY/7200'), ('13', '12470 X 24940')], max_length=2, null=True, verbose_name='HV'),
        ),
        migrations.AlterField(
            model_name='trafo',
            name='LV',
            field=models.CharField(blank=True, choices=[('0', '240/120'), ('1', '480Y/277'), ('2', '208Y/120'), ('3', '4160Y/2400'), ('4', '277/480Y'), ('5', '277'), ('6', '480'), ('7', '208')], max_length=2, null=True, verbose_name='LV'),
        ),
        migrations.AlterField(
            model_name='trafo',
            name='MOUNTING',
            field=models.CharField(blank=True, choices=[('0', 'Pole'), ('1', 'Pad'), ('2', 'Platform'), ('3', 'Underground'), ('4', 'Substation')], max_length=2, null=True, verbose_name='MOUNTING TYPE'),
        ),
    ]
