# Generated by Django 5.0.6 on 2025-12-11 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0026_items_idcontainer_alter_trafo_hv_alter_trafo_lv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='plateB_file',
            field=models.FileField(blank=True, null=True, upload_to='plate_docss/'),
        ),
        migrations.AlterField(
            model_name='trafo',
            name='CONNECTION',
            field=models.CharField(blank=True, choices=[('0', 'Dyn1'), ('1', 'Dyn11'), ('2', 'Yyn0'), ('3', 'YNyn0'), ('4', 'Dzn0'), ('5', 'Yd11'), ('6', 'lio'), ('7', 'Dyn1/YNyn0')], max_length=2, null=True, verbose_name='CONNECTION'),
        ),
    ]
