# Generated by Django 5.0.6 on 2025-12-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0027_items_plateb_file_alter_trafo_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafo',
            name='COOLING',
            field=models.CharField(blank=True, choices=[('0', 'ONAN'), ('1', 'ONAF'), ('2', 'KNAN'), ('3', 'KNAF'), ('4', 'AN'), ('5', 'AF'), ('6', 'OFAN'), ('7', 'OFAF'), ('8', 'ONWF'), ('9', 'OFWF'), ('10', 'KNAN/KNAF'), ('11', 'OFWONAN/ONAFF')], max_length=2, null=True, verbose_name='COOLING'),
        ),
    ]
