# Generated by Django 4.2.1 on 2026-01-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0028_alter_trafo_cooling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafo',
            name='HV',
            field=models.CharField(blank=True, choices=[('0', '4160'), ('1', '7200'), ('2', '8320'), ('3', '12470'), ('4', '13200'), ('5', '13800'), ('6', '14400'), ('7', '21600'), ('8', '22860'), ('9', '23960'), ('10', '24940'), ('11', '34500'), ('12', '2400Delta X 7200Delta X 4160GY/2400 X 12470GY/7200'), ('13', '12470 X 24940'), ('14', '14400X7200'), ('15', '34500 GrdY/19920')], max_length=2, null=True, verbose_name='HV'),
        ),
        migrations.AlterField(
            model_name='trafo',
            name='LV',
            field=models.CharField(blank=True, choices=[('0', '240/120'), ('1', '480Y/277'), ('2', '208Y/120'), ('3', '4160Y/2400'), ('4', '277/480Y'), ('5', '277'), ('6', '480'), ('7', '208'), ('8', '480/240')], max_length=2, null=True, verbose_name='LV'),
        ),
    ]
