# Generated by Django 5.0.6 on 2026-02-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0029_alter_trafo_hv_alter_trafo_lv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafo',
            name='HV',
            field=models.CharField(blank=True, choices=[('0', '4160'), ('1', '7200'), ('2', '8320'), ('3', '12470'), ('4', '13200'), ('5', '13800'), ('6', '14400'), ('7', '21600'), ('8', '22860'), ('9', '23960'), ('10', '24940'), ('11', '34500'), ('12', '2400Delta X 7200Delta X 4160GY/2400 X 12470GY/7200'), ('13', '12470 X 24940'), ('14', '14400 X 7200'), ('15', '34500 GrdY/19920')], max_length=2, null=True, verbose_name='HV'),
        ),
        migrations.AlterField(
            model_name='trafo',
            name='STANDARD',
            field=models.CharField(blank=True, choices=[('0', 'IEEE C57.12.00'), ('1', 'IEEE C57.12.20'), ('2', 'IEEE C57.12.21'), ('3', 'IEEE C57.12.34'), ('4', 'IEEE C57.12.38')], max_length=2, null=True, verbose_name='STANDARD'),
        ),
    ]
