# Generated by Django 4.2.1 on 2026-02-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0030_alter_trafo_hv_alter_trafo_standard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafo',
            name='KVA',
            field=models.CharField(blank=True, choices=[('0', '75'), ('1', '100'), ('2', '150'), ('3', '167'), ('4', '225'), ('5', '250'), ('6', '300'), ('7', '500'), ('8', '750'), ('9', '1000'), ('10', '1500'), ('11', '2000'), ('12', '2000/2300'), ('13', '2500'), ('14', '2600'), ('15', '3000'), ('16', '3000/3750'), ('17', '3750'), ('18', '5000')], max_length=2, null=True, verbose_name='kVA CAPACITY'),
        ),
    ]
