# Generated by Django 4.2.1 on 2026-02-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0031_alter_trafo_kva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='seq',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True, verbose_name='Serial'),
        ),
    ]
