# Generated by Django 5.0.6 on 2026-02-23 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0032_alter_items_seq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='idTrafo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_Trafo', to='sales.trafo'),
        ),
    ]
