# Generated by Django 5.0.6 on 2026-02-25 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0033_alter_items_idtrafo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trafo',
            options={'verbose_name': 'Plantilla trafo', 'verbose_name_plural': 'Plantillas trafos'},
        ),
    ]
