# Generated by Django 5.0.6 on 2026-02-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0034_alter_trafo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='po_pdfs/'),
        ),
    ]
