# Generated by Django 5.0.6 on 2026-03-02 09:50

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0006_tin_company_type'),
        ('sales', '0035_quotes_pdf_file'),
        ('stakeholders', '0007_alter_supplier_numberidsupplier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotes',
            options={'verbose_name': 'Cotización master', 'verbose_name_plural': 'Cotizaciones master'},
        ),
        migrations.RemoveField(
            model_name='quotes',
            name='idTinExecuting',
        ),
        migrations.AddField(
            model_name='items',
            name='unitCostInt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo unitario interno'),
        ),
        migrations.AddField(
            model_name='items',
            name='unitCostWO',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo unitario interno'),
        ),
        migrations.CreateModel(
            name='IntQuotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('currency', models.CharField(blank=True, choices=[('0', 'PEN'), ('1', 'USD'), ('2', 'EUR')], max_length=1, null=True, verbose_name='Moneda')),
                ('initialAmount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Monto inicial')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Monto')),
                ('dateOrder', models.DateField(blank=True, null=True, verbose_name='Fecha de solicitud')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Fecha de entrega')),
                ('payMethod', models.CharField(blank=True, choices=[('1', 'Contado'), ('0', 'Credito')], default='0', max_length=1, null=True, verbose_name='Método de pago')),
                ('poNumber', models.CharField(blank=True, max_length=10, null=True, verbose_name='PO number')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='intpo_pdfs/')),
                ('idClient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='int_client', to='stakeholders.client')),
                ('idTinReceiving', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='int_company_receiving', to='cuentas.tin')),
            ],
            options={
                'verbose_name': 'Cotización Interna',
                'verbose_name_plural': 'Cotizaciones Internas',
            },
        ),
        migrations.AddField(
            model_name='items',
            name='idTrafoIntQuote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_IntQuote', to='sales.intquotes'),
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('currency', models.CharField(blank=True, choices=[('0', 'PEN'), ('1', 'USD'), ('2', 'EUR')], max_length=1, null=True, verbose_name='Moneda')),
                ('initialAmount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Monto inicial')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Monto')),
                ('dateOrder', models.DateField(blank=True, null=True, verbose_name='Fecha de solicitud')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Fecha de entrega')),
                ('payMethod', models.CharField(blank=True, choices=[('1', 'Contado'), ('0', 'Credito')], default='0', max_length=1, null=True, verbose_name='Método de pago')),
                ('woNumber', models.CharField(blank=True, max_length=10, null=True, verbose_name='PO number')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='Wo_pdfs/')),
                ('idSupplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_supplier', to='stakeholders.supplier')),
                ('idTinReceiving', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='int_company_executing', to='cuentas.tin')),
            ],
            options={
                'verbose_name': 'Orden de trabajo',
                'verbose_name_plural': 'Ordenes de Trabajos',
            },
        ),
        migrations.AddField(
            model_name='items',
            name='idWorkOrder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_WorkOrder', to='sales.workorder'),
        ),
    ]
