# Generated by Django 5.0.6 on 2026-03-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0036_alter_quotes_options_remove_quotes_idtinexecuting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='woNumber',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='PO number'),
        ),
    ]
