# Generated by Django 5.0.6 on 2026-03-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0038_alter_workorder_wonumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='poNumber',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='PO number'),
        ),
    ]
