# Generated by Django 5.0.6 on 2026-03-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0039_alter_quotes_ponumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='unitCostWO',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo unitario WO'),
        ),
    ]
