# Generated by Django 5.0.6 on 2024-12-19 10:54

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actividades', '0001_initial'),
        ('clientes', '0001_initial'),
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentsUploaded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('fileName', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de archivo')),
                ('observations', models.CharField(blank=True, max_length=100, null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Documento subido',
                'verbose_name_plural': 'Documentos subidos',
            },
        ),
        migrations.CreateModel(
            name='ExpenseSubCategories',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nameSubCategoy', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nombre de subcategoria')),
                ('category', models.CharField(blank=True, choices=[('0', 'Producto'), ('1', 'Compras activos'), ('2', 'Fijos'), ('3', 'Variables'), ('4', 'Impuestos'), ('5', 'Cambio de moneda'), ('6', 'Deducciones'), ('7', 'Retiros'), ('8', 'Otros')], default='8', max_length=1, null=True, verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Categoria de gasto',
                'verbose_name_plural': 'Categorias de gastos',
            },
        ),
        migrations.CreateModel(
            name='IncomeSubCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nameSubCategoy', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre de subcategoria')),
            ],
            options={
                'verbose_name': 'Categoria de ingreso',
                'verbose_name_plural': 'Categorias de ingresos',
            },
        ),
        migrations.CreateModel(
            name='InternalTransfers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('SourceAmount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto origen')),
                ('DestinationAmount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto destino')),
                ('opNumber', models.PositiveIntegerField(blank=True, null=True, verbose_name='Numero de operacion')),
            ],
            options={
                'verbose_name': 'Transferencia',
                'verbose_name_plural': 'Transferencias',
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('dateTime', models.DateTimeField(verbose_name='Fecha de movimiento')),
                ('category', models.CharField(blank=True, choices=[('0', 'remuneracion'), ('1', 'proveedor'), ('2', 'servicio'), ('3', 'comision'), ('4', 'compra'), ('5', 'impuestos'), ('6', 'caja chica'), ('7', 'Transferencia interna'), ('8', 'abono pedido'), ('9', 'venta'), ('10', 'alquiler'), ('11', 'donacion'), ('12', 'suscripcion'), ('13', 'prestamo')], max_length=20, verbose_name='Categoria')),
                ('idTransaction', models.CharField(blank=True, max_length=100, null=True, verbose_name='IdMovimiento')),
                ('transactionName', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de movimiento')),
                ('clientName', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de receptor')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('currency', models.CharField(blank=True, choices=[('0', 'Soles'), ('1', 'Dolares')], max_length=20, verbose_name='Tipo de moneda')),
                ('transactionType', models.CharField(blank=True, choices=[('0', 'egreso'), ('1', 'ingreso')], max_length=20, verbose_name='Tipo de movimiento')),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Saldo')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
            },
        ),
        migrations.CreateModel(
            name='BankMovements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date', models.DateField(verbose_name='Fecha y hora')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripción EEC')),
                ('transactionType', models.CharField(blank=True, choices=[('0', 'egreso'), ('1', 'ingreso')], max_length=1, verbose_name='Tipo de movimiento')),
                ('conciliationType', models.CharField(blank=True, choices=[('0', 'Documentaria'), ('1', 'Movimiento')], default='0', max_length=1, null=True, verbose_name='Tipo de conciliacion')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='saldo')),
                ('amountReconcilied', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto conciliado')),
                ('opNumber', models.CharField(blank=True, max_length=10, null=True, verbose_name='Numero de operacion')),
                ('conciliated', models.BooleanField(default=False, verbose_name='Conciliado?')),
                ('flagUpdate', models.BooleanField(default=False, verbose_name='Actualizado?')),
                ('idAccount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuentas.account')),
                ('idMovement', models.ManyToManyField(blank=True, to='movimientos.bankmovements')),
                ('originDestination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Movimiento bancario',
                'verbose_name_plural': 'Movimientos bancarios',
            },
        ),
        migrations.CreateModel(
            name='Conciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('type', models.CharField(choices=[('0', 'documento'), ('1', 'movimiento')], max_length=1, verbose_name='Tipo de conciliacion')),
                ('amountReconcilied', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto conciliado')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('exchangeRate', models.DecimalField(decimal_places=3, default=1, max_digits=4, verbose_name='Tipo de cambio')),
                ('idMovArrival', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mov_destino', to='movimientos.bankmovements')),
                ('idMovOrigin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mov_origen', to='movimientos.bankmovements')),
            ],
            options={
                'verbose_name': 'Conciliacion',
                'verbose_name_plural': 'Conciliaciones',
            },
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('month_dec', models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], null=True, verbose_name='Mes de declaración')),
                ('year_dec', models.PositiveIntegerField(blank=True, null=True, verbose_name='Año de declaración')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Fecha de emisión')),
                ('typeInvoice', models.CharField(blank=True, choices=[('0', 'Factura'), ('1', 'RHE'), ('2', 'Doc del exterior'), ('3', 'Impuesto'), ('4', 'Planilla'), ('5', 'Otros')], max_length=1, null=True, verbose_name='Tipo de comprobante')),
                ('typeCurrency', models.CharField(blank=True, choices=[('0', 'S/.'), ('1', '$'), ('2', '€')], max_length=1, null=True, verbose_name='Tipo de moneda')),
                ('idInvoice', models.CharField(blank=True, max_length=25, null=True, verbose_name='Id de comprobante')),
                ('ActivitiesCategory', models.CharField(blank=True, choices=[('0', 'pedidos trafos'), ('1', 'comision'), ('2', 'proyecto')], max_length=10, null=True, verbose_name='Categoria de actividades')),
                ('expensesCategory', models.CharField(blank=True, choices=[('0', 'Ag. Aduanas'), ('1', 'Mercadería'), ('2', 'Caja'), ('3', 'Vuelos'), ('4', 'Adicionales'), ('5', 'Otros')], max_length=2, null=True, verbose_name='Categoria de egresos')),
                ('incomeCategory', models.CharField(blank=True, choices=[('0', 'abono pedido'), ('1', 'venta'), ('2', 'alquiler'), ('3', 'donacion'), ('4', 'suscripcion'), ('5', 'prestamo'), ('6', 'Transferencia interna')], max_length=1, null=True, verbose_name='Categoria de ingresos')),
                ('detraction', models.CharField(choices=[('0', 'No requiere'), ('1', 'Pendiente'), ('2', 'Completado')], default='0', max_length=1, verbose_name='Detracción - Factura')),
                ('shippingGuide', models.CharField(choices=[('0', 'No requiere'), ('1', 'Pendiente'), ('2', 'Completado')], default='0', max_length=1, verbose_name='Guia de remisión - Factura')),
                ('retention', models.CharField(choices=[('0', 'No requiere'), ('1', 'Pendiente'), ('2', 'Completado')], default='0', max_length=1, verbose_name='Retención - RHE')),
                ('subCategoryPallRoy', models.CharField(blank=True, choices=[('0', 'remuneracion'), ('1', 'AFP'), ('2', 'CTS'), ('3', 'seguros'), ('4', 'bono'), ('5', 'otro')], max_length=1, null=True, verbose_name='Sub Categoria planilla')),
                ('subCategoryCashBox', models.CharField(blank=True, choices=[('0', 'movilidad'), ('1', 'oficina'), ('2', 'alimentacion'), ('3', 'limpieza'), ('4', 'repuestos'), ('5', 'personal'), ('6', 'otro')], max_length=2, null=True, verbose_name='Sub Categoria caja chica')),
                ('annotation', models.CharField(blank=True, choices=[('1', 'anticipo'), ('1', 'pago final'), ('2', 'total')], max_length=2, null=True, verbose_name='Anotaciones')),
                ('contabilidad', models.CharField(blank=True, choices=[('0', 'Agente de aduana'), ('1', 'Caja chica'), ('2', 'Caja General'), ('3', 'Caja General ventas'), ('4', 'RHE general'), ('5', 'Adicional'), ('6', 'Personal'), ('7', 'PL'), ('8', 'renta')], max_length=2, null=True, verbose_name='Sub Categoria contabilidad')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripción')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto')),
                ('amountReconcilied', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto conciliado')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='conciliaciones_pdfs/')),
                ('idClient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('idCommission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actividades.commissions')),
                ('idProject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actividades.projects')),
                ('idTrafoOrder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actividades.trafoorder')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
    ]
