# Generated by Django 5.0.6 on 2024-07-10 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0001_initial'),
        ('movimientos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bankreconciliation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Reconciliation_user', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='documentsuploaded',
            name='idAccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuentas.account'),
        ),
        migrations.AddField(
            model_name='bankmovements',
            name='idDoc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movimientos.documentsuploaded'),
        ),
        migrations.AddField(
            model_name='internaltransfers',
            name='idDestinationAcount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destino', to='cuentas.account'),
        ),
        migrations.AddField(
            model_name='internaltransfers',
            name='idSourceAcount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origen', to='cuentas.account'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='idAccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuentas.account'),
        ),
    ]
