# Generated by Django 5.0.6 on 2024-12-20 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='ActivitiesCategory',
        ),
    ]
