# Generated by Django 5.0.6 on 2024-07-11 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankreconciliation',
            name='pdf_file',
            field=models.FileField(null=True, upload_to='pdfs/'),
        ),
    ]
