# Generated by Django 5.0.6 on 2024-12-23 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0003_remove_documents_activitiescategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='expensesCategory',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='idCommission',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='idProject',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='idTrafoOrder',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='incomeCategory',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='subCategoryCashBox',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='subCategoryPallRoy',
        ),
    ]
