# Generated by Django 5.0.6 on 2024-12-23 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_alter_account_nickname'),
        ('movimientos', '0004_remove_documents_expensescategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='idTin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuentas.tin'),
        ),
    ]
