# Generated by Django 5.0.6 on 2025-03-12 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_email'),
        ('movimientos', '0006_alter_documents_annotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankmovements',
            name='intermediary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intermeddiario', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='bankmovements',
            name='justification',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Justification'),
        ),
    ]
