# Generated by Django 5.0.6 on 2024-08-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0006_rename_bankreconciliation_documents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='idBankMovements',
        ),
        migrations.AddField(
            model_name='bankmovements',
            name='idDocs',
            field=models.ManyToManyField(blank=True, to='movimientos.documents'),
        ),
    ]
