# Generated by Django 5.0.6 on 2025-04-23 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0007_bankmovements_intermediary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankmovements',
            name='justification',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Justification'),
        ),
        migrations.AlterField(
            model_name='bankmovements',
            name='opNumber',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Numero de operacion'),
        ),
    ]
