# Generated by Django 5.0.6 on 2024-08-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0007_remove_documents_idbankmovements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='month',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], null=True, verbose_name='Mes de declaración'),
        ),
        migrations.AddField(
            model_name='documents',
            name='typeCurrency',
            field=models.CharField(blank=True, choices=[('0', 'S/.'), ('1', '$'), ('2', '€')], max_length=1, null=True, verbose_name='Tipo de moneda'),
        ),
        migrations.AddField(
            model_name='documents',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Año de declaración'),
        ),
    ]
