# Generated by Django 5.0.6 on 2024-08-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0008_documents_month_documents_typecurrency_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documents',
            options={'verbose_name': 'Documento', 'verbose_name_plural': 'Documentos'},
        ),
        migrations.RenameField(
            model_name='documents',
            old_name='month',
            new_name='month_dec',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='year',
        ),
        migrations.AddField(
            model_name='documents',
            name='year_dec',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Año de declaración'),
        ),
    ]
