# Generated by Django 5.0.6 on 2024-08-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0009_alter_documents_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankmovements',
            name='idDocs',
            field=models.ManyToManyField(blank=True, related_name='docs', to='movimientos.documents'),
        ),
    ]
