# Generated by Django 5.0.6 on 2025-04-26 12:41

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0010_alter_bankmovements_justification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='idInvoice',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Id de comprobante'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='typeInvoice',
            field=models.CharField(blank=True, choices=[('0', 'Factura'), ('1', 'RHE'), ('2', 'Doc del exterior'), ('3', 'Impuesto'), ('4', 'Planilla'), ('5', 'Nota de credito'), ('11', 'Liq'), ('7', 'Diario'), ('8', 'DUA'), ('9', 'FT Vuelo'), ('10', 'Vuelo'), ('11', 'Planilla'), ('12', 'Planilla'), ('13', 'Otros')], max_length=2, null=True, verbose_name='Tipo de comprobante'),
        ),
        migrations.CreateModel(
            name='OtherDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('typeDoc', models.CharField(blank=True, choices=[('0', 'Guia de remision'), ('1', 'Liquidacion'), ('9', 'Otros')], max_length=2, null=True, verbose_name='Tipo de comprobante')),
                ('idDocument', models.CharField(blank=True, max_length=50, null=True, verbose_name='Id de comprobante')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='otherDocs_pdfs/')),
                ('idDoc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OtheDocuments', to='movimientos.documents')),
            ],
            options={
                'verbose_name': 'Documento complementario',
                'verbose_name_plural': 'Documentos complementarios',
            },
        ),
    ]
