# Generated by Django 5.0.6 on 2025-04-28 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0011_alter_documents_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conciliation',
            name='exchangeRate',
        ),
        migrations.AddField(
            model_name='conciliation',
            name='equivalentAmount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Monto equivalente'),
        ),
    ]
