# Generated by Django 5.0.6 on 2024-08-27 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0012_remove_documents_idmovement_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankmovements',
            old_name='typeConciliation',
            new_name='conciliationType',
        ),
    ]
