# Generated by Django 5.0.6 on 2025-05-05 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0012_remove_conciliation_exchangerate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documents',
            options={'verbose_name': 'Documento contable', 'verbose_name_plural': 'Documentos contables'},
        ),
        migrations.AlterField(
            model_name='documents',
            name='typeInvoice',
            field=models.CharField(blank=True, choices=[('0', 'Factura'), ('1', 'RHE'), ('2', 'Doc del exterior'), ('3', 'Impuesto'), ('4', 'Planilla'), ('5', 'Nota de credito'), ('11', 'Liq'), ('7', 'Diario'), ('8', 'DUA'), ('9', 'Boleto Aéreo'), ('11', 'Liquidacion'), ('12', 'percepcion'), ('13', 'Otros')], max_length=2, null=True, verbose_name='Tipo de comprobante'),
        ),
    ]
