# Generated by Django 5.0.6 on 2024-08-27 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0013_rename_typeconciliation_bankmovements_conciliationtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankmovements',
            name='idMovement',
        ),
        migrations.AddField(
            model_name='bankmovements',
            name='idMovement',
            field=models.ManyToManyField(null=True, to='movimientos.bankmovements'),
        ),
    ]
