# Generated by Django 5.0.6 on 2024-08-28 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0016_remove_bankmovements_idmovement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankmovements',
            name='idMovement',
        ),
        migrations.AddField(
            model_name='bankmovements',
            name='idMovement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movimientos.bankmovements'),
        ),
    ]
