# Generated by Django 5.0.6 on 2024-08-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0018_remove_bankmovements_idmovement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankmovements',
            name='idMovement',
            field=models.ManyToManyField(blank=True, to='movimientos.bankmovements'),
        ),
    ]
