# Generated by Django 5.0.6 on 2024-08-30 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0020_remove_bankmovements_idmovement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankmovements',
            name='conciliated',
            field=models.BooleanField(default=False, verbose_name='Conciliado?'),
        ),
    ]
