# Generated by Django 5.0.6 on 2024-08-31 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0022_remove_bankmovements_idmovement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankmovements',
            name='flagUpdate',
            field=models.BooleanField(default=False, verbose_name='Actualizado?'),
        ),
    ]
