# Generated by Django 5.0.6 on 2024-09-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0023_bankmovements_flagupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankmovements',
            name='idMovement',
            field=models.ManyToManyField(to='movimientos.bankmovements'),
        ),
    ]
