# Generated by Django 5.0.6 on 2024-09-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0024_alter_bankmovements_idmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto'),
        ),
    ]
