# Generated by Django 5.0.6 on 2024-09-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0025_documents_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankmovements',
            name='idMovement',
            field=models.ManyToManyField(null=True, to='movimientos.bankmovements'),
        ),
    ]
