# Generated by Django 5.0.6 on 2024-09-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0026_alter_bankmovements_idmovement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankmovements',
            name='idMovement',
            field=models.ManyToManyField(blank=True, to='movimientos.bankmovements'),
        ),
    ]
