# Generated by Django 5.0.6 on 2024-09-15 20:22

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0027_alter_bankmovements_idmovement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('type', models.CharField(choices=[('0', 'documento'), ('1', 'movimiento')], max_length=1, verbose_name='Tipo de conciliacion')),
                ('amountConcilied', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto conciliado')),
                ('idDoc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movimientos.documents')),
                ('idMovArrival', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mov_destino', to='movimientos.bankmovements')),
                ('idMovOrigin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mov_origen', to='movimientos.bankmovements')),
            ],
            options={
                'verbose_name': 'Conciliacion',
                'verbose_name_plural': 'Conciliaciones',
            },
        ),
    ]
