# Generated by Django 5.0.6 on 2024-09-15 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0028_conciliation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conciliation',
            old_name='amountConcilied',
            new_name='amountReconcilied',
        ),
    ]
