# Generated by Django 5.0.6 on 2024-09-23 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0029_rename_amountconcilied_conciliation_amountreconcilied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankmovements',
            name='conciliationType',
            field=models.CharField(blank=True, choices=[('0', 'Documentaria'), ('1', 'Movimiento')], default='0', max_length=1, null=True, verbose_name='Tipo de conciliacion'),
        ),
        migrations.AlterField(
            model_name='conciliation',
            name='idDoc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doc_conciliation', to='movimientos.documents'),
        ),
    ]
