# Generated by Django 5.0.6 on 2024-10-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0030_alter_bankmovements_conciliationtype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conciliation',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
    ]
