# Generated by Django 5.0.6 on 2024-10-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0032_conciliation_exchangerate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='expensesCategory',
            field=models.CharField(blank=True, choices=[('0', 'Ag. Aduanas'), ('1', 'Mercadería'), ('2', 'Caja'), ('3', 'impuesVuelostos'), ('4', 'Adicionales'), ('5', 'Otros')], max_length=2, null=True, verbose_name='Categoria de egresos'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='typeInvoice',
            field=models.CharField(blank=True, choices=[('0', 'Factura'), ('1', 'RHE'), ('2', 'Doc del exterior'), ('3', 'Impuesto'), ('4', 'Planilla'), ('5', 'Otros')], max_length=1, null=True, verbose_name='Tipo de comprobante'),
        ),
    ]
