# Generated by Django 5.0.6 on 2024-12-18 21:09

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_cliente_bankname'),
        ('movimientos', '0032_conciliation_exchangerate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseSubCategories',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nameSubCategoy', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nombre de subcategoria')),
                ('category', models.CharField(blank=True, choices=[('0', 'Producto'), ('1', 'Compras activos'), ('2', 'Fijos'), ('3', 'Variables'), ('4', 'Impuestos'), ('5', 'Cambio de moneda'), ('6', 'Deducciones'), ('7', 'Retiros'), ('8', 'Otros')], max_length=1, null=True, verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Categoria de gasto',
                'verbose_name_plural': 'Categorias de gastos',
            },
        ),
        migrations.CreateModel(
            name='IncomeSubCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nameSubCategoy', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre de subcategoria')),
            ],
            options={
                'verbose_name': 'Categoria de ingreso',
                'verbose_name_plural': 'Categorias de ingresos',
            },
        ),
        migrations.AddField(
            model_name='bankmovements',
            name='originDestination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='documents',
            name='detraction',
            field=models.CharField(choices=[('0', 'No requiere'), ('1', 'Pendiente'), ('2', 'Completado')], default='0', max_length=1, verbose_name='Detracción - Factura'),
        ),
        migrations.AddField(
            model_name='documents',
            name='retention',
            field=models.CharField(choices=[('0', 'No requiere'), ('1', 'Pendiente'), ('2', 'Completado')], default='0', max_length=1, verbose_name='Retención - RHE'),
        ),
        migrations.AddField(
            model_name='documents',
            name='shippingGuide',
            field=models.CharField(choices=[('0', 'No requiere'), ('1', 'Pendiente'), ('2', 'Completado')], default='0', max_length=1, verbose_name='Guia de remisión - Factura'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='expensesCategory',
            field=models.CharField(blank=True, choices=[('0', 'Ag. Aduanas'), ('1', 'Mercadería'), ('2', 'Caja'), ('3', 'Vuelos'), ('4', 'Adicionales'), ('5', 'Otros')], max_length=2, null=True, verbose_name='Categoria de egresos'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='typeInvoice',
            field=models.CharField(blank=True, choices=[('0', 'Factura'), ('1', 'RHE'), ('2', 'Doc del exterior'), ('3', 'Impuesto'), ('4', 'Planilla'), ('5', 'Otros')], max_length=1, null=True, verbose_name='Tipo de comprobante'),
        ),
        migrations.AddField(
            model_name='bankmovements',
            name='expenseSubCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movimientos.expensesubcategories'),
        ),
        migrations.AddField(
            model_name='bankmovements',
            name='incomeSubCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movimientos.incomesubcategories'),
        ),
    ]
