# Generated by Django 5.0.6 on 2024-10-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0033_alter_documents_expensescategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='detraction',
            field=models.CharField(choices=[('0', 'No requiere'), ('1', 'Pendiente'), ('2', 'Completado')], default='0', max_length=1, verbose_name='Detracción - Factura'),
        ),
        migrations.AddField(
            model_name='documents',
            name='retention',
            field=models.CharField(choices=[('0', 'No requiere'), ('1', 'Pendiente'), ('2', 'Completado')], default='0', max_length=1, verbose_name='Retención - RHE'),
        ),
        migrations.AddField(
            model_name='documents',
            name='shippingGuide',
            field=models.CharField(choices=[('0', 'No requiere'), ('1', 'Pendiente'), ('2', 'Completado')], default='0', max_length=1, verbose_name='Guia de remisión - Factura'),
        ),
    ]
