# Generated by Django 5.0.6 on 2024-10-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0034_documents_detraction_documents_retention_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='expensesCategory',
            field=models.CharField(blank=True, choices=[('0', 'Ag. Aduanas'), ('1', 'Mercadería'), ('2', 'Caja'), ('3', 'Vuelos'), ('4', 'Adicionales'), ('5', 'Otros')], max_length=2, null=True, verbose_name='Categoria de egresos'),
        ),
    ]
