# Generated by Django 5.0.6 on 2024-12-03 16:36

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0035_alter_documents_expensescategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseSubCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nameSubCategoy', models.CharField(blank=True, max_length=20, null=True, verbose_name='Observaciones')),
                ('category', models.CharField(blank=True, choices=[('0', 'Producto'), ('1', 'Compras activos'), ('2', 'Fijos'), ('3', 'Variables'), ('4', 'Impuestos'), ('5', 'Cambio de moneda'), ('6', 'Deducciones'), ('7', 'Retiros'), ('8', 'Otros')], max_length=1, null=True, verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Categoria de gasto',
                'verbose_name_plural': 'Categorias de gastos',
            },
        ),
        migrations.AddField(
            model_name='bankmovements',
            name='subCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movimientos.expensesubcategories'),
        ),
    ]
