# Generated by Django 5.0.6 on 2024-12-03 17:22

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0036_expensesubcategories_bankmovements_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeSubCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nameSubCategoy', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nombre de subcategoria')),
            ],
            options={
                'verbose_name': 'Categoria de ingreso',
                'verbose_name_plural': 'Categorias de ingresos',
            },
        ),
        migrations.AlterField(
            model_name='expensesubcategories',
            name='nameSubCategoy',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nombre de subcategoria'),
        ),
    ]
