# Generated by Django 5.0.6 on 2024-12-03 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0037_incomesubcategories_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankmovements',
            old_name='subCategory',
            new_name='expenseSubCategory',
        ),
        migrations.AddField(
            model_name='bankmovements',
            name='incomeSubCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movimientos.incomesubcategories'),
        ),
    ]
