# Generated by Django 5.0.6 on 2024-12-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0038_rename_subcategory_bankmovements_expensesubcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomesubcategories',
            name='nameSubCategoy',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre de subcategoria'),
        ),
    ]
