# Generated by Django 5.0.6 on 2024-12-12 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_cliente_bankname'),
        ('movimientos', '0039_alter_incomesubcategories_namesubcategoy'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankmovements',
            name='originDestination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
    ]
