# Generated by Django 5.0.6 on 2024-12-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0040_bankmovements_origindestination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensesubcategories',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
