# Generated by Django 5.0.6 on 2025-06-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotetraking',
            name='event',
            field=models.CharField(choices=[('0', 'Recibido'), ('1', 'Respondido'), ('2', 'Aprobado'), ('3', 'Rechazado'), ('4', 'Eliminado')], default='0', max_length=1, verbose_name='Recibido'),
        ),
    ]
