# Generated by Django 5.0.6 on 2025-06-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_alter_quotetraking_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafoquote',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto'),
        ),
    ]
