# Generated by Django 5.0.6 on 2024-07-10 13:21

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('activity', models.CharField(verbose_name='Actividad')),
                ('startDate', models.DateField(verbose_name='Fecha de incio')),
                ('endDate', models.DateField(verbose_name='Fecha de finalizacion')),
                ('status', models.CharField(blank=True, choices=[('0', 'en proceso'), ('1', 'culminado'), ('2', 'cancelado'), ('3', 'en espera')], max_length=1, null=True, verbose_name='Estado')),
                ('comentary', models.CharField(verbose_name='comentario')),
            ],
            options={
                'verbose_name': 'Tarea asignada',
                'verbose_name_plural': 'Tareas asignadas',
            },
        ),
        migrations.CreateModel(
            name='Commissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('commissionName', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de comision')),
                ('place', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lugar')),
                ('startDate', models.DateField(verbose_name='Fecha de incio')),
                ('endDate', models.DateField(verbose_name='Fecha de finalizacion')),
                ('status', models.CharField(blank=True, choices=[('0', 'Activo'), ('1', 'Culminado'), ('2', 'Pausado'), ('3', 'Suspendido'), ('4', 'Cancelado')], max_length=50, verbose_name='Estado')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Comision de trabajo',
                'verbose_name_plural': 'Comisiones de trabajo',
            },
        ),
        migrations.CreateModel(
            name='DailyTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('activity', models.TextField(verbose_name='Actividad')),
                ('type', models.CharField(blank=True, choices=[('0', 'jornada diaria'), ('1', 'horas extra'), ('2', 'otro')], max_length=1, null=True, verbose_name='Tipo de jornada')),
                ('startTime', models.TimeField(blank=True, null=True, verbose_name='Hora de inicio')),
                ('endTime', models.TimeField(blank=True, null=True, verbose_name='Hora de termino')),
            ],
            options={
                'verbose_name': 'Tarea diaria',
                'verbose_name_plural': 'Tareas diarias',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('projectName', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de projecto')),
                ('startDate', models.DateField(verbose_name='Fecha de incio')),
                ('endDate', models.DateField(verbose_name='Fecha de finalizacion')),
                ('status', models.CharField(blank=True, choices=[('0', 'Activo'), ('1', 'Culminado'), ('2', 'Pausado'), ('3', 'Suspendido'), ('4', 'Cancelado')], max_length=50, verbose_name='Estado')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
        migrations.CreateModel(
            name='TrafoOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idOrder', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Id orden')),
                ('dateOrder', models.DateField(verbose_name='Fecha de pedido')),
                ('deadline', models.DateField(verbose_name='Fecha de entrega')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo')),
                ('numberUnits', models.PositiveIntegerField(blank=True, null=True, verbose_name='Numero de unidades')),
                ('IdOrderState', models.CharField(blank=True, default='0', max_length=25, null=True, verbose_name='Estado de orden')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='TrafoTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('idOrder', models.IntegerField(blank=True, null=True, verbose_name='Id Orders')),
                ('dateChange', models.DateTimeField(verbose_name='Fecha')),
                ('orderState', models.CharField(choices=[('0', 'Creado'), ('1', 'Fabricado'), ('2', 'Enviado'), ('3', 'Completado'), ('4', 'Cancelado')], max_length=1, verbose_name='Estado de orden')),
            ],
            options={
                'verbose_name': 'pedido seguimiento ',
                'verbose_name_plural': 'pedidos seguimientos ',
            },
        ),
    ]
