# Generated by Django 5.0.6 on 2024-12-19 10:54

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('activity', models.CharField(verbose_name='Actividad')),
                ('startDate', models.DateField(verbose_name='Fecha de incio')),
                ('endDate', models.DateField(verbose_name='Fecha de finalizacion')),
                ('status', models.CharField(blank=True, choices=[('0', 'en proceso'), ('1', 'culminado'), ('2', 'cancelado'), ('3', 'en espera')], max_length=1, null=True, verbose_name='Estado')),
                ('comentary', models.CharField(verbose_name='comentario')),
            ],
            options={
                'verbose_name': 'Tarea asignada',
                'verbose_name_plural': 'Tareas asignadas',
            },
        ),
        migrations.CreateModel(
            name='Commissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('commissionName', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de comision')),
                ('place', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lugar')),
                ('startDate', models.DateField(verbose_name='Fecha de incio')),
                ('endDate', models.DateField(verbose_name='Fecha de finalizacion')),
                ('status', models.CharField(blank=True, choices=[('0', 'Activo'), ('1', 'Culminado'), ('2', 'Pausado'), ('3', 'Suspendido'), ('4', 'Cancelado')], max_length=50, verbose_name='Estado')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Comision de trabajo',
                'verbose_name_plural': 'Comisiones de trabajo',
            },
        ),
        migrations.CreateModel(
            name='DailyTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('activity', models.TextField(verbose_name='Actividad')),
                ('is_overTime', models.BooleanField(default=False, verbose_name='Horas extra')),
                ('startTime', models.TimeField(blank=True, null=True, verbose_name='Hora de inicio')),
                ('endTime', models.TimeField(blank=True, null=True, verbose_name='Hora de termino')),
            ],
            options={
                'verbose_name': 'Tarea diaria',
                'verbose_name_plural': 'Tareas diarias',
            },
        ),
        migrations.CreateModel(
            name='EmailSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('typeMail', models.CharField(blank=True, choices=[('0', 'inicial'), ('1', 'cotizacion'), ('2', 'aprobación')], default='0', max_length=1, null=True, verbose_name='Tipo')),
                ('sendFlag', models.BooleanField(default=False, verbose_name='Enviado')),
                ('subject', models.CharField(max_length=100, verbose_name='Subject')),
                ('body', models.TextField(verbose_name='Body')),
                ('sender', models.CharField(default='jh', max_length=100, verbose_name='Emisor')),
                ('recipients', models.CharField(max_length=100, verbose_name='Receptores')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('projectName', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de projecto')),
                ('startDate', models.DateField(verbose_name='Fecha de incio')),
                ('endDate', models.DateField(verbose_name='Fecha de finalizacion')),
                ('status', models.CharField(blank=True, choices=[('0', 'Activo'), ('1', 'Culminado'), ('2', 'Pausado'), ('3', 'Suspendido'), ('4', 'Cancelado')], max_length=50, verbose_name='Estado')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
        migrations.CreateModel(
            name='SuggestionBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('suggestion', models.TextField(verbose_name='Sugerencia')),
                ('area', models.CharField(blank=True, choices=[('1', 'Contabilidad'), ('2', 'Supervisor producción'), ('5', 'Adquisiciones'), ('6', 'Finanzas'), ('8', 'Consultor')], max_length=1, verbose_name='Area')),
            ],
            options={
                'verbose_name': 'Sugerencia',
                'verbose_name_plural': 'Sugerencias',
            },
        ),
        migrations.CreateModel(
            name='TrafoOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('idOrder', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Id orden')),
                ('dateOrder', models.DateField(verbose_name='Fecha de pedido')),
                ('deadline', models.DateField(verbose_name='Fecha de entrega')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo')),
                ('numberUnits', models.PositiveIntegerField(blank=True, null=True, verbose_name='Numero de unidades')),
                ('IdOrderState', models.CharField(blank=True, default='0', max_length=25, null=True, verbose_name='Estado de orden')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='TrafoQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('idQuote', models.CharField(max_length=100, unique=True, verbose_name='RFQ Number')),
                ('userClient', models.CharField(blank=True, max_length=20, null=True, verbose_name='Cliente')),
                ('dateOrder', models.DateField(verbose_name='Fecha de pedido')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Fecha de entrega')),
                ('q1', models.CharField(choices=[('4', 'creado'), ('0', 'espera'), ('1', 'completado'), ('3', 'observado'), ('2', 'cancelado')], default='0', max_length=1, verbose_name='Recibido')),
                ('q2', models.CharField(choices=[('4', 'creado'), ('0', 'espera'), ('1', 'completado'), ('3', 'observado'), ('2', 'cancelado')], default='4', max_length=1, verbose_name='Cotizacion')),
                ('q3', models.CharField(choices=[('4', 'creado'), ('0', 'espera'), ('1', 'completado'), ('3', 'observado'), ('2', 'cancelado')], default='4', max_length=1, verbose_name='Respuesta de cliente')),
                ('q4', models.CharField(choices=[('4', 'creado'), ('0', 'espera'), ('1', 'completado'), ('3', 'observado'), ('2', 'cancelado')], default='4', max_length=1, verbose_name='Atendido')),
                ('dt1', models.DateTimeField(blank=True, null=True, verbose_name='dt1')),
                ('dt2', models.DateTimeField(blank=True, null=True, verbose_name='dt2')),
                ('dt3', models.DateTimeField(blank=True, null=True, verbose_name='dt3')),
                ('dt4', models.DateTimeField(blank=True, null=True, verbose_name='dt4')),
                ('poStatus', models.CharField(blank=True, choices=[('0', 'no PO'), ('1', 'PO')], default='0', max_length=1, null=True, verbose_name='Estado PO')),
                ('trakingStatus', models.CharField(blank=True, choices=[('0', 'recibido'), ('1', 'insumos'), ('2', 'fabricado'), ('3', 'transporte interno'), ('4', 'transporte maritimo'), ('5', 'arribado'), ('6', 'entregado')], default='0', max_length=1, null=True, verbose_name='Seguimiento')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('condition', models.CharField(blank=True, choices=[('0', 'recibida'), ('1', 'enviada'), ('2', 'aprobada')], default='0', max_length=1, null=True, verbose_name='Condicion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trafos',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('KVA', models.CharField(blank=True, choices=[('0', '15'), ('1', '30'), ('2', '75'), ('3', '100'), ('4', '167'), ('5', '200'), ('6', '250'), ('7', '400'), ('8', '500'), ('9', '600'), ('10', '750'), ('11', '1000'), ('12', '1500'), ('13', '2000')], max_length=2, null=True, verbose_name='kVA CAPACITY')),
                ('HVTAP', models.CharField(blank=True, choices=[('0', 'K-Tap - HV'), ('1', 'Fix HV')], max_length=2, null=True, verbose_name='HV TAP')),
                ('KTapHV', models.CharField(blank=True, choices=[('0', '12700/7200'), ('1', '24940/14400')], max_length=2, null=True, verbose_name='K Tap HV')),
                ('FIXHV', models.CharField(blank=True, choices=[('0', '7200'), ('1', '12470'), ('2', '22900')], max_length=2, null=True, verbose_name='FIX HV')),
                ('LV', models.CharField(blank=True, choices=[('0', '120/240'), ('1', '277/480')], max_length=2, null=True, verbose_name='LV')),
                ('HZ', models.CharField(blank=True, choices=[('0', '50'), ('1', '60')], max_length=2, null=True, verbose_name='HZ')),
                ('TYPE', models.CharField(blank=True, choices=[('0', 'Mono-phasic'), ('1', 'Three-phasic')], max_length=2, null=True, verbose_name='TYPE')),
                ('MOUNTING', models.CharField(blank=True, choices=[('0', 'Pole'), ('1', 'Standard'), ('2', 'Feed Through Pad')], max_length=2, null=True, verbose_name='MOUNTING TYPE')),
                ('COOLING', models.CharField(blank=True, choices=[('0', 'Oil'), ('1', 'Dry')], max_length=2, null=True, verbose_name='COOLING')),
                ('WINDING', models.CharField(blank=True, choices=[('0', 'Al - Al'), ('1', 'Cu - CU')], max_length=2, null=True, verbose_name='WINDING')),
                ('INSULAT', models.CharField(blank=True, choices=[('0', 'A'), ('1', 'E'), ('2', 'H')], max_length=2, null=True, verbose_name='INSULAT CLASS')),
                ('CONNECTION', models.CharField(blank=True, choices=[('0', 'WEY'), ('1', 'DELTA')], max_length=2, null=True, verbose_name='CONNECTION')),
                ('STANDARD', models.CharField(blank=True, choices=[('0', 'NMX-116'), ('1', 'IEC 61558')], max_length=2, null=True, verbose_name='STANDARD')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Cantidad')),
                ('unitCost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo unitario')),
            ],
            options={
                'verbose_name': 'Trafos',
                'verbose_name_plural': 'Trafos',
            },
        ),
        migrations.CreateModel(
            name='TrafoTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nameTask', models.CharField(max_length=100, verbose_name='Tarea')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ubicacion')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha finalizacion')),
                ('progress', models.IntegerField(default=0, verbose_name='Progreso')),
                ('is_milestone', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Tarea orden',
                'verbose_name_plural': 'Tareas ordenes',
            },
        ),
        migrations.CreateModel(
            name='TrafoTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('idOrder', models.IntegerField(blank=True, null=True, verbose_name='Id Orders')),
                ('dateChange', models.DateTimeField(verbose_name='Fecha')),
                ('orderState', models.CharField(choices=[('0', 'Creado'), ('1', 'Fabricado'), ('2', 'Enviado'), ('3', 'Completado'), ('4', 'Cancelado')], max_length=1, verbose_name='Estado de orden')),
            ],
            options={
                'verbose_name': 'pedido seguimiento ',
                'verbose_name_plural': 'pedidos seguimientos ',
            },
        ),
    ]
