# Generated by Django 5.0.6 on 2024-07-10 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actividades', '0001_initial'),
        ('clientes', '0001_initial'),
        ('personal', '0001_initial'),
        ('producto', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedtasks',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commissions',
            name='workers',
            field=models.ManyToManyField(to='personal.workers'),
        ),
        migrations.AddField(
            model_name='dailytasks',
            name='assignedTasks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actividades.assignedtasks'),
        ),
        migrations.AddField(
            model_name='dailytasks',
            name='commissions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actividades.commissions'),
        ),
        migrations.AddField(
            model_name='dailytasks',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='projects',
            name='workers',
            field=models.ManyToManyField(to='personal.workers'),
        ),
        migrations.AddField(
            model_name='dailytasks',
            name='projects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actividades.projects'),
        ),
        migrations.AddField(
            model_name='trafoorder',
            name='idAttendant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personal.workers'),
        ),
        migrations.AddField(
            model_name='trafoorder',
            name='idClient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='trafoorder',
            name='idTransformer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='producto.transformer'),
        ),
        migrations.AddField(
            model_name='dailytasks',
            name='trafoOrder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actividades.trafoorder'),
        ),
    ]
