# Generated by Django 5.0.6 on 2025-05-17 01:03

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailytasks',
            name='is_overTime',
        ),
        migrations.AddField(
            model_name='dailytasks',
            name='overTime',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Horas extra'),
        ),
        migrations.AddField(
            model_name='dailytasks',
            name='type',
            field=models.CharField(blank=True, choices=[('0', 'Jornada diaria'), ('1', 'Horas extra'), ('2', 'Feriado'), ('0', 'Devolución'), ('3', 'Otro')], default='0', max_length=1, null=True, verbose_name='Tipo de jornada'),
        ),
        migrations.AlterField(
            model_name='dailytasks',
            name='activity',
            field=models.TextField(blank=True, null=True, verbose_name='Actividad'),
        ),
        migrations.CreateModel(
            name='WorkPermits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date', models.DateField(verbose_name='Fecha solicitada')),
                ('type', models.CharField(blank=True, choices=[('0', 'Permiso particular'), ('1', 'Descanso médico'), ('2', 'Vacaciones'), ('3', 'Maternidad'), ('4', 'Otro')], default='0', max_length=1, null=True, verbose_name='Tipo de permiso')),
                ('sleepTime', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Horas')),
                ('startTime', models.DateField(blank=True, null=True, verbose_name='Hora de inicio')),
                ('endTime', models.DateField(blank=True, null=True, verbose_name='Hora de término')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Tarea diaria',
                'verbose_name_plural': 'Tareas diarias',
            },
        ),
    ]
