# Generated by Django 5.0.6 on 2025-05-17 01:03

import django.db.models.manager
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0003_remove_dailytasks_is_overtime_dailytasks_overtime_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkPermits',
            new_name='RestDays',
        ),
        migrations.AlterModelManagers(
            name='restdays',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
