# Generated by Django 5.0.6 on 2025-05-17 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0004_rename_workpermits_restdays_alter_restdays_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='restdays',
            name='motive',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo'),
        ),
        migrations.AddField(
            model_name='restdays',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='descansos_pdfs/'),
        ),
    ]
