# Generated by Django 5.0.6 on 2025-05-17 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0005_restdays_motive_restdays_pdf_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restdays',
            options={'verbose_name': 'Descanso', 'verbose_name_plural': 'Descansos'},
        ),
        migrations.RenameField(
            model_name='restdays',
            old_name='endTime',
            new_name='endDate',
        ),
        migrations.RenameField(
            model_name='restdays',
            old_name='startTime',
            new_name='startDate',
        ),
    ]
