# Generated by Django 5.0.6 on 2024-07-19 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0005_trafoquote_trafos'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafoquote',
            name='userClient',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cliente'),
        ),
    ]
