# Generated by Django 5.0.6 on 2024-07-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0006_trafoquote_userclient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafoquote',
            name='idQuote',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='RFQ Number'),
        ),
    ]
