# Generated by Django 5.0.6 on 2025-05-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0006_alter_restdays_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restdays',
            name='daysCompensated',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Dias compensados'),
        ),
        migrations.AddField(
            model_name='restdays',
            name='hoursCompensated',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Horas compensados'),
        ),
        migrations.AddField(
            model_name='restdays',
            name='isCompensated',
            field=models.BooleanField(default=False, verbose_name='Compensación necesaria'),
        ),
    ]
