# Generated by Django 5.0.6 on 2025-05-17 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0007_restdays_dayscompensated_restdays_hourscompensated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytasks',
            name='idRestDay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actividades.restdays'),
        ),
    ]
