# Generated by Django 5.0.6 on 2024-07-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0007_alter_trafoquote_idquote'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafoquote',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='trafoquote',
            name='trakingStatus',
            field=models.CharField(blank=True, choices=[('0', 'recibido'), ('1', 'insumos'), ('2', 'fabricado'), ('3', 'transporte interno'), ('4', 'transporte maritimo'), ('5', 'arribado'), ('6', 'entregado')], default='0', max_length=1, null=True, verbose_name='Seguimiento'),
        ),
        migrations.AlterField(
            model_name='trafoquote',
            name='poStatus',
            field=models.CharField(blank=True, choices=[('0', 'no PO'), ('1', 'PO')], default='0', max_length=1, null=True, verbose_name='Estado PO'),
        ),
        migrations.AlterField(
            model_name='trafoquote',
            name='quoteStatus',
            field=models.CharField(blank=True, choices=[('0', 'recibido'), ('1', 'revision'), ('2', 'respondido'), ('3', 'cancelado'), ('4', 'espera')], default='0', max_length=1, null=True, verbose_name='Estado cotizacion'),
        ),
    ]
