# Generated by Django 5.0.6 on 2024-07-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0008_trafoquote_description_trafoquote_trakingstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafoquote',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de entrega'),
        ),
    ]
