# Generated by Django 5.0.6 on 2025-05-17 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0009_alter_restdays_managers_restdays_dt1_restdays_dt2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restdays',
            old_name='sleepTime',
            new_name='hours',
        ),
        migrations.AlterField(
            model_name='restdays',
            name='endDate',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de término'),
        ),
        migrations.AlterField(
            model_name='restdays',
            name='startDate',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de inicio'),
        ),
    ]
