# Generated by Django 5.0.6 on 2025-05-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0010_rename_sleeptime_restdays_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restdays',
            name='isCompensated',
            field=models.BooleanField(default=True, verbose_name='Compensación necesaria'),
        ),
    ]
