# Generated by Django 5.0.6 on 2024-07-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0010_alter_trafoquote_idclient_alter_trafoquote_idquote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trafoquote',
            name='quoteStatus',
        ),
        migrations.AddField(
            model_name='trafoquote',
            name='dt1',
            field=models.DateTimeField(null=True, verbose_name='dt1'),
        ),
        migrations.AddField(
            model_name='trafoquote',
            name='dt2',
            field=models.DateTimeField(null=True, verbose_name='dt2'),
        ),
        migrations.AddField(
            model_name='trafoquote',
            name='dt3',
            field=models.DateTimeField(null=True, verbose_name='dt3'),
        ),
        migrations.AddField(
            model_name='trafoquote',
            name='dt4',
            field=models.DateTimeField(null=True, verbose_name='dt4'),
        ),
        migrations.AddField(
            model_name='trafoquote',
            name='q1',
            field=models.CharField(choices=[('0', 'creado'), ('1', 'espera'), ('2', 'completado'), ('3', 'observado'), ('4', 'cancelado')], default='0', max_length=1, verbose_name='Recibido'),
        ),
        migrations.AddField(
            model_name='trafoquote',
            name='q2',
            field=models.CharField(choices=[('0', 'creado'), ('1', 'espera'), ('2', 'completado'), ('3', 'observado'), ('4', 'cancelado')], default='0', max_length=1, verbose_name='Cotizacion'),
        ),
        migrations.AddField(
            model_name='trafoquote',
            name='q3',
            field=models.CharField(choices=[('0', 'creado'), ('1', 'espera'), ('2', 'completado'), ('3', 'observado'), ('4', 'cancelado')], default='0', max_length=1, verbose_name='Respuesta de cliente'),
        ),
        migrations.AddField(
            model_name='trafoquote',
            name='q4',
            field=models.CharField(choices=[('0', 'creado'), ('1', 'espera'), ('2', 'completado'), ('3', 'observado'), ('4', 'cancelado')], default='0', max_length=1, verbose_name='Atendido'),
        ),
    ]
