# Generated by Django 5.0.6 on 2025-05-18 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0011_alter_restdays_iscompensated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restdays',
            name='date',
        ),
    ]
