# Generated by Django 5.0.6 on 2024-07-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0012_alter_trafoquote_q1_alter_trafoquote_q2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafoquote',
            name='dt1',
            field=models.DateTimeField(blank=True, null=True, verbose_name='dt1'),
        ),
        migrations.AlterField(
            model_name='trafoquote',
            name='dt2',
            field=models.DateTimeField(blank=True, null=True, verbose_name='dt2'),
        ),
        migrations.AlterField(
            model_name='trafoquote',
            name='dt3',
            field=models.DateTimeField(blank=True, null=True, verbose_name='dt3'),
        ),
        migrations.AlterField(
            model_name='trafoquote',
            name='dt4',
            field=models.DateTimeField(blank=True, null=True, verbose_name='dt4'),
        ),
    ]
