# Generated by Django 5.0.6 on 2025-05-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0012_remove_restdays_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='restdays',
            name='days',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Dias'),
        ),
    ]
