# Generated by Django 5.0.6 on 2024-07-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0013_alter_trafoquote_dt1_alter_trafoquote_dt2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trafos',
            name='quantityApproved',
        ),
        migrations.RemoveField(
            model_name='trafos',
            name='unitCostApproved',
        ),
        migrations.AddField(
            model_name='trafos',
            name='condition',
            field=models.CharField(blank=True, choices=[('0', 'recibida'), ('1', 'enviada'), ('2', 'aprobada')], max_length=1, null=True, verbose_name='Condicion'),
        ),
        migrations.AlterField(
            model_name='trafoquote',
            name='q1',
            field=models.CharField(choices=[('4', 'creado'), ('0', 'espera'), ('1', 'completado'), ('3', 'observado'), ('2', 'cancelado')], default='0', max_length=1, verbose_name='Recibido'),
        ),
        migrations.AlterField(
            model_name='trafoquote',
            name='q2',
            field=models.CharField(choices=[('4', 'creado'), ('0', 'espera'), ('1', 'completado'), ('3', 'observado'), ('2', 'cancelado')], default='4', max_length=1, verbose_name='Cotizacion'),
        ),
        migrations.AlterField(
            model_name='trafoquote',
            name='q3',
            field=models.CharField(choices=[('4', 'creado'), ('0', 'espera'), ('1', 'completado'), ('3', 'observado'), ('2', 'cancelado')], default='4', max_length=1, verbose_name='Respuesta de cliente'),
        ),
        migrations.AlterField(
            model_name='trafoquote',
            name='q4',
            field=models.CharField(choices=[('4', 'creado'), ('0', 'espera'), ('1', 'completado'), ('3', 'observado'), ('2', 'cancelado')], default='4', max_length=1, verbose_name='Atendido'),
        ),
    ]
