# Generated by Django 5.0.6 on 2025-05-18 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0013_restdays_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytasks',
            name='type',
            field=models.CharField(blank=True, choices=[('0', 'Jornada diaria'), ('1', 'Horas extra'), ('2', 'Feriado'), ('4', 'COmpensación'), ('3', 'Otro')], default='0', max_length=1, null=True, verbose_name='Tipo de jornada'),
        ),
    ]
