# Generated by Django 5.0.6 on 2024-07-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0014_remove_trafos_quantityapproved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafos',
            name='condition',
            field=models.CharField(blank=True, choices=[('0', 'recibida'), ('1', 'enviada'), ('2', 'aprobada')], default='0', max_length=1, null=True, verbose_name='Condicion'),
        ),
        migrations.AlterField(
            model_name='trafos',
            name='unitCost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo unitario'),
        ),
    ]
