# Generated by Django 5.0.6 on 2025-05-18 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0014_alter_dailytasks_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytasks',
            name='idRestDay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rest_day', to='actividades.restdays'),
        ),
        migrations.AlterField(
            model_name='dailytasks',
            name='type',
            field=models.CharField(blank=True, choices=[('0', 'Jornada diaria'), ('1', 'Horas extra'), ('2', 'Feriado'), ('4', 'Compensación'), ('3', 'Otro')], default='0', max_length=1, null=True, verbose_name='Tipo de jornada'),
        ),
    ]
