# Generated by Django 5.0.6 on 2025-05-18 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0015_alter_dailytasks_idrestday_alter_dailytasks_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailytasks',
            name='idRestDay',
        ),
        migrations.AddField(
            model_name='dailytasks',
            name='rest_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compensations', to='actividades.restdays'),
        ),
    ]
