# Generated by Django 5.0.6 on 2024-07-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0015_alter_trafos_condition_alter_trafos_unitcost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trafos',
            name='condition',
        ),
        migrations.AddField(
            model_name='trafoquote',
            name='condition',
            field=models.CharField(blank=True, choices=[('0', 'recibida'), ('1', 'enviada'), ('2', 'aprobada')], default='0', max_length=1, null=True, verbose_name='Condicion'),
        ),
    ]
