# Generated by Django 5.0.6 on 2024-07-23 13:22

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0016_remove_trafos_condition_trafoquote_condition'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('typeMail', models.CharField(blank=True, choices=[('0', 'inicial'), ('1', 'cotizacion'), ('2', 'aprobación')], default='0', max_length=1, null=True, verbose_name='Tipo')),
                ('sendFlag', models.BooleanField(default=False, verbose_name='Enviado')),
                ('subject', models.CharField(max_length=100, verbose_name='Subject')),
                ('body', models.TextField(verbose_name='Body')),
                ('sender', models.CharField(default='jh', max_length=100, verbose_name='Emisor')),
                ('recipients', models.CharField(max_length=100, verbose_name='Receptores')),
                ('idQuote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actividades.trafoquote')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
