# Generated by Django 5.0.6 on 2024-08-17 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0017_emailsent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytasks',
            name='type',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Horas extra'),
        ),
    ]
