# Generated by Django 5.0.6 on 2025-05-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0017_dailytasks_idtin_alter_dailytasks_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailytasks',
            name='endTime',
        ),
        migrations.RemoveField(
            model_name='dailytasks',
            name='startTime',
        ),
        migrations.AddField(
            model_name='dailytasks',
            name='hours',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Horas'),
        ),
    ]
