# Generated by Django 5.0.6 on 2024-09-16 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0021_remove_trafoorder_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trafotask',
            name='trafoQuote',
        ),
        migrations.AddField(
            model_name='trafotask',
            name='idTrafoQuote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actividades.trafoquote'),
        ),
    ]
