# Generated by Django 5.0.6 on 2024-09-16 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0022_remove_trafotask_trafoquote_trafotask_idtrafoquote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafotask',
            name='idTrafoQuote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.trafoquote'),
        ),
    ]
