# Generated by Django 5.0.6 on 2025-03-18 17:48

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerTracking',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', models.CharField(blank=True, choices=[('0', 'Start as per the PO'), ('1', 'Sea Travel'), ('2', 'Land Travel'), ('3', 'Delivery in Greenville as per PO'), ('4', 'Perdido')], default='0', max_length=2, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trackingNumber', models.CharField(blank=True, max_length=20, null=True, verbose_name='Seguimiento')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='conciliaciones_pdfs/')),
            ],
            options={
                'verbose_name': 'Numero de seguimiento',
                'verbose_name_plural': 'Numeros de seguimientos',
            },
        ),
    ]
