# Generated by Django 5.0.6 on 2025-03-18 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containertracking',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='doc_pdfs/'),
        ),
        migrations.AlterField(
            model_name='containertracking',
            name='trackingNumber',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Seguimiento'),
        ),
    ]
