# Generated by Django 5.0.6 on 2024-12-19 10:54

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('accountName', models.CharField(max_length=50, verbose_name='Nombre de cuenta')),
                ('nickName', models.CharField(blank=True, max_length=10, null=True, verbose_name='Nombre cortp')),
                ('accountNumber', models.CharField(max_length=30, unique=True, verbose_name='Numero de cuenta')),
                ('bankName', models.CharField(max_length=50, verbose_name='Nombre de banco')),
                ('accountBalance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto en sistema')),
                ('lastUpdateCRM', models.DateTimeField(verbose_name='Actualización CRM')),
                ('currency', models.CharField(blank=True, choices=[('0', 'S/.'), ('1', '$')], max_length=1, verbose_name='Tipo de moneda')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('cajaChica', models.BooleanField(blank=True, default=False, null=True, verbose_name='Caja Chica')),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas bancarias',
            },
        ),
        migrations.CreateModel(
            name='Tin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('tin', models.CharField(max_length=50, verbose_name='RUC')),
                ('tinName', models.CharField(max_length=50, verbose_name='Razón Social')),
            ],
            options={
                'verbose_name': 'Ruc',
                'verbose_name_plural': 'Rucs',
            },
        ),
        migrations.CreateModel(
            name='ManualAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('realBalance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto en cuenta')),
                ('idAcount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Account', to='cuentas.account')),
            ],
            options={
                'verbose_name': 'Cuenta Manual',
                'verbose_name_plural': 'Cuentas bancarias Manuales',
            },
        ),
        migrations.AddField(
            model_name='account',
            name='idTin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuentas.tin'),
        ),
    ]
