# Generated by Django 5.0.6 on 2024-07-18 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(blank=True, choices=[('0', 'S/.'), ('1', '$')], max_length=1, verbose_name='Tipo de moneda'),
        ),
    ]
