# Generated by Django 5.0.6 on 2024-12-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='nickName',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Nombre corto'),
        ),
    ]
