# Generated by Django 5.0.6 on 2024-08-15 23:02

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_alter_account_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('tin', models.CharField(max_length=50, verbose_name='RUC')),
                ('tinName', models.CharField(max_length=50, verbose_name='Razón Social')),
            ],
            options={
                'verbose_name': 'Ruc',
                'verbose_name_plural': 'Rucs',
            },
        ),
        migrations.AddField(
            model_name='account',
            name='idTin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuentas.tin'),
        ),
    ]
