# Generated by Django 5.0.6 on 2025-05-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_alter_account_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(blank=True, choices=[('0', 'PEN'), ('1', 'USD')], max_length=1, verbose_name='Tipo de moneda'),
        ),
    ]
