# Generated by Django 5.0.6 on 2025-08-25 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_alter_account_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='accountBalance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto inicial'),
        ),
        migrations.AlterField(
            model_name='account',
            name='lastUpdateCRM',
            field=models.DateTimeField(verbose_name='Fecha inicial'),
        ),
    ]
