# Generated by Django 5.0.6 on 2025-08-25 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0004_alter_account_accountbalance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='lastUpdateCRM',
            new_name='initalDate',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='accountBalance',
            new_name='initialAccount',
        ),
    ]
