# Generated by Django 5.0.6 on 2026-02-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0005_rename_lastupdatecrm_account_initaldate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tin',
            name='company_type',
            field=models.CharField(blank=True, choices=[('0', 'Holding'), ('1', 'Subsidiaria')], max_length=1, null=True),
        ),
    ]
