# Generated by Django 5.0.6 on 2026-03-17 09:45

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0006_tin_company_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['idTin__tinName', 'accountName'], 'verbose_name': 'Cuenta bancaria', 'verbose_name_plural': 'Cuentas bancarias'},
        ),
        migrations.AlterField(
            model_name='account',
            name='accountNumber',
            field=models.CharField(max_length=30, unique=True, verbose_name='Número de cuenta'),
        ),
        migrations.AlterField(
            model_name='account',
            name='bankName',
            field=models.CharField(max_length=50, verbose_name='Banco'),
        ),
        migrations.AlterField(
            model_name='account',
            name='cajaChica',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Caja chica'),
        ),
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(blank=True, choices=[('0', 'PEN'), ('1', 'USD')], max_length=1, verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='account',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='account',
            name='idTin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='cuentas.tin', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='account',
            name='initialAccount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Saldo inicial'),
        ),
        migrations.AlterField(
            model_name='account',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.CreateModel(
            name='Account0',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('accountName', models.CharField(max_length=50, verbose_name='Nombre de cuenta')),
                ('nickName', models.CharField(blank=True, max_length=10, null=True, verbose_name='Nombre corto')),
                ('accountNumber', models.CharField(max_length=30, unique=True, verbose_name='Numero de cuenta')),
                ('bankName', models.CharField(max_length=50, verbose_name='Nombre de banco')),
                ('initialAccount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto inicial')),
                ('initalDate', models.DateTimeField(verbose_name='Fecha inicial')),
                ('currency', models.CharField(blank=True, choices=[('0', 'PEN'), ('1', 'USD')], max_length=1, verbose_name='Tipo de moneda')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('cajaChica', models.BooleanField(blank=True, default=False, null=True, verbose_name='Caja Chica')),
                ('idTin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuentas.tin')),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas bancarias',
            },
        ),
    ]
