# Generated by Django 5.0.6 on 2026-03-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0007_alter_account_options_alter_account_accountnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(blank=True, choices=[('0', 'PEN'), ('1', 'USD'), ('2', 'EUR')], max_length=1, verbose_name='Moneda'),
        ),
        migrations.DeleteModel(
            name='Account0',
        ),
    ]
