# Generated by Django 5.0.6 on 2026-03-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0008_alter_account_currency_delete_account0'),
    ]

    operations = [
        migrations.AddField(
            model_name='tin',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo corporativo'),
        ),
    ]
