# Generated by Django 5.0.6 on 2025-10-09 13:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0005_rename_lastupdatecrm_account_initaldate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feriados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('Nombre', models.CharField(blank=True, max_length=25, verbose_name='Nombre feriado')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('jefe_departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departamentos_jefe', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('fecha_contratacion', models.DateField(blank=True, verbose_name='Fecha de ingreso')),
                ('tipo_contrato', models.CharField(blank=True, choices=[('0', 'Contrato Fijo'), ('1', 'Contrato Temporal'), ('2', 'Prácticas'), ('3', 'Formación')], default='0', max_length=1, verbose_name='Tipo de contrato')),
                ('moneda', models.CharField(choices=[('0', 'PEN'), ('1', 'USD'), ('2', 'EUR')], default='0', max_length=1, verbose_name='Moneda')),
                ('salario_base', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Salario')),
                ('telefono', models.CharField(blank=True, max_length=15, verbose_name='Telefono')),
                ('direccion', models.TextField(blank=True, verbose_name='Direccion')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='F. Nacimiento')),
                ('activo', models.BooleanField(default=True, verbose_name='Esta activo?')),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RRHH.departamento')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empleado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('tipo', models.CharField(choices=[('0', 'Boleta de Pago'), ('1', 'Contrato'), ('2', 'Curriculum Vitae'), ('3', 'Identificación'), ('4', 'Certificación'), ('5', 'Otro')], max_length=20, verbose_name='Tipo de documento')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de documento')),
                ('archivo', models.FileField(upload_to='documentos/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'jpg', 'png'])])),
                ('fecha_documento', models.DateField(verbose_name='Fecha de emisión')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción del documento')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RRHH.empleado')),
            ],
            options={
                'ordering': ['-fecha_documento'],
            },
        ),
        migrations.CreateModel(
            name='ContactoEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(blank=True, max_length=150, verbose_name='APellidos y Nombres')),
                ('parentesco', models.CharField(blank=True, choices=[('0', 'Hermano/a'), ('1', 'Padre o madre'), ('2', 'Cónyuge'), ('3', 'otro')], max_length=1, verbose_name='Parentesco')),
                ('telefono', models.CharField(blank=True, max_length=15, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('principal', models.BooleanField(blank=True, default=False, verbose_name='Es principal?')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos_emergencia', to='RRHH.empleado')),
            ],
            options={
                'verbose_name': 'Contacto de emergencia',
                'verbose_name_plural': 'Contactos de Emergencia',
            },
        ),
        migrations.CreateModel(
            name='ActividadDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('horas_trabajadas', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Horas')),
                ('proyecto', models.CharField(blank=True, max_length=100, verbose_name='proyecto')),
                ('completada', models.BooleanField(default=False)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RRHH.empleado')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombreLocal', models.CharField(max_length=20, verbose_name='Nombre Local')),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Descripción')),
                ('idCompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas.tin')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('tipo', models.CharField(choices=[('0', 'Vacaciones'), ('1', 'Enfermedad'), ('2', 'Personal'), ('3', 'Maternidad'), ('4', 'Paternidad')], default='2', max_length=20, verbose_name='Tipo de permiso')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de finalización')),
                ('horas', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Horas')),
                ('estado', models.CharField(choices=[('0', 'Pendiente'), ('1', 'Aprobado'), ('2', 'Rechazado')], default='PENDIENTE', max_length=10, verbose_name='Estado')),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aprobación')),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RRHH.empleado')),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos ',
            },
        ),
        migrations.CreateModel(
            name='RegistroAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora_inicio', models.TimeField(blank=True, null=True, verbose_name='Hora inicio')),
                ('hora_final', models.TimeField(blank=True, null=True, verbose_name='Hora final')),
                ('ubicacion', models.CharField(blank=True, max_length=1, null=True, verbose_name='Local')),
                ('jornada_horaria', models.CharField(blank=True, choices=[('0', 'Reg 9:00 - 18:00'), ('1', 'HE1 18:01 - 21:00'), ('2', 'HE2 21:01 - 23:59 y 00:00 - 06:00')], default='0', max_length=1, verbose_name='Tipo de Jornada Horaria')),
                ('jornada_diaria', models.CharField(blank=True, choices=[('0', 'Día Laborable'), ('1', 'Feriado'), ('2', 'Fin de semana')], default='0', max_length=1, verbose_name='Tipo de Jornada Diaria')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('horas', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=4, null=True, verbose_name='Horas laboradas')),
                ('estado', models.CharField(choices=[('0', 'Pendiente'), ('1', 'Aprobado'), ('2', 'Rechazado'), ('3', 'Procesado')], default='0', max_length=1)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asistencia_aprobacion', to=settings.AUTH_USER_MODEL)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RRHH.empleado')),
                ('idLocal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RRHH.local')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Registro de asistencia',
                'ordering': ['-fecha', '-hora_inicio'],
                'indexes': [models.Index(fields=['empleado', 'fecha'], name='RRHH_regist_emplead_c4b7ce_idx'), models.Index(fields=['fecha', 'jornada_horaria'], name='RRHH_regist_fecha_38e7f4_idx'), models.Index(fields=['fecha', 'jornada_diaria'], name='RRHH_regist_fecha_f52075_idx')],
                'unique_together': {('empleado', 'fecha', 'hora_inicio', 'jornada_horaria')},
            },
        ),
    ]
