# Generated by Django 5.0.6 on 2025-10-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RRHH', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroasistencia',
            name='ubicacion',
            field=models.CharField(blank=True, default='0', max_length=1, null=True, verbose_name='Local'),
        ),
    ]
