# Generated by Django 5.0.6 on 2025-09-27 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RRHH', '0002_feriados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroasistencia',
            name='jornada',
            field=models.CharField(blank=True, choices=[('0', 'Reg 9:00 - 18:00'), ('1', 'HE1 18:01 - 21:59'), ('2', 'HE2 22:00 - 05:59'), ('3', 'Feriado'), ('4', 'Refrigerio'), ('5', 'Otro')], default='0', max_length=1, verbose_name='Jornada'),
        ),
    ]
