# Generated by Django 5.0.6 on 2025-10-15 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RRHH', '0002_alter_registroasistencia_ubicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroasistencia',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registro_asistencia', to='RRHH.empleado'),
        ),
    ]
