# Generated by Django 5.0.6 on 2025-10-28 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RRHH', '0003_alter_registroasistencia_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='idArea',
            field=models.CharField(blank=True, choices=[('0', 'Administrador'), ('1', 'Comercial'), ('2', 'Finanzas'), ('3', 'Producción'), ('4', 'Gerencia'), ('5', 'Logística'), ('6', 'Recursos humanos'), ('7', 'Consultor externo'), ('8', 'CEO general'), ('9', 'TI')], max_length=1, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
