# Generated by Django 5.0.6 on 2025-10-30 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RRHH', '0004_departamento_idarea_alter_departamento_nombre'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registroasistencia',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='es_registro_dividido',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='registroasistencia',
            name='jornada_horaria',
            field=models.CharField(blank=True, choices=[('0', 'Reg 9:00 - 18:00'), ('1', 'HE1 18:01 - 22:00'), ('2', 'HE2 22:01 - 23:59 y 00:00 - 06:00')], default='0', max_length=1, verbose_name='Tipo de Jornada Horaria'),
        ),
    ]
