# Generated by Django 5.0.6 on 2025-10-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RRHH', '0005_alter_registroasistencia_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroasistencia',
            name='es_registro_dividido',
        ),
        migrations.AlterField(
            model_name='registroasistencia',
            name='jornada_horaria',
            field=models.CharField(blank=True, choices=[('0', 'Reg 9:00 - 18:00'), ('1', 'HE1 18:01 - 21:00'), ('2', 'HE2 21:01 - 23:59 y 00:00 - 06:00')], default='0', max_length=1, verbose_name='Tipo de Jornada Horaria'),
        ),
    ]
