# Generated by Django 5.0.6 on 2026-02-23 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RRHH', '0007_alter_registroasistencia_jornada_horaria'),
        ('cuentas', '0005_rename_lastupdatecrm_account_initaldate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuentas.tin'),
        ),
    ]
