# Generated by Django 5.0.6 on 2025-09-22 11:18

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stakeholders', '0007_alter_supplier_numberidsupplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trafos',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('KVA', models.CharField(blank=True, choices=[('0', '15'), ('1', '30'), ('2', '75'), ('3', '100'), ('4', '167'), ('5', '200'), ('6', '250'), ('7', '400'), ('8', '500'), ('9', '600'), ('10', '750'), ('11', '1000'), ('12', '1500'), ('13', '2000')], max_length=2, null=True, verbose_name='kVA CAPACITY')),
                ('HVTAP', models.CharField(blank=True, choices=[('0', 'K-Tap - HV'), ('1', 'Fix HV')], max_length=2, null=True, verbose_name='HV TAP')),
                ('KTapHV', models.CharField(blank=True, choices=[('0', '12700/7200'), ('1', '24940/14400')], max_length=2, null=True, verbose_name='K Tap HV')),
                ('FIXHV', models.CharField(blank=True, choices=[('0', '7200'), ('1', '12470'), ('2', '22900')], max_length=2, null=True, verbose_name='FIX HV')),
                ('LV', models.CharField(blank=True, choices=[('0', '120/240'), ('1', '277/480')], max_length=2, null=True, verbose_name='LV')),
                ('HZ', models.CharField(blank=True, choices=[('0', '50'), ('1', '60')], max_length=2, null=True, verbose_name='HZ')),
                ('TYPE', models.CharField(blank=True, choices=[('0', 'Mono-phasic'), ('1', 'Three-phasic')], max_length=2, null=True, verbose_name='TYPE')),
                ('MOUNTING', models.CharField(blank=True, choices=[('0', 'Pole'), ('1', 'Standard'), ('2', 'Feed Through Pad')], max_length=2, null=True, verbose_name='MOUNTING TYPE')),
                ('COOLING', models.CharField(blank=True, choices=[('0', 'Oil'), ('1', 'Dry')], max_length=2, null=True, verbose_name='COOLING')),
                ('WINDING', models.CharField(blank=True, choices=[('0', 'Al - Al'), ('1', 'Cu - CU')], max_length=2, null=True, verbose_name='WINDING')),
                ('INSULAT', models.CharField(blank=True, choices=[('0', 'A'), ('1', 'E'), ('2', 'H')], max_length=2, null=True, verbose_name='INSULAT CLASS')),
                ('CONNECTION', models.CharField(blank=True, choices=[('0', 'WEY'), ('1', 'DELTA')], max_length=2, null=True, verbose_name='CONNECTION')),
                ('STANDARD', models.CharField(blank=True, choices=[('0', 'NMX-116'), ('1', 'IEC 61558')], max_length=2, null=True, verbose_name='STANDARD')),
                ('idSupplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prod_trafo_supplier', to='stakeholders.supplier')),
            ],
            options={
                'verbose_name': 'Trafos',
                'verbose_name_plural': 'Trafos',
            },
        ),
    ]
