# Generated by Django 5.0.6 on 2025-09-22 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCTION', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trafos',
            options={'verbose_name': 'Catalogo de transformadores', 'verbose_name_plural': 'Transformadores'},
        ),
        migrations.AddField(
            model_name='trafos',
            name='idUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
