# Generated by Django 5.0.6 on 2025-11-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCTION', '0003_remove_trafos_fixhv_remove_trafos_hvtap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafos',
            name='HV',
            field=models.CharField(blank=True, choices=[('0', '4160'), ('1', '7200'), ('2', '8320'), ('3', '12470'), ('4', '13200'), ('5', '13800'), ('6', '14400'), ('7', '21600'), ('8', '22860'), ('9', '23960'), ('10', '24940'), ('11', '34500')], max_length=2, null=True, verbose_name='HV'),
        ),
    ]
