# Generated by Django 5.0.6 on 2026-03-13 08:30

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0006_tin_company_type'),
        ('sales', '0039_alter_quotes_ponumber'),
        ('stakeholders', '0007_alter_supplier_numberidsupplier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('doc_type', models.CharField(choices=[('FAC', 'Factura'), ('BOL', 'Boleta de Venta'), ('RHE', 'Recibo por Honorarios'), ('NCR', 'Nota de Crédito'), ('NDB', 'Nota de Débito'), ('DUA', 'DUA (Importación)'), ('GRE', 'Guía de Remisión'), ('LIQ', 'Liquidación'), ('PLA', 'Planilla'), ('IMP', 'Impuesto / Tributo'), ('PER', 'Percepción'), ('OTR', 'Otro')], default='FAC', max_length=3, verbose_name='Tipo de comprobante')),
                ('doc_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de comprobante')),
                ('direction', models.CharField(choices=[('IN', 'Ingreso  (cobro al cliente)'), ('OUT', 'Egreso   (pago al proveedor/subsidiaria)'), ('INT', 'Interno  (holding ↔ subsidiaria)')], default='OUT', max_length=3, verbose_name='Dirección del flujo')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Fecha de emisión')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento')),
                ('declare_month', models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], null=True, verbose_name='Mes de declaración')),
                ('declare_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Año de declaración')),
                ('currency', models.CharField(choices=[('PEN', 'Soles (PEN)'), ('USD', 'Dólares (USD)'), ('EUR', 'Euros (EUR)')], default='USD', max_length=3, verbose_name='Moneda')),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1, help_text='Tasa respecto al USD en la fecha de emisión', max_digits=10, verbose_name='Tipo de cambio')),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Monto bruto')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Impuesto (IGV/IVA)')),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Monto neto')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Monto pagado')),
                ('pending_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Monto pendiente')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PARTIAL', 'Pago parcial'), ('PAID', 'Pagado'), ('CANCELLED', 'Anulado'), ('REVERSED', 'Revertido')], default='PENDING', max_length=10, verbose_name='Estado')),
                ('annotation', models.CharField(blank=True, choices=[('ADVANCE', 'Anticipo'), ('BALANCE', 'Saldo / Pago final'), ('FULL', 'Total')], max_length=10, null=True, verbose_name='Anotación')),
                ('has_detraction', models.BooleanField(default=False, verbose_name='¿Tiene detracción?')),
                ('detraction_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Monto detracción')),
                ('has_retention', models.BooleanField(default=False, verbose_name='¿Tiene retención?')),
                ('retention_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Monto retención')),
                ('account_category', models.CharField(blank=True, choices=[('ADUANAS', 'Agente de aduana'), ('CAJA_CH', 'Caja chica'), ('CAJA_GEN', 'Caja general'), ('CAJA_VTA', 'Caja general ventas'), ('RHE_GEN', 'RHE general'), ('ADICIONAL', 'Adicional'), ('PERSONAL', 'Personal'), ('PLANILLA', 'Planilla'), ('RENTA', 'Renta')], max_length=10, null=True, verbose_name='Categoría contable')),
                ('cost_center', models.CharField(blank=True, max_length=50, null=True, verbose_name='Centro de costo')),
                ('short_description', models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripción corta')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción detallada')),
                ('xml_file', models.FileField(blank=True, null=True, upload_to='payment_docs/xml/', verbose_name='XML')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='payment_docs/pdf/', verbose_name='PDF')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_docs', to='stakeholders.client', verbose_name='Cliente externo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_docs_created', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_docs', to='stakeholders.supplier', verbose_name='Proveedor externo')),
                ('tin_issuer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docs_issued', to='cuentas.tin', verbose_name='Empresa emisora (TIN)')),
                ('tin_receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docs_received', to='cuentas.tin', verbose_name='Empresa receptora (TIN)')),
            ],
            options={
                'verbose_name': 'Comprobante de pago',
                'verbose_name_plural': 'Comprobantes de pago',
                'ordering': ['-issue_date', '-created'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('allocated_amount', models.DecimalField(decimal_places=2, default=0, help_text='Fracción del comprobante que corresponde a este ítem', max_digits=14, verbose_name='Monto asignado')),
                ('notes', models.CharField(blank=True, max_length=200, null=True, verbose_name='Notas')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_allocations', to='sales.items', verbose_name='Ítem')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='FINANTIAL.paymentdocument', verbose_name='Comprobante')),
            ],
            options={
                'verbose_name': 'Asignación de comprobante',
                'verbose_name_plural': 'Asignaciones de comprobante',
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('reference', models.CharField(blank=True, max_length=80, null=True, verbose_name='Referencia bancaria / Número')),
                ('pay_method', models.CharField(choices=[('TRANSFER', 'Transferencia bancaria'), ('CHECK', 'Cheque'), ('CASH', 'Efectivo'), ('CARD', 'Tarjeta'), ('OTHER', 'Otro')], default='TRANSFER', max_length=10, verbose_name='Método de pago')),
                ('transaction_date', models.DateField(verbose_name='Fecha de pago')),
                ('currency', models.CharField(choices=[('PEN', 'Soles (PEN)'), ('USD', 'Dólares (USD)'), ('EUR', 'Euros (EUR)')], default='USD', max_length=3, verbose_name='Moneda')),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1, max_digits=10, verbose_name='Tipo de cambio')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Monto total de la transacción')),
                ('reconciled_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Monto conciliado')),
                ('bank_account', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cuenta bancaria')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('CONFIRMED', 'Confirmado'), ('REVERSED', 'Revertido')], default='DRAFT', max_length=10, verbose_name='Estado')),
                ('voucher_file', models.FileField(blank=True, null=True, upload_to='payment_tx/', verbose_name='Comprobante de pago')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='stakeholders.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_created', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='stakeholders.supplier')),
                ('tin_payer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_paid', to='cuentas.tin', verbose_name='Empresa pagadora (TIN)')),
                ('tin_receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_received', to='cuentas.tin', verbose_name='Empresa receptora (TIN)')),
            ],
            options={
                'verbose_name': 'Transacción de pago',
                'verbose_name_plural': 'Transacciones de pago',
                'ordering': ['-transaction_date', '-created'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransactionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('amount_applied', models.DecimalField(decimal_places=2, help_text='Monto de la transacción aplicado a este comprobante', max_digits=14, verbose_name='Monto aplicado')),
                ('notes', models.CharField(blank=True, max_length=200, null=True, verbose_name='Notas')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_lines', to='FINANTIAL.paymentdocument', verbose_name='Comprobante')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_lines', to='FINANTIAL.paymenttransaction', verbose_name='Transacción')),
            ],
            options={
                'verbose_name': 'Línea de transacción',
                'verbose_name_plural': 'Líneas de transacción',
            },
        ),
        migrations.AddIndex(
            model_name='paymentdocument',
            index=models.Index(fields=['status'], name='FINANTIAL_p_status_e9b713_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentdocument',
            index=models.Index(fields=['tin_issuer'], name='FINANTIAL_p_tin_iss_ed8627_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentdocument',
            index=models.Index(fields=['tin_receiver'], name='FINANTIAL_p_tin_rec_c6f92f_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentdocument',
            index=models.Index(fields=['direction'], name='FINANTIAL_p_directi_cb3ff5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentallocation',
            unique_together={('document', 'item')},
        ),
    ]
