# Generated by Django 5.0.6 on 2026-03-17 09:45

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FINANTIAL', '0001_initial'),
        ('cuentas', '0007_alter_account_options_alter_account_accountnumber_and_more'),
        ('stakeholders', '0007_alter_supplier_numberidsupplier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='bankAccountsClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('account', models.CharField(max_length=30, verbose_name='Número de cuenta')),
                ('bankName', models.CharField(blank=True, max_length=50, null=True, verbose_name='Banco')),
            ],
            options={
                'verbose_name': 'Cuenta bancaria de cliente',
                'verbose_name_plural': 'Cuentas bancarias de clientes',
            },
        ),
        migrations.CreateModel(
            name='BankMovements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_reconciled_with_payment', models.BooleanField(default=False, verbose_name='¿Conciliado desde pagos?')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripción')),
                ('opNumber', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nro. operación')),
                ('justification', models.TextField(blank=True, null=True, verbose_name='Justificación')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Monto')),
                ('equivalentAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Monto equivalente')),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Saldo')),
                ('amountReconcilied', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Monto conciliado')),
                ('conciliated', models.BooleanField(default=False, verbose_name='Conciliado')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='vouchers_pdfs/', verbose_name='PDF voucher')),
            ],
            options={
                'verbose_name': 'Movimiento bancario',
                'verbose_name_plural': 'Movimientos bancarios',
                'ordering': ['date', 'created'],
            },
        ),
        migrations.CreateModel(
            name='Conciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('type', models.CharField(choices=[('0', 'Documento'), ('1', 'Movimiento'), ('2', 'Com. Bancarias'), ('3', 'Impuestos')], max_length=1, verbose_name='Tipo')),
                ('amountReconcilied', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Monto conciliado')),
                ('equivalentAmount', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Monto equivalente')),
                ('status', models.BooleanField(default=False, verbose_name='Procesado')),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('PAYMENT', 'Desde pagos')], default='MANUAL', max_length=10, verbose_name='Origen')),
            ],
            options={
                'verbose_name': 'Conciliación',
                'verbose_name_plural': 'Conciliaciones',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='DocumentsUploaded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('file', models.FileField(upload_to='financial_docs/', verbose_name='Archivo')),
                ('description', models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Documento adjunto',
                'verbose_name_plural': 'Documentos adjuntos',
            },
        ),
        migrations.CreateModel(
            name='ExpenseSubCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=60, verbose_name='Nombre')),
                ('description', models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripción')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Subcategoría de gasto',
                'verbose_name_plural': 'Subcategorías de gasto',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FinancialDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('docNumber', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número')),
                ('docType', models.CharField(blank=True, max_length=10, null=True, verbose_name='Tipo')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Monto')),
                ('amountReconcilied', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Monto conciliado')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Documento financiero',
                'verbose_name_plural': 'Documentos financieros',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='IncomeSubCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=60, verbose_name='Nombre')),
                ('description', models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripción')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Subcategoría de ingreso',
                'verbose_name_plural': 'Subcategorías de ingreso',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MovementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=60, verbose_name='Nombre')),
                ('flow', models.CharField(choices=[('0', 'Egreso'), ('1', 'Ingreso')], max_length=1, verbose_name='Flujo')),
                ('description', models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripción')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tipo de movimiento',
                'verbose_name_plural': 'Tipos de movimiento',
                'ordering': ['flow', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='paymentallocation',
            name='allocated_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Monto asignado'),
        ),
        migrations.AlterField(
            model_name='paymentdocument',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_docs_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentdocument',
            name='declare_month',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], null=True, verbose_name='Mes declaración'),
        ),
        migrations.AlterField(
            model_name='paymentdocument',
            name='declare_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Año declaración'),
        ),
        migrations.AlterField(
            model_name='paymentdocument',
            name='direction',
            field=models.CharField(choices=[('IN', 'Ingreso  (cobro al cliente)'), ('OUT', 'Egreso   (pago al proveedor)'), ('INT', 'Interno  (holding ↔ subsidiaria)')], default='OUT', max_length=3, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='paymentdocument',
            name='doc_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='paymentdocument',
            name='doc_type',
            field=models.CharField(choices=[('FAC', 'Factura'), ('BOL', 'Boleta de Venta'), ('RHE', 'Recibo por Honorarios'), ('NCR', 'Nota de Crédito'), ('NDB', 'Nota de Débito'), ('DUA', 'DUA (Importación)'), ('GRE', 'Guía de Remisión'), ('LIQ', 'Liquidación'), ('PLA', 'Planilla'), ('IMP', 'Impuesto / Tributo'), ('PER', 'Percepción'), ('OTR', 'Otro')], default='FAC', max_length=3, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='paymentdocument',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=10, verbose_name='T.C.'),
        ),
        migrations.AlterField(
            model_name='paymentdocument',
            name='has_detraction',
            field=models.BooleanField(default=False, verbose_name='¿Detracción?'),
        ),
        migrations.AlterField(
            model_name='paymentdocument',
            name='has_retention',
            field=models.BooleanField(default=False, verbose_name='¿Retención?'),
        ),
        migrations.AlterField(
            model_name='paymentdocument',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Pagado'),
        ),
        migrations.AlterField(
            model_name='paymentdocument',
            name='pending_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Pendiente'),
        ),
        migrations.AlterField(
            model_name='paymentdocument',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='IGV / IVA'),
        ),
        migrations.AlterField(
            model_name='paymentdocument',
            name='tin_issuer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docs_issued', to='cuentas.tin', verbose_name='Empresa emisora'),
        ),
        migrations.AlterField(
            model_name='paymentdocument',
            name='tin_receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docs_received', to='cuentas.tin', verbose_name='Empresa receptora'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Monto total'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='cuentas.account', verbose_name='Cuenta bancaria'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='stakeholders.client'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=10, verbose_name='T.C.'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='pay_method',
            field=models.CharField(choices=[('TRANSFER', 'Transferencia bancaria'), ('CHECK', 'Cheque'), ('CASH', 'Efectivo'), ('CARD', 'Tarjeta'), ('OTHER', 'Otro')], default='TRANSFER', max_length=10, verbose_name='Método'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='reference',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Referencia / Nro. Op.'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='stakeholders.supplier'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='tin_payer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_paid', to='cuentas.tin', verbose_name='Empresa pagadora'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='tin_receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_received', to='cuentas.tin', verbose_name='Empresa receptora'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='voucher_file',
            field=models.FileField(blank=True, null=True, upload_to='payment_tx/', verbose_name='Voucher'),
        ),
        migrations.AlterField(
            model_name='paymenttransactionline',
            name='amount_applied',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Monto aplicado'),
        ),
        migrations.AddIndex(
            model_name='paymentdocument',
            index=models.Index(fields=['issue_date'], name='FINANTIAL_p_issue_d_8c5096_idx'),
        ),
        migrations.AddField(
            model_name='bankaccountsclient',
            name='idClient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='stakeholders.client'),
        ),
        migrations.AddField(
            model_name='bankmovements',
            name='idAccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_movements', to='cuentas.account', verbose_name='Cuenta bancaria'),
        ),
        migrations.AddField(
            model_name='bankmovements',
            name='originDestination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_movements', to='stakeholders.client', verbose_name='Origen / Destino'),
        ),
        migrations.AddField(
            model_name='bankmovements',
            name='payment_transaction',
            field=models.ForeignKey(blank=True, help_text='Se asigna automáticamente al confirmar una PaymentTransaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_movements', to='FINANTIAL.paymenttransaction', verbose_name='Transacción de pago vinculada'),
        ),
        migrations.AddField(
            model_name='bankmovements',
            name='tin',
            field=models.ForeignKey(blank=True, help_text='Auto-asignada desde la cuenta al guardar', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_movements', to='cuentas.tin', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='bank_movement',
            field=models.ForeignKey(blank=True, help_text='Opcional: vincula con el movimiento real para conciliación automática', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions_linked', to='FINANTIAL.bankmovements', verbose_name='Movimiento bancario'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['status'], name='FINANTIAL_p_status_bdb87c_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['transaction_date'], name='FINANTIAL_p_transac_2f3ccb_idx'),
        ),
        migrations.AddField(
            model_name='conciliation',
            name='idMovArrival',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mov_destino', to='FINANTIAL.bankmovements', verbose_name='Mov. destino'),
        ),
        migrations.AddField(
            model_name='conciliation',
            name='idMovOrigin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mov_origen', to='FINANTIAL.bankmovements', verbose_name='Mov. origen'),
        ),
        migrations.AddField(
            model_name='documentsuploaded',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_docs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankmovements',
            name='idDoc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_movements_doc', to='FINANTIAL.documentsuploaded', verbose_name='Documento adjunto'),
        ),
        migrations.AddField(
            model_name='bankmovements',
            name='expenseSubCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FINANTIAL.expensesubcategories', verbose_name='Subcategoría gasto'),
        ),
        migrations.AddField(
            model_name='financialdocuments',
            name='idTin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_docs', to='cuentas.tin'),
        ),
        migrations.AddField(
            model_name='conciliation',
            name='idDoc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doc_conciliation', to='FINANTIAL.financialdocuments', verbose_name='Documento'),
        ),
        migrations.AddField(
            model_name='bankmovements',
            name='incomeSubCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FINANTIAL.incomesubcategories', verbose_name='Subcategoría ingreso'),
        ),
        migrations.AddField(
            model_name='bankmovements',
            name='movementType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='FINANTIAL.movementtype', verbose_name='Tipo de movimiento'),
        ),
        migrations.AddIndex(
            model_name='conciliation',
            index=models.Index(fields=['type'], name='FINANTIAL_c_type_3e9344_idx'),
        ),
        migrations.AddIndex(
            model_name='conciliation',
            index=models.Index(fields=['status'], name='FINANTIAL_c_status_af1d6b_idx'),
        ),
        migrations.AddIndex(
            model_name='conciliation',
            index=models.Index(fields=['source'], name='FINANTIAL_c_source_1ecf0b_idx'),
        ),
        migrations.AddIndex(
            model_name='bankmovements',
            index=models.Index(fields=['date'], name='FINANTIAL_b_date_f71c3c_idx'),
        ),
        migrations.AddIndex(
            model_name='bankmovements',
            index=models.Index(fields=['conciliated'], name='FINANTIAL_b_concili_faff4b_idx'),
        ),
        migrations.AddIndex(
            model_name='bankmovements',
            index=models.Index(fields=['tin'], name='FINANTIAL_b_tin_id_710251_idx'),
        ),
        migrations.AddIndex(
            model_name='bankmovements',
            index=models.Index(fields=['idAccount'], name='FINANTIAL_b_idAccou_bbcff6_idx'),
        ),
        migrations.AddIndex(
            model_name='bankmovements',
            index=models.Index(fields=['payment_transaction'], name='FINANTIAL_b_payment_f112fd_idx'),
        ),
    ]
