# Generated by Django 5.0.6 on 2026-03-19 15:35

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FINANTIAL', '0002_bankaccountsclient_bankmovements_conciliation_and_more'),
        ('cuentas', '0008_alter_account_currency_delete_account0'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('account_type', models.CharField(choices=[('ASSET', 'Activo'), ('LIABILITY', 'Pasivo'), ('EQUITY', 'Patrimonio'), ('INCOME', 'Ingreso'), ('EXPENSE', 'Gasto'), ('BANK', 'Banco / Tesorería'), ('TAX', 'Impuesto')], max_length=10, verbose_name='Tipo')),
                ('currency', models.CharField(choices=[('PEN', 'Soles (PEN)'), ('USD', 'Dólares (USD)'), ('EUR', 'Euros (EUR)')], default='PEN', max_length=3, verbose_name='Moneda')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción')),
                ('active', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Cuenta contable',
                'verbose_name_plural': 'Plan de cuentas',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=80, verbose_name='Nombre')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Válido desde')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Válido hasta')),
            ],
            options={
                'verbose_name': 'Centro de costos',
                'verbose_name_plural': 'Centros de costos',
                'ordering': ['tin__tinName', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('from_currency', models.CharField(choices=[('PEN', 'Soles (PEN)'), ('USD', 'Dólares (USD)'), ('EUR', 'Euros (EUR)')], max_length=3, verbose_name='Moneda origen')),
                ('to_currency', models.CharField(choices=[('PEN', 'Soles (PEN)'), ('USD', 'Dólares (USD)'), ('EUR', 'Euros (EUR)')], max_length=3, verbose_name='Moneda destino')),
                ('rate_date', models.DateField(verbose_name='Fecha')),
                ('rate', models.DecimalField(decimal_places=6, max_digits=14, verbose_name='Tasa')),
                ('source', models.CharField(default='Manual', help_text='SBS, SUNAT, Manual, etc.', max_length=50, verbose_name='Fuente')),
            ],
            options={
                'verbose_name': 'Tipo de cambio',
                'verbose_name_plural': 'Tipos de cambio',
                'ordering': ['-rate_date'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('reference', models.CharField(max_length=80, verbose_name='Referencia')),
                ('entry_date', models.DateField(verbose_name='Fecha del asiento')),
                ('period_year', models.PositiveSmallIntegerField(verbose_name='Año')),
                ('period_month', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], verbose_name='Mes')),
                ('currency', models.CharField(choices=[('PEN', 'Soles (PEN)'), ('USD', 'Dólares (USD)'), ('EUR', 'Euros (EUR)')], default='PEN', max_length=3, verbose_name='Moneda')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción')),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('PAYMENT', 'Transacción de pago'), ('CONCILIATION', 'Conciliación'), ('CLOSURE', 'Cierre de período')], default='MANUAL', max_length=15, verbose_name='Origen')),
                ('is_posted', models.BooleanField(default=False, verbose_name='Contabilizado')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha contabilización')),
            ],
            options={
                'verbose_name': 'Asiento contable',
                'verbose_name_plural': 'Asientos contables',
                'ordering': ['-entry_date', '-created'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Debe')),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Haber')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Línea de asiento',
                'verbose_name_plural': 'Líneas de asiento',
            },
        ),
        migrations.CreateModel(
            name='MonthlyClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('period_year', models.PositiveSmallIntegerField(verbose_name='Año')),
                ('period_month', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], verbose_name='Mes')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Saldo inicial')),
                ('total_ingresos', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total ingresos')),
                ('total_egresos', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total egresos')),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Saldo final')),
                ('movements_count', models.PositiveIntegerField(default=0, verbose_name='Nro. movimientos')),
                ('unreconciled_count', models.PositiveIntegerField(default=0, verbose_name='Sin conciliar')),
                ('status', models.CharField(choices=[('OPEN', 'Abierto'), ('CLOSED', 'Cerrado'), ('APPROVED', 'Aprobado'), ('REOPENED', 'Reabierto')], default='OPEN', max_length=10, verbose_name='Estado')),
                ('is_locked', models.BooleanField(default=False, help_text='Si True, no se permiten nuevos movimientos en este período', verbose_name='Período bloqueado')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha cierre')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha aprobación')),
                ('reopen_reason', models.TextField(blank=True, null=True, verbose_name='Motivo reapertura')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Cierre mensual',
                'verbose_name_plural': 'Cierres mensuales',
                'ordering': ['-period_year', '-period_month', 'account'],
            },
        ),
        migrations.CreateModel(
            name='TaxCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=80, verbose_name='Nombre')),
                ('tax_type', models.CharField(choices=[('IGV', 'IGV / IVA'), ('DETRACTION', 'Detracción'), ('RETENTION', 'Retención'), ('PERCEPTION', 'Percepción'), ('OTHER', 'Otro')], max_length=15, verbose_name='Tipo')),
                ('rate', models.DecimalField(decimal_places=4, help_text='Ej: 18.0000 para IGV 18%', max_digits=6, verbose_name='Tasa (%)')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('applies_to_doc_types', models.CharField(blank=True, help_text='FAC,BOL,RHE — vacío=todos', max_length=100, verbose_name='Aplica a tipos')),
            ],
            options={
                'verbose_name': 'Código de impuesto',
                'verbose_name_plural': 'Códigos de impuesto',
                'ordering': ['tax_type', 'code'],
            },
        ),
        migrations.RemoveField(
            model_name='bankaccountsclient',
            name='idClient',
        ),
        migrations.RemoveIndex(
            model_name='bankmovements',
            name='FINANTIAL_b_payment_f112fd_idx',
        ),
        migrations.AlterField(
            model_name='bankmovements',
            name='payment_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_movements', to='FINANTIAL.paymenttransaction', verbose_name='Transacción de pago vinculada'),
        ),
        migrations.AlterField(
            model_name='bankmovements',
            name='tin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_movements', to='cuentas.tin', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='paymentdocument',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=10, verbose_name='T.C.'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='bank_movement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions_linked', to='FINANTIAL.bankmovements', verbose_name='Movimiento bancario'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=10, verbose_name='T.C.'),
        ),
        migrations.AddField(
            model_name='accountingaccount',
            name='bank_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_account', to='cuentas.account', verbose_name='Cuenta bancaria vinculada'),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_centers_responsible', to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='tin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_centers', to='cuentas.tin', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='bankmovements',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_movements', to='FINANTIAL.costcenter', verbose_name='Centro de costos'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='FINANTIAL.costcenter', verbose_name='Centro de costos'),
        ),
        migrations.AlterField(
            model_name='paymentdocument',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_documents', to='FINANTIAL.costcenter', verbose_name='Centro de costos'),
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['rate_date', 'from_currency', 'to_currency'], name='FINANTIAL_e_rate_da_ae2540_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='exchangerate',
            unique_together={('from_currency', 'to_currency', 'rate_date')},
        ),
        migrations.AddField(
            model_name='journalentry',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='FINANTIAL.costcenter', verbose_name='Centro de costos'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='payment_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entry', to='FINANTIAL.paymenttransaction', verbose_name='Transacción de pago'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='tin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='cuentas.tin', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_lines', to='FINANTIAL.accountingaccount', verbose_name='Cuenta contable'),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_lines', to='FINANTIAL.costcenter', verbose_name='Centro de costos'),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='FINANTIAL.journalentry', verbose_name='Asiento'),
        ),
        migrations.AddField(
            model_name='monthlyclosure',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_closures', to='cuentas.account', verbose_name='Cuenta bancaria'),
        ),
        migrations.AddField(
            model_name='monthlyclosure',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closures_approved', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por'),
        ),
        migrations.AddField(
            model_name='monthlyclosure',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closures_executed', to=settings.AUTH_USER_MODEL, verbose_name='Cerrado por'),
        ),
        migrations.AddField(
            model_name='monthlyclosure',
            name='tin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_closures', to='cuentas.tin', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='taxcode',
            name='accounting_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_codes', to='FINANTIAL.accountingaccount', verbose_name='Cuenta contable destino'),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='tax_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_lines', to='FINANTIAL.taxcode', verbose_name='Código impuesto'),
        ),
        migrations.AddField(
            model_name='paymentdocument',
            name='tax_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_documents', to='FINANTIAL.taxcode', verbose_name='Código de impuesto'),
        ),
        migrations.DeleteModel(
            name='bankAccountsClient',
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['period_year', 'period_month', 'tin'], name='FINANTIAL_j_period__2b90b8_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlyclosure',
            index=models.Index(fields=['period_year', 'period_month', 'tin'], name='FINANTIAL_m_period__23b47e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlyclosure',
            unique_together={('account', 'period_year', 'period_month')},
        ),
    ]
