# Generated by Django 5.0.6 on 2026-03-23 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FINANTIAL', '0003_accountingaccount_costcenter_exchangerate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conciliation',
            name='idDoc',
        ),
        migrations.AddField(
            model_name='conciliation',
            name='payment_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conciliations', to='FINANTIAL.paymentdocument', verbose_name='Comprobante'),
        ),
    ]
