# Generated by Django 5.0.6 on 2026-03-23 19:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FINANTIAL', '0004_remove_conciliation_iddoc_and_more'),
        ('cuentas', '0008_alter_account_currency_delete_account0'),
        ('stakeholders', '0008_alter_bankaccountsclient_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='paymentdocument',
            constraint=models.UniqueConstraint(condition=models.Q(('doc_number__isnull', False), models.Q(('doc_number', ''), _negated=True)), fields=('doc_type', 'doc_number', 'tin_issuer'), name='unique_payment_doc_number_per_issuer'),
        ),
    ]
