# Generated by Django 5.0.6 on 2026-03-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FINANTIAL', '0005_paymentdocument_unique_payment_doc_number_per_issuer'),
        ('sales', '0040_paymentallocation_cost_level'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paymentallocation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='cost_level',
            field=models.CharField(choices=[('QUO', 'Cotización Master — Cliente → Holding (unitCost)'), ('INT', 'Cotización Interna — Subsidiaria ↔ Holding (unitCostInt)'), ('WO', 'Orden de Trabajo — Holding → Proveedor (unitCostWO)')], default='QUO', max_length=3, verbose_name='Nivel de costo'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentallocation',
            unique_together={('document', 'item', 'cost_level')},
        ),
    ]
