# Generated by Django 5.0.6 on 2024-12-19 10:54

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=100, verbose_name='Nombres')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellidos')),
                ('phoneNumber', models.CharField(blank=True, null=True, verbose_name='Telefono')),
                ('ruc', models.CharField(blank=True, null=True, verbose_name='RUC')),
                ('dni', models.CharField(blank=True, null=True, verbose_name='DNI')),
                ('address', models.CharField(blank=True, null=True, verbose_name='Direccion')),
                ('position', models.CharField(blank=True, choices=[('0', 'Administrador'), ('1', 'Contabilidad'), ('2', 'Supervisor producción'), ('4', 'Trabajador'), ('5', 'Adquisiciones'), ('6', 'Finanzas'), ('7', 'Tesoreria'), ('8', 'Consultor'), ('9', 'Recursos humanos')], max_length=1, verbose_name='Tipo de usuario')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Género')),
                ('condition', models.CharField(blank=True, choices=[('0', 'Activo'), ('1', 'Cesado'), ('2', 'Licencia'), ('3', 'Vacaciones')], max_length=1, verbose_name='Condicion')),
                ('EC_full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contacto - nombres')),
                ('EC_relationship', models.CharField(blank=True, max_length=20, null=True, verbose_name='Contacto - parentesco')),
                ('EC_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Contacto - telefono')),
                ('EC_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Contacto - correo')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Documentations',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('typeDoc', models.CharField(choices=[('0', 'Contrato'), ('1', 'CV'), ('2', 'Informe Mensual'), ('3', 'Memorandum'), ('4', 'Oficio'), ('5', 'Carta'), ('6', 'Otro'), ('7', 'DNI')], max_length=1, verbose_name='Tipo de dpcumento')),
                ('idDoc', models.CharField(blank=True, max_length=25, null=True, verbose_name='Id doc')),
                ('sumary', models.CharField(blank=True, max_length=150, null=True, verbose_name='Resumen')),
                ('is_multiple', models.BooleanField(default=False)),
                ('doc_file', models.FileField(blank=True, null=True, upload_to='doc_pdfs/')),
                ('idUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento de personal',
                'verbose_name_plural': 'Documentos de personal',
            },
        ),
    ]
