# Generated by Django 5.0.6 on 2024-07-12 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, choices=[('0', 'Administrador'), ('1', 'Contabilidad'), ('2', 'Supervisor producción'), ('3', 'Supervisor compras'), ('4', 'Trabajador'), ('5', 'Adquisiciones'), ('6', 'Finanzas')], max_length=1, verbose_name='Tipo de usuario'),
        ),
    ]
