# Generated by Django 5.0.6 on 2025-07-12 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_alter_account_currency'),
        ('users', '0003_alter_user_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuentas.tin'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_boss',
            field=models.BooleanField(default=False),
        ),
    ]
