# Generated by Django 5.0.6 on 2024-07-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='condition',
            field=models.CharField(blank=True, choices=[('0', 'Activo'), ('1', 'Cesado'), ('2', 'Licencia'), ('3', 'Vacaciones')], max_length=1, verbose_name='Condicion'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Género'),
        ),
        migrations.AddField(
            model_name='user',
            name='phoneNumber',
            field=models.CharField(blank=True, null=True, verbose_name='Telefono'),
        ),
    ]
