# Generated by Django 5.0.6 on 2025-09-08 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, choices=[('0', 'Administrador'), ('1', 'Comercial'), ('2', 'Finanzas'), ('3', 'Producción'), ('4', 'Gerencia'), ('5', 'Logística'), ('6', 'Recursos humanos'), ('7', 'Consultor externo'), ('8', 'CEO general'), ('9', 'TI')], max_length=1, verbose_name='Area'),
        ),
    ]
