# Generated by Django 5.0.6 on 2024-11-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_ruc_documentations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentations',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
