# Generated by Django 5.0.6 on 2024-11-13 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_documentations_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cv_file',
        ),
    ]
