# Generated by Django 5.0.6 on 2024-11-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_user_cv_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, choices=[('0', 'Administrador'), ('1', 'Contabilidad'), ('2', 'Supervisor producción'), ('4', 'Trabajador'), ('5', 'Adquisiciones'), ('6', 'Finanzas'), ('7', 'Tesoreria'), ('8', 'Consultor'), ('9', 'Recursos humanos')], max_length=1, verbose_name='Tipo de usuario'),
        ),
    ]
