# Generated by Django 5.0.6 on 2024-11-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_address_user_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='EC_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Contacto - correo'),
        ),
        migrations.AddField(
            model_name='user',
            name='EC_full_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contacto - nombres'),
        ),
        migrations.AddField(
            model_name='user',
            name='EC_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Contacto - telefono'),
        ),
        migrations.AddField(
            model_name='user',
            name='EC_relationship',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Contacto - parentesco'),
        ),
    ]
