# Generated by Django 5.0.6 on 2024-11-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_ec_email_user_ec_full_name_user_ec_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentations',
            name='typeDoc',
            field=models.CharField(choices=[('0', 'Contrato'), ('1', 'CV'), ('2', 'Informe Mensual'), ('3', 'Memorandum'), ('4', 'Oficio'), ('5', 'Carta'), ('6', 'Otro'), ('7', 'DNI')], max_length=1, verbose_name='Tipo de dpcumento'),
        ),
    ]
