# Generated by Django 5.0.6 on 2024-11-18 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_documentations_is_multiple'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentations',
            name='idDoc',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Id doc'),
        ),
        migrations.AlterField(
            model_name='documentations',
            name='sumary',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Resumen'),
        ),
    ]
