# Generated by Django 5.0.6 on 2024-11-18 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_documentations_iddoc_alter_documentations_sumary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentations',
            name='idDoc',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Id doc'),
        ),
    ]
