# Generated by Django 5.0.6 on 2024-12-19 10:54

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, verbose_name='Nombre')),
                ('brand', models.CharField(blank=True, max_length=40, null=True, verbose_name='Marca')),
                ('code', models.CharField(max_length=13, verbose_name='Codigo')),
                ('dateInput', models.DateField(blank=True, null=True, verbose_name='Fecha de adquisición')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('amount', models.IntegerField(blank=True, null=True, verbose_name='Cantidad')),
                ('unit', models.CharField(choices=[('0', 'Unidades'), ('1', 'Kg'), ('2', 'Litros')], max_length=1, verbose_name='Unidad de medida')),
                ('status', models.CharField(choices=[('0', 'Activo'), ('1', 'De baja'), ('2', 'Mantenimiento'), ('3', 'No habido')], max_length=1, verbose_name='Estado')),
                ('location', models.CharField(blank=True, choices=[('0', 'Oficina Lima'), ('1', 'Usa')], max_length=1, null=True, verbose_name='Ubicación')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.workers')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transformer',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('model_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Modelo')),
                ('KVA', models.CharField(blank=True, choices=[('0', '15'), ('1', '30'), ('2', '75'), ('3', '100'), ('4', '167'), ('5', '200'), ('6', '250'), ('7', '400'), ('8', '500'), ('9', '600'), ('10', '750'), ('11', '1000'), ('12', '1500'), ('13', '2000')], max_length=2, null=True, verbose_name='kVA CAPACITY')),
                ('HVTAP', models.CharField(blank=True, choices=[('0', 'K-Tap - HV'), ('1', 'Fix HV')], max_length=2, null=True, verbose_name='HV TAP')),
                ('KTapHV', models.CharField(blank=True, choices=[('0', '12700/7200'), ('1', '24940/14400')], max_length=2, null=True, verbose_name='K Tap HV')),
                ('FIXHV', models.CharField(blank=True, choices=[('0', '7200'), ('1', '12470'), ('2', '22900')], max_length=2, null=True, verbose_name='FIX HV')),
                ('LV', models.CharField(blank=True, choices=[('0', '120/240'), ('1', '277/480')], max_length=2, null=True, verbose_name='LV')),
                ('HZ', models.CharField(blank=True, choices=[('0', '50'), ('1', '60')], max_length=2, null=True, verbose_name='HZ')),
                ('TYPE', models.CharField(blank=True, choices=[('0', 'Mono-phasic'), ('1', 'Three-phasic')], max_length=2, null=True, verbose_name='TYPE')),
                ('MOUNTING', models.CharField(blank=True, choices=[('0', 'Pole'), ('1', 'Standard'), ('2', 'Feed Through Pad')], max_length=2, null=True, verbose_name='MOUNTING TYPE')),
                ('COOLING', models.CharField(blank=True, choices=[('0', 'Oil'), ('1', 'Dry')], max_length=2, null=True, verbose_name='COOLING')),
                ('WINDING', models.CharField(blank=True, choices=[('0', 'Al - Al'), ('1', 'Cu - CU')], max_length=2, null=True, verbose_name='WINDING')),
                ('INSULAT', models.CharField(blank=True, choices=[('0', 'A'), ('1', 'E'), ('2', 'H')], max_length=2, null=True, verbose_name='INSULAT CLASS')),
                ('CONNECTION', models.CharField(blank=True, choices=[('0', 'WEY'), ('1', 'DELTA')], max_length=2, null=True, verbose_name='CONNECTION')),
                ('STANDARD', models.CharField(blank=True, choices=[('0', 'NMX-116'), ('1', 'IEC 61558')], max_length=2, null=True, verbose_name='STANDARD')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Transformador',
                'verbose_name_plural': 'Transformadores',
            },
        ),
    ]
