# Generated by Django 5.0.6 on 2025-05-05 02:17

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0007_alter_cliente_ruc'),
        ('cuentas', '0002_alter_account_nickname'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('month_dec', models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], null=True, verbose_name='Mes de declaración')),
                ('year_dec', models.PositiveIntegerField(blank=True, null=True, verbose_name='Año de declaración')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Fecha de emisión')),
                ('typeInvoice', models.CharField(blank=True, choices=[('0', 'Factura'), ('1', 'RHE'), ('2', 'Doc del exterior'), ('3', 'Impuesto'), ('4', 'Planilla'), ('5', 'Nota de credito'), ('10', 'Liq'), ('7', 'Diario'), ('8', 'DUA'), ('9', 'Boleto Aéreo'), ('10', 'Liquidacion'), ('11', 'percepcion'), ('12', 'Otros')], max_length=2, null=True, verbose_name='Tipo de comprobante')),
                ('typeCurrency', models.CharField(blank=True, choices=[('0', 'S/.'), ('1', '$'), ('2', '€')], max_length=1, null=True, verbose_name='Tipo de moneda')),
                ('idInvoice', models.CharField(blank=True, max_length=50, null=True, verbose_name='Id de comprobante')),
                ('detraction', models.CharField(choices=[('0', 'No requiere'), ('1', 'Pendiente'), ('2', 'Completado')], default='0', max_length=1, verbose_name='Detracción - Factura')),
                ('shippingGuide', models.CharField(choices=[('0', 'No requiere'), ('1', 'Pendiente'), ('2', 'Completado')], default='0', max_length=1, verbose_name='Guia de remisión - Factura')),
                ('retention', models.CharField(choices=[('0', 'No requiere'), ('1', 'Pendiente'), ('2', 'Completado')], default='0', max_length=1, verbose_name='Retención - RHE')),
                ('annotation', models.CharField(blank=True, choices=[('0', 'anticipo'), ('1', 'pago final'), ('2', 'total')], max_length=2, null=True, verbose_name='Anotaciones')),
                ('contabilidad', models.CharField(blank=True, choices=[('0', 'Agente de aduana'), ('1', 'Caja chica'), ('2', 'Caja General'), ('3', 'Caja General ventas'), ('4', 'RHE general'), ('5', 'Adicional'), ('6', 'Personal'), ('7', 'PL'), ('8', 'renta')], max_length=2, null=True, verbose_name='Sub Categoria contabilidad')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto')),
                ('equivalentAmount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto equivalente')),
                ('amountReconcilied', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto conciliado')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='financialDocs_pdfs/')),
                ('idClient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('idTin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuentas.tin')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finantialDocumentes_user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Documento financiero',
                'verbose_name_plural': 'Documentos financieros',
            },
        ),
        migrations.CreateModel(
            name='OthersDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Fecha de emisión')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='othersDocuments_pdfs/')),
                ('idFinacialDocuments', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documentos.financialdocuments')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OthersDocuments_user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Documento generico',
                'verbose_name_plural': 'Documentos genericos',
            },
        ),
    ]
