# Generated by Django 5.0.6 on 2025-05-05 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0003_othersdocuments_typedoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='othersdocuments',
            name='typeDoc',
            field=models.CharField(blank=True, choices=[('0', 'Guia de remisión'), ('1', 'Liquidación'), ('2', 'Retencion'), ('3', 'Detraccion'), ('9', 'Otros')], default='9', max_length=1, null=True, verbose_name='Tipo de documento'),
        ),
    ]
