# Generated by Django 5.0.6 on 2025-05-05 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0004_alter_othersdocuments_typedoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialdocuments',
            name='equivalentAmount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto equivalente'),
        ),
    ]
