# Generated by Django 5.0.6 on 2025-05-06 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0005_alter_financialdocuments_equivalentamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='othersdocuments',
            name='idOtherDocument',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Id documento'),
        ),
    ]
