# Generated by Django 5.0.6 on 2025-05-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0007_alter_othersdocuments_typedoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialdocuments',
            name='typeCurrency',
            field=models.CharField(blank=True, choices=[('0', 'PEN'), ('1', 'USD'), ('2', 'EUR')], max_length=1, null=True, verbose_name='Tipo de moneda'),
        ),
    ]
