# Generated by Django 5.0.6 on 2025-05-20 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0008_alter_financialdocuments_typecurrency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialdocuments',
            options={'ordering': ['created'], 'verbose_name': 'Documento financiero', 'verbose_name_plural': 'Documentos financieros'},
        ),
    ]
