# Generated by Django 5.0.6 on 2025-06-04 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0010_rawsfilesrhe'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialdocuments',
            name='doc_emisor',
            field=models.CharField(blank=True, choices=[('0', 'RUC'), ('1', 'DNI'), ('2', 'DNI'), ('2', 'Carnet de Extranjería')], max_length=1, null=True, verbose_name='Tipo de Doc. Emisor'),
        ),
        migrations.AddField(
            model_name='financialdocuments',
            name='doc_status',
            field=models.CharField(blank=True, choices=[('0', 'No Anulado'), ('1', 'Anulado'), ('2', 'Revertido')], max_length=1, null=True, verbose_name='Estado Doc. Emitido'),
        ),
        migrations.AddField(
            model_name='financialdocuments',
            name='incomeTax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Impuesto a la Renta'),
        ),
        migrations.AddField(
            model_name='financialdocuments',
            name='netAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto neto'),
        ),
        migrations.AddField(
            model_name='financialdocuments',
            name='pendingNetPayment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto Neto Pendiente de Pago'),
        ),
        migrations.AddField(
            model_name='rawsfilesrhe',
            name='status',
            field=models.CharField(blank=True, choices=[('0', 'Procesando'), ('1', 'Completado'), ('2', 'Error')], max_length=1, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='financialdocuments',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto bruto'),
        ),
        migrations.AlterField(
            model_name='financialdocuments',
            name='typeCurrency',
            field=models.CharField(blank=True, choices=[('0', 'PEN'), ('1', 'USD'), ('2', 'EUR')], max_length=1, null=True, verbose_name='Moneda de Operación'),
        ),
        migrations.AlterField(
            model_name='financialdocuments',
            name='typeInvoice',
            field=models.CharField(blank=True, choices=[('0', 'Factura'), ('1', 'RHE'), ('2', 'Doc del exterior'), ('3', 'Impuesto'), ('4', 'Planilla'), ('5', 'Nota de credito'), ('10', 'Liq'), ('7', 'Diario'), ('8', 'DUA'), ('9', 'Boleto Aéreo'), ('10', 'Liquidacion'), ('11', 'percepcion'), ('12', 'Otros'), ('13', 'Boleta de venta')], max_length=2, null=True, verbose_name='Tipo de Doc. Emisor'),
        ),
    ]
