# Generated by Django 5.0.6 on 2025-06-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0011_financialdocuments_doc_emisor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialdocuments',
            name='xlm_file',
            field=models.FileField(blank=True, null=True, upload_to='financialDocs_pdfs/'),
        ),
    ]
