# Generated by Django 5.0.6 on 2025-06-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0012_financialdocuments_xlm_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialdocuments',
            name='xlm_file',
        ),
        migrations.AddField(
            model_name='financialdocuments',
            name='xml_file',
            field=models.FileField(blank=True, null=True, upload_to='financialDocs_xlms/'),
        ),
    ]
