# Generated by Django 5.0.6 on 2025-06-04 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0014_alter_financialdocuments_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialdocuments',
            name='incomeTax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Impuesto'),
        ),
    ]
