# Generated by Django 5.0.6 on 2025-06-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0015_alter_financialdocuments_incometax'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialdocuments',
            name='declareFlag',
            field=models.BooleanField(default=True, verbose_name='Declaracion?'),
        ),
        migrations.AddField(
            model_name='financialdocuments',
            name='shortDescription',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripción corta'),
        ),
    ]
