# Generated by Django 5.0.6 on 2025-07-04 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expenses',
            options={'ordering': ['created'], 'verbose_name': 'Documento de compra', 'verbose_name_plural': 'Documentos de compras'},
        ),
    ]
