# Generated by Django 5.0.6 on 2025-07-09 15:45

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_cliente_electronicsignature_and_more'),
        ('cuentas', '0003_alter_account_currency'),
        ('purchase', '0003_expenses_trackdoc_alter_expenses_pdf_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('idOrder', models.IntegerField(blank=True, null=True, verbose_name='Id Requerimiento')),
                ('dateChange', models.DateTimeField(verbose_name='Fecha y hora')),
                ('orderState', models.CharField(choices=[('0', 'solicitado'), ('1', 'aprobado'), ('2', 'conciliado'), ('3', 'cancelado')], max_length=1, verbose_name='Estado de orden')),
                ('amountAssigned', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto asignado')),
            ],
            options={
                'verbose_name': 'seguimiento de requerimiento',
                'verbose_name_plural': 'seguimientos de requerimientos',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Fecha de emisión')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PurchaseOrder_user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', models.CharField(blank=True, choices=[('0', 'Solicitado'), ('1', 'Aprobado'), ('2', 'Denegado'), ('3', 'Observado'), ('4', 'Creado')], max_length=1, null=True, verbose_name='Estado')),
                ('listName', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de lista')),
                ('tag1', models.CharField(blank=True, choices=[('0', 'Solicitado'), ('1', 'Aprobado'), ('2', 'Denegado'), ('3', 'Observado'), ('4', 'Creado')], default='0', max_length=1, null=True, verbose_name='Adquisiciones')),
                ('dt1', models.DateTimeField(blank=True, null=True, verbose_name='F. adquisiciones')),
                ('tag2', models.CharField(blank=True, choices=[('0', 'Solicitado'), ('1', 'Aprobado'), ('2', 'Denegado'), ('3', 'Observado'), ('4', 'Creado')], default='4', max_length=1, null=True, verbose_name='Contabilidad')),
                ('dt2', models.DateTimeField(blank=True, null=True, verbose_name='F. contabilidad ')),
                ('tag3', models.CharField(blank=True, choices=[('0', 'Solicitado'), ('1', 'Aprobado'), ('2', 'Denegado'), ('3', 'Observado'), ('4', 'Creado')], default='4', max_length=1, null=True, verbose_name='Finanzas')),
                ('dt3', models.DateTimeField(blank=True, null=True, verbose_name='F. gereFinanzasncia')),
                ('tag4', models.CharField(blank=True, choices=[('0', 'Solicitado'), ('1', 'Aprobado'), ('2', 'Denegado'), ('3', 'Observado'), ('4', 'Creado')], default='4', max_length=1, null=True, verbose_name='Gerencia')),
                ('dt4', models.DateTimeField(blank=True, null=True, verbose_name='F. Gerencia')),
                ('idPetitioner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='req_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lista de solicitudes',
                'verbose_name_plural': 'Listas de solicitudes',
            },
        ),
        migrations.CreateModel(
            name='requirementItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Cantidad')),
                ('currency', models.CharField(blank=True, choices=[('0', 'PEN'), ('1', 'USD'), ('2', 'EUR')], max_length=1, null=True, verbose_name='Moneda')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio')),
                ('idRequirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase.requirements')),
            ],
            options={
                'verbose_name': 'Item de requerimiento',
                'verbose_name_plural': 'Items de requerimientos',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='requirementsInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('month_dec', models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], null=True, verbose_name='Mes de declaración')),
                ('year_dec', models.PositiveIntegerField(blank=True, null=True, verbose_name='Año de declaración')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Fecha de emisión')),
                ('idInvoice', models.CharField(blank=True, max_length=50, null=True, verbose_name='Id de factura')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='requirementsInvoice_pdfs/')),
                ('idClient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('idRequirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase.requirements')),
                ('idTin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuentas.tin')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirementsInvoice_user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='requirementsQuotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('idQuote', models.CharField(blank=True, max_length=50, null=True, verbose_name='Id de cotización')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='requirementsQuotes_pdfs/')),
                ('idProvider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('idRequirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase.requirements')),
            ],
            options={
                'verbose_name': 'Cotización de requerimiento',
                'verbose_name_plural': 'Cotizaciones de requerimientos',
                'ordering': ['created'],
            },
        ),
    ]
