# Generated by Django 5.0.6 on 2025-07-09 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_requesttracking_purchaseorder_requirements_and_more'),
        ('suppliers', '0002_supplier_status_alter_contacto_last_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requirements',
            options={'verbose_name': 'Requerimiento', 'verbose_name_plural': 'Requerimientos'},
        ),
        migrations.AlterModelOptions(
            name='requirementsinvoice',
            options={'ordering': ['created'], 'verbose_name': 'Invoice de requerimiento', 'verbose_name_plural': 'Invoices de requerimientos'},
        ),
        migrations.RemoveField(
            model_name='requesttracking',
            name='amountAssigned',
        ),
        migrations.RemoveField(
            model_name='requesttracking',
            name='dateChange',
        ),
        migrations.RemoveField(
            model_name='requesttracking',
            name='idOrder',
        ),
        migrations.RemoveField(
            model_name='requesttracking',
            name='orderState',
        ),
        migrations.RemoveField(
            model_name='requirements',
            name='dt1',
        ),
        migrations.RemoveField(
            model_name='requirements',
            name='dt2',
        ),
        migrations.RemoveField(
            model_name='requirements',
            name='dt3',
        ),
        migrations.RemoveField(
            model_name='requirements',
            name='dt4',
        ),
        migrations.RemoveField(
            model_name='requirements',
            name='listName',
        ),
        migrations.RemoveField(
            model_name='requirements',
            name='status',
        ),
        migrations.RemoveField(
            model_name='requirements',
            name='tag1',
        ),
        migrations.RemoveField(
            model_name='requirements',
            name='tag2',
        ),
        migrations.RemoveField(
            model_name='requirements',
            name='tag3',
        ),
        migrations.RemoveField(
            model_name='requirements',
            name='tag4',
        ),
        migrations.RemoveField(
            model_name='requirementsinvoice',
            name='idClient',
        ),
        migrations.AddField(
            model_name='requesttracking',
            name='area',
            field=models.CharField(blank=True, choices=[('0', 'Usuario'), ('1', 'Area Manager'), ('2', 'Gerencia'), ('3', 'Compras'), ('4', 'Contabilidad'), ('4', 'Finanzas')], max_length=1, null=True, verbose_name='Area de seguimiento'),
        ),
        migrations.AddField(
            model_name='requesttracking',
            name='idRequirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase.requirements'),
        ),
        migrations.AddField(
            model_name='requesttracking',
            name='status',
            field=models.CharField(blank=True, choices=[('0', 'Creado'), ('1', 'Recibido'), ('2', 'Aprobado'), ('3', 'Rechazado'), ('4', 'Observado'), ('5', 'Completado')], max_length=1, null=True, verbose_name='Estado de orden'),
        ),
        migrations.AddField(
            model_name='requirements',
            name='area',
            field=models.CharField(blank=True, choices=[('0', 'Comercial'), ('1', 'Producción'), ('3', 'Gerencia'), ('4', 'Logística'), ('5', 'TI')], max_length=1, null=True, verbose_name='Area de compañia'),
        ),
        migrations.AddField(
            model_name='requirementsinvoice',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto bruto'),
        ),
        migrations.AddField(
            model_name='requirementsinvoice',
            name='amountReconcilied',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto conciliado'),
        ),
        migrations.AddField(
            model_name='requirementsinvoice',
            name='annotation',
            field=models.CharField(blank=True, choices=[('0', 'anticipo'), ('1', 'pago final'), ('2', 'total')], max_length=2, null=True, verbose_name='Anotaciones'),
        ),
        migrations.AddField(
            model_name='requirementsinvoice',
            name='declareFlag',
            field=models.BooleanField(default=True, verbose_name='Declaracion?'),
        ),
        migrations.AddField(
            model_name='requirementsinvoice',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='requirementsinvoice',
            name='detraction',
            field=models.CharField(choices=[('0', 'No requiere'), ('1', 'Pendiente'), ('2', 'Completado')], default='0', max_length=1, verbose_name='Detracción - Factura'),
        ),
        migrations.AddField(
            model_name='requirementsinvoice',
            name='doc_status',
            field=models.CharField(blank=True, choices=[('0', 'No Anulado'), ('1', 'Anulado'), ('2', 'Revertido')], max_length=1, null=True, verbose_name='Estado Doc. Emitido'),
        ),
        migrations.AddField(
            model_name='requirementsinvoice',
            name='equivalentAmount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto equivalente'),
        ),
        migrations.AddField(
            model_name='requirementsinvoice',
            name='idSupplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier'),
        ),
        migrations.AddField(
            model_name='requirementsinvoice',
            name='incomeTax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Impuesto'),
        ),
        migrations.AddField(
            model_name='requirementsinvoice',
            name='netAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto neto'),
        ),
        migrations.AddField(
            model_name='requirementsinvoice',
            name='pendingNetPayment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto Neto Pendiente de Pago'),
        ),
        migrations.AddField(
            model_name='requirementsinvoice',
            name='retention',
            field=models.CharField(choices=[('0', 'No requiere'), ('1', 'Pendiente'), ('2', 'Completado')], default='0', max_length=1, verbose_name='Retención - RHE'),
        ),
        migrations.AddField(
            model_name='requirementsinvoice',
            name='shippingGuide',
            field=models.CharField(choices=[('0', 'No requiere'), ('1', 'Pendiente'), ('2', 'Completado')], default='0', max_length=1, verbose_name='Guia de remisión - Factura'),
        ),
        migrations.AddField(
            model_name='requirementsinvoice',
            name='shortDescription',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripción corta'),
        ),
        migrations.AddField(
            model_name='requirementsinvoice',
            name='typeCurrency',
            field=models.CharField(blank=True, choices=[('0', 'PEN'), ('1', 'USD'), ('2', 'EUR')], max_length=1, null=True, verbose_name='Moneda de Operación'),
        ),
        migrations.AddField(
            model_name='requirementsinvoice',
            name='typeInvoice',
            field=models.CharField(blank=True, choices=[('0', 'Factura'), ('1', 'RHE'), ('2', 'Doc del exterior'), ('3', 'Impuesto'), ('4', 'Planilla'), ('5', 'Nota de credito'), ('7', 'Diario'), ('8', 'DUA'), ('9', 'Boleto Aéreo'), ('10', 'Liquidacion'), ('11', 'percepcion'), ('12', 'Otros'), ('13', 'Boleta de venta')], max_length=2, null=True, verbose_name='Tipo de Doc. Emisor'),
        ),
        migrations.AddField(
            model_name='requirementsinvoice',
            name='xml_file',
            field=models.FileField(blank=True, null=True, upload_to='purchaseDocs_xlms/'),
        ),
        migrations.AlterField(
            model_name='requirementitems',
            name='idRequirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirementItems_requirement', to='purchase.requirements'),
        ),
        migrations.AlterField(
            model_name='requirementitems',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='requirementsinvoice',
            name='idInvoice',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Id de comprobante'),
        ),
        migrations.AlterField(
            model_name='requirementsquotes',
            name='idProvider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier'),
        ),
        migrations.DeleteModel(
            name='Expenses',
        ),
    ]
