# Generated by Django 5.0.6 on 2025-07-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0006_requirements_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementitems',
            name='product',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Producto'),
        ),
    ]
