# Generated by Django 5.0.6 on 2025-07-10 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_alter_account_currency'),
        ('purchase', '0007_requirementitems_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirements',
            name='idTin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuentas.tin'),
        ),
        migrations.AlterField(
            model_name='requirements',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripción'),
        ),
    ]
