# Generated by Django 5.0.6 on 2025-07-10 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0008_requirements_idtin_alter_requirements_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirements',
            name='isPettyCash',
            field=models.BooleanField(default=False, verbose_name='Es caja chica?'),
        ),
    ]
