# Generated by Django 5.0.6 on 2025-07-12 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0009_requirements_ispettycash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirements',
            name='area',
            field=models.CharField(blank=True, choices=[('0', 'Administrador'), ('1', 'Compras'), ('2', 'Ventas'), ('3', 'Producción'), ('4', 'Gerencia'), ('5', 'Logística'), ('6', 'Recursos humanos'), ('7', 'Consultor externo'), ('8', 'Contabilidad'), ('9', 'TI')], max_length=1, null=True, verbose_name='Area de compañia'),
        ),
    ]
