# Generated by Django 5.0.6 on 2025-07-12 11:27

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0010_alter_requirements_area'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirements',
            name='area',
        ),
        migrations.RemoveField(
            model_name='requirements',
            name='idTin',
        ),
        migrations.RemoveField(
            model_name='requirements',
            name='isPettyCash',
        ),
        migrations.CreateModel(
            name='PettyCash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripción')),
                ('idPetitioner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PettyCash_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Caja chica',
                'verbose_name_plural': 'Todo caja chica',
            },
        ),
    ]
