# Generated by Django 5.0.6 on 2025-07-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0012_pettycashitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='pettycash',
            name='totalPrice',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Precio total'),
        ),
        migrations.AddField(
            model_name='requirements',
            name='totalPrice',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Precio total'),
        ),
    ]
