# Generated by Django 5.0.6 on 2025-07-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0013_pettycash_totalprice_requirements_totalprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirementitems',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Precio unitario'),
        ),
    ]
