# Generated by Django 5.0.6 on 2025-07-12 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0014_alter_requirementitems_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirementitems',
            name='currency',
        ),
        migrations.AddField(
            model_name='requirements',
            name='currency',
            field=models.CharField(blank=True, choices=[('0', 'PEN'), ('1', 'USD'), ('2', 'EUR')], max_length=1, null=True, verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='requesttracking',
            name='area',
            field=models.CharField(blank=True, choices=[('0', 'Usuario'), ('1', 'Area Manager'), ('2', 'Gerencia'), ('3', 'Compras'), ('4', 'Contabilidad'), ('5', 'Finanzas')], max_length=1, null=True, verbose_name='Area de seguimiento'),
        ),
    ]
