# Generated by Django 5.0.6 on 2025-07-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0015_remove_requirementitems_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pettycash',
            name='currency',
            field=models.CharField(blank=True, choices=[('0', 'PEN'), ('1', 'USD'), ('2', 'EUR')], max_length=1, null=True, verbose_name='Moneda'),
        ),
    ]
