# Generated by Django 5.0.6 on 2025-07-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0017_alter_pettycashitems_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesttracking',
            name='area',
            field=models.CharField(blank=True, choices=[('0', 'Usuario'), ('10', 'Area Manager'), ('4', 'Gerencia'), ('1', 'Compras'), ('8', 'Contabilidad'), ('5', 'Finanzas')], max_length=2, null=True, verbose_name='Area de seguimiento'),
        ),
    ]
