# Generated by Django 5.0.6 on 2025-07-31 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0018_alter_requesttracking_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirements',
            name='isPurchaseOrder',
            field=models.BooleanField(default=False, verbose_name='Es orden de compra?'),
        ),
    ]
