# Generated by Django 5.0.6 on 2025-08-05 11:53

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_alter_account_currency'),
        ('purchase', '0019_requirements_ispurchaseorder'),
        ('stakeholders', '0002_alter_supplier_contact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirementsinvoice',
            name='typeInvoice',
            field=models.CharField(blank=True, choices=[('0', 'Factura'), ('1', 'RHE'), ('2', 'Doc del exterior'), ('3', 'Impuesto'), ('4', 'Planilla'), ('5', 'Nota de credito'), ('7', 'Diario'), ('8', 'DUA'), ('9', 'Boleto Aéreo'), ('10', 'Liquidacion'), ('12', 'Otros'), ('13', 'Boleta de venta')], max_length=2, null=True, verbose_name='Tipo de Doc. Emisor'),
        ),
        migrations.CreateModel(
            name='PurchaseOrderInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('typeInvoice', models.CharField(blank=True, choices=[('0', 'Factura'), ('1', 'RHE'), ('2', 'Doc del exterior'), ('3', 'Impuesto'), ('4', 'Planilla'), ('5', 'Nota de credito'), ('7', 'Diario'), ('8', 'DUA'), ('9', 'Boleto Aéreo'), ('10', 'Liquidacion'), ('12', 'Otros'), ('13', 'Boleta de venta')], max_length=2, null=True, verbose_name='Tipo de Doc. Emisor')),
                ('doc_status', models.CharField(blank=True, choices=[('0', 'No Anulado'), ('1', 'Anulado'), ('2', 'Revertido')], max_length=1, null=True, verbose_name='Estado Doc. Emitido')),
                ('typeCurrency', models.CharField(blank=True, choices=[('0', 'PEN'), ('1', 'USD'), ('2', 'EUR')], max_length=1, null=True, verbose_name='Moneda de Operación')),
                ('month_dec', models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], null=True, verbose_name='Mes de declaración')),
                ('year_dec', models.PositiveIntegerField(blank=True, null=True, verbose_name='Año de declaración')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Fecha de emisión')),
                ('detraction', models.CharField(choices=[('0', 'No requiere'), ('1', 'Pendiente'), ('2', 'Completado')], default='0', max_length=1, verbose_name='Detracción - Factura')),
                ('shippingGuide', models.CharField(choices=[('0', 'No requiere'), ('1', 'Pendiente'), ('2', 'Completado')], default='0', max_length=1, verbose_name='Guia de remisión - Factura')),
                ('retention', models.CharField(choices=[('0', 'No requiere'), ('1', 'Pendiente'), ('2', 'Completado')], default='0', max_length=1, verbose_name='Retención - RHE')),
                ('annotation', models.CharField(blank=True, choices=[('0', 'anticipo'), ('1', 'pago final'), ('2', 'total')], max_length=2, null=True, verbose_name='Anotaciones')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('shortDescription', models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripción corta')),
                ('declareFlag', models.BooleanField(default=True, verbose_name='Declaracion?')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto bruto')),
                ('incomeTax', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Impuesto')),
                ('netAmount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto neto')),
                ('pendingNetPayment', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto Neto Pendiente de Pago')),
                ('equivalentAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto equivalente')),
                ('amountReconcilied', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto conciliado')),
                ('idInvoice', models.CharField(blank=True, max_length=50, null=True, verbose_name='Id de comprobante')),
                ('xml_file', models.FileField(blank=True, null=True, upload_to='purchaseDocs_xlms/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='requirementsInvoice_pdfs/')),
                ('idRequirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase.requirements')),
                ('idSupplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stakeholders.supplier')),
                ('idTin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuentas.tin')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchaseOrderInvoice_user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Invoice de ordene de compra',
                'verbose_name_plural': 'Invoices de ordenes de compras',
                'ordering': ['created'],
            },
        ),
    ]
