# Generated by Django 5.0.6 on 2025-08-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0020_alter_requirementsinvoice_typeinvoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesttracking',
            name='status',
            field=models.CharField(blank=True, choices=[('0', 'Creado'), ('1', 'Recibido'), ('2', 'Aprobado'), ('3', 'Rechazado'), ('4', 'Observado'), ('5', 'Solicitado'), ('6', 'Enviado a proveedores'), ('7', 'Cotizado por proveedores'), ('8', 'Parcailmente recepcionado'), ('9', 'Recepción total'), ('10', 'Facturado'), ('10', 'Pago parcial'), ('11', 'Pagol total'), ('12', 'Completado')], max_length=2, null=True, verbose_name='Estado de orden'),
        ),
    ]
