# Generated by Django 5.0.6 on 2025-08-13 07:58

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0021_alter_requesttracking_status'),
        ('stakeholders', '0002_alter_supplier_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteSuppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Mensaje')),
                ('idProvider', models.ManyToManyField(to='stakeholders.supplier')),
                ('idRequirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase.requirements')),
            ],
            options={
                'verbose_name': 'Envio de cotizacion',
                'verbose_name_plural': 'Envio de cotizacion a proveedores',
                'ordering': ['created'],
            },
        ),
    ]
