# Generated by Django 5.0.6 on 2025-08-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0022_quotesuppliers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirementsquotes',
            name='idQuote',
        ),
        migrations.AddField(
            model_name='requirementsquotes',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto bruto'),
        ),
        migrations.AddField(
            model_name='requirementsquotes',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de emisión'),
        ),
        migrations.AddField(
            model_name='requirementsquotes',
            name='expireDate',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de expiración'),
        ),
        migrations.AddField(
            model_name='requirementsquotes',
            name='incomeTax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Impuesto'),
        ),
        migrations.AddField(
            model_name='requirementsquotes',
            name='initialAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto inicial'),
        ),
        migrations.AddField(
            model_name='requirementsquotes',
            name='netAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto neto'),
        ),
        migrations.AddField(
            model_name='requirementsquotes',
            name='shortDescription',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripción corta'),
        ),
        migrations.AddField(
            model_name='requirementsquotes',
            name='typeCurrency',
            field=models.CharField(blank=True, choices=[('0', 'PEN'), ('1', 'USD'), ('2', 'EUR')], max_length=1, null=True, verbose_name='Moneda de Operación'),
        ),
    ]
