# Generated by Django 5.0.6 on 2025-08-14 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0023_remove_requirementsquotes_idquote_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requirementsquotes',
            old_name='idProvider',
            new_name='idSupplier',
        ),
    ]
