# Generated by Django 5.0.6 on 2025-08-15 12:09

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0024_rename_idprovider_requirementsquotes_idsupplier'),
        ('stakeholders', '0002_alter_supplier_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderVouchers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Fecha de emisión')),
                ('typeCurrency', models.CharField(blank=True, choices=[('0', 'PEN'), ('1', 'USD'), ('2', 'EUR')], max_length=1, null=True, verbose_name='Moneda de Operación')),
                ('shortDescription', models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripción corta')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto bruto')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='PurchaseOrderVouchers_pdfs/')),
                ('idRequirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase.requirements')),
                ('idSupplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stakeholders.supplier')),
            ],
            options={
                'verbose_name': 'Voucher de orden de compra',
                'verbose_name_plural': 'Vouchers de ordenes de compra',
                'ordering': ['created'],
            },
        ),
    ]
