# Generated by Django 5.0.6 on 2025-09-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0025_purchaseordervouchers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesttracking',
            name='area',
            field=models.CharField(blank=True, choices=[('1', 'Comercial'), ('2', 'Finanzas'), ('3', 'Producción'), ('4', 'Gerencia'), ('5', 'Logistica'), ('6', 'Recursos humanos')], max_length=2, null=True, verbose_name='Area de seguimiento'),
        ),
    ]
