# Generated by Django 5.0.6 on 2025-09-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0026_alter_requesttracking_area'),
        ('stakeholders', '0005_alter_supplier_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotesuppliers',
            name='idProvider',
            field=models.ManyToManyField(related_name='quote_supplier', to='stakeholders.supplier'),
        ),
    ]
