# Generated by Django 5.0.6 on 2025-09-10 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0027_alter_quotesuppliers_idprovider'),
        ('sales', '0010_trafos_idcontainer_alter_incomes_idclient'),
        ('transport', '0002_remove_container_message_container_shortdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementitems',
            name='idContainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirementItems_container', to='transport.container'),
        ),
        migrations.AddField(
            model_name='requirementitems',
            name='idTrafos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirementItems_trafos', to='sales.trafos'),
        ),
        migrations.AddField(
            model_name='requirementitems',
            name='type',
            field=models.CharField(blank=True, choices=[('0', 'Articulo'), ('1', 'Transformador'), ('2', 'Contenedor'), ('3', 'Aduana')], max_length=1, null=True, verbose_name='Tipo'),
        ),
    ]
