# Generated by Django 5.0.6 on 2025-09-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0028_requirementitems_idcontainer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirementitems',
            name='idContainer',
        ),
        migrations.AlterField(
            model_name='requirementitems',
            name='type',
            field=models.CharField(blank=True, choices=[('0', 'Articulo'), ('1', 'Transformador'), ('2', 'Contenedor'), ('3', 'Aduana')], default='0', max_length=1, null=True, verbose_name='Tipo'),
        ),
    ]
