# Generated by Django 5.0.6 on 2025-09-23 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCTION', '0002_alter_trafos_options_trafos_iduser'),
        ('purchase', '0029_remove_requirementitems_idcontainer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirementitems',
            name='idTrafos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirementItems_trafos', to='PRODUCTION.trafos'),
        ),
    ]
