# Generated by Django 5.0.6 on 2025-12-04 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0030_alter_requirementitems_idtrafos'),
        ('sales', '0026_items_idcontainer_alter_trafo_hv_alter_trafo_lv_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirementitems',
            name='idTrafos',
        ),
        migrations.AddField(
            model_name='requirementitems',
            name='idTrafo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trafo_requirement', to='sales.trafo'),
        ),
    ]
