# Generated by Django 5.0.6 on 2026-03-26 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0031_remove_requirementitems_idtrafos_and_more'),
        ('sales', '0040_paymentallocation_cost_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementitems',
            name='idItem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_items', to='sales.items', verbose_name='Item de cotización vinculado'),
        ),
        migrations.AlterField(
            model_name='requesttracking',
            name='status',
            field=models.CharField(blank=True, choices=[('0', 'Creado'), ('1', 'Recibido'), ('2', 'Aprobado'), ('3', 'Rechazado'), ('4', 'Observado'), ('5', 'Solicitado'), ('6', 'Enviado a proveedores'), ('7', 'Cotizado por proveedores'), ('8', 'Parcailmente recepcionado'), ('9', 'Recepción total'), ('10', 'Facturado'), ('11', 'Pago parcial'), ('12', 'Pago total'), ('13', 'Completado')], max_length=2, null=True, verbose_name='Estado de orden'),
        ),
    ]
