# Generated by Django 5.0.6 on 2026-03-26 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0032_add_iditem_to_requirementitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementitems',
            name='idSupplierQuote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quoted_items', to='purchase.requirementsquotes', verbose_name='Cotización proveedor asignada'),
        ),
        migrations.AddField(
            model_name='requirementsquotes',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Aprobada'),
        ),
    ]
