# Generated by Django 5.0.6 on 2025-07-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='status',
            field=models.CharField(blank=True, choices=[('0', 'Activo'), ('1', 'No activo')], default='0', max_length=1, null=True, verbose_name='Estado Proveedor'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Apellidos'),
        ),
    ]
