# Generated by Django 5.0.6 on 2024-07-10 13:21

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actividades', '0001_initial'),
        ('clientes', '0001_initial'),
        ('personal', '0001_initial'),
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('idOrder', models.IntegerField(blank=True, null=True, verbose_name='Id Orders')),
                ('dateChange', models.DateTimeField(verbose_name='Fecha')),
                ('orderState', models.CharField(choices=[('0', 'Creado'), ('1', 'Fabricado'), ('2', 'Enviado'), ('3', 'Completado'), ('4', 'Cancelado')], max_length=1, verbose_name='Estado de orden')),
            ],
            options={
                'verbose_name': 'pedido seguimiento ',
                'verbose_name_plural': 'pedidos seguimientos ',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchaseOrder', models.CharField(blank=True, max_length=100, null=True, verbose_name='Concepto de compra')),
                ('numberUnits', models.PositiveIntegerField(blank=True, null=True, verbose_name='Numero de unidades')),
                ('estimatedPrice', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio estimado')),
                ('currency', models.CharField(blank=True, choices=[('0', 'Soles'), ('1', 'Dolares')], max_length=1, verbose_name='Tipo de moneda')),
                ('IdOrderState', models.CharField(blank=True, default='0', max_length=25, null=True, verbose_name='Estado de orden')),
            ],
            options={
                'verbose_name': 'compra',
                'verbose_name_plural': 'compras',
            },
        ),
        migrations.CreateModel(
            name='PurchaseTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('idOrder', models.CharField(blank=True, max_length=20, null=True, verbose_name='Id Orders')),
                ('dateChange', models.DateTimeField(auto_now=True, verbose_name='Fecha')),
                ('orderState', models.CharField(choices=[('0', 'Solicitado'), ('1', 'Aprobado'), ('2', 'Denegado'), ('3', 'Completado'), ('4', 'Cancelado')], max_length=1, verbose_name='Estado de orden')),
            ],
            options={
                'verbose_name': 'compra seguimientos',
                'verbose_name_plural': 'compras seguimiento',
            },
        ),
        migrations.CreateModel(
            name='RequestTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('idOrder', models.IntegerField(blank=True, null=True, verbose_name='Id Requerimiento')),
                ('dateChange', models.DateTimeField(verbose_name='Fecha y hora')),
                ('orderState', models.CharField(choices=[('0', 'solicitado'), ('1', 'aprobado'), ('2', 'conciliado'), ('3', 'cancelado')], max_length=1, verbose_name='Estado de orden')),
                ('amountAssigned', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto asignado')),
            ],
            options={
                'verbose_name': 'seguimiento de requerimiento',
                'verbose_name_plural': 'seguimientos de requerimientos',
            },
        ),
        migrations.CreateModel(
            name='ServiceOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('serviceOrder', models.CharField(blank=True, max_length=100, null=True, verbose_name='Concepto de servicio')),
                ('estimatedPrice', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio estimado')),
                ('currency', models.CharField(blank=True, choices=[('0', 'Soles'), ('1', 'Dolares')], max_length=1, verbose_name='Tipo de moneda')),
                ('IdOrderState', models.CharField(blank=True, default='0', max_length=25, null=True, verbose_name='Estado de orden')),
            ],
            options={
                'verbose_name': 'servicio',
                'verbose_name_plural': 'servicios',
            },
        ),
        migrations.CreateModel(
            name='ServiceTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('idOrder', models.CharField(blank=True, max_length=20, null=True, verbose_name='Id Orders')),
                ('dateChange', models.DateTimeField(auto_now=True, verbose_name='Fecha')),
                ('orderState', models.CharField(choices=[('0', 'Solicitado'), ('1', 'Aprobado'), ('2', 'Denegado'), ('3', 'Completado'), ('4', 'Cancelado')], max_length=1, verbose_name='Estado de orden')),
            ],
            options={
                'verbose_name': 'servicio seguimiento',
                'verbose_name_plural': 'servicios seguimientos',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idOrder', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Id orden')),
                ('dateOrder', models.DateField(verbose_name='Fecha de pedido')),
                ('deadline', models.DateField(verbose_name='Fecha de entrega')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('numberUnits', models.PositiveIntegerField(blank=True, null=True, verbose_name='Numero de unidades')),
                ('IdOrderState', models.CharField(blank=True, default='0', max_length=25, null=True, verbose_name='Estado de orden')),
                ('idAttendant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personal.workers')),
                ('idClient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('idTransformer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='producto.transformer')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('requirementName', models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Nombre de requerimiento')),
                ('numbers', models.PositiveIntegerField(blank=True, null=True, verbose_name='Numero de unidades')),
                ('amountRequested', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto solicitado')),
                ('amountAssigned', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto asignado')),
                ('amountReconcilied', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto conciliado')),
                ('paymentType', models.CharField(blank=True, choices=[('0', 'compras'), ('1', 'servicio'), ('2', 'proveedor'), ('3', 'impuestos'), ('4', 'caja chica'), ('5', 'comisiones'), ('6', 'proyecto'), ('7', 'planilla'), ('8', 'operaciones'), ('9', 'multas'), ('10', 'personal'), ('11', 'transferencias internas'), ('12', 'agente aduanas'), ('13', 'prestamo')], max_length=2, null=True, verbose_name='Categoria de pago')),
                ('currencyType', models.CharField(blank=True, choices=[('0', 'soles'), ('1', 'dolares'), ('2', 'euros')], max_length=2, null=True, verbose_name='Moneda')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Fecha de entrega')),
                ('tagOrder', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('0', 'solicitado'), ('1', 'aceptado'), ('2', 'denegado')], default='0', max_length=1, null=True, verbose_name='Estado'), blank=True, null=True, size=None)),
                ('idCommissions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actividades.commissions')),
            ],
            options={
                'verbose_name': 'Requerimiento de pago',
                'verbose_name_plural': 'Requerimientos de pagos',
            },
        ),
    ]
