# Generated by Django 5.0.6 on 2024-12-19 10:54

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actividades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('listName', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de lista')),
                ('tag1', models.CharField(blank=True, choices=[('0', 'Solicitado'), ('1', 'Atendido'), ('2', 'Denegado'), ('3', 'Observado'), ('4', 'Creado')], default='0', max_length=1, null=True, verbose_name='Adquisiciones')),
                ('dt1', models.DateTimeField(blank=True, null=True, verbose_name='F. adquisiciones')),
                ('tag2', models.CharField(blank=True, choices=[('0', 'Solicitado'), ('1', 'Atendido'), ('2', 'Denegado'), ('3', 'Observado'), ('4', 'Creado')], default='4', max_length=1, null=True, verbose_name='Contabilidad')),
                ('dt2', models.DateTimeField(blank=True, null=True, verbose_name='F. contabilidad ')),
                ('tag3', models.CharField(blank=True, choices=[('0', 'Solicitado'), ('1', 'Atendido'), ('2', 'Denegado'), ('3', 'Observado'), ('4', 'Creado')], default='4', max_length=1, null=True, verbose_name='Finanzas')),
                ('dt3', models.DateTimeField(blank=True, null=True, verbose_name='F. gereFinanzasncia')),
                ('tag4', models.CharField(blank=True, choices=[('0', 'Solicitado'), ('1', 'Atendido'), ('2', 'Denegado'), ('3', 'Observado'), ('4', 'Creado')], default='4', max_length=1, null=True, verbose_name='Gerencia')),
                ('dt4', models.DateTimeField(blank=True, null=True, verbose_name='F. Gerencia')),
            ],
            options={
                'verbose_name': 'Lista de solicitudes',
                'verbose_name_plural': 'Listas de solicitudes',
            },
        ),
        migrations.CreateModel(
            name='RequestTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('idOrder', models.IntegerField(blank=True, null=True, verbose_name='Id Requerimiento')),
                ('dateChange', models.DateTimeField(verbose_name='Fecha y hora')),
                ('orderState', models.CharField(choices=[('0', 'solicitado'), ('1', 'aprobado'), ('2', 'conciliado'), ('3', 'cancelado')], max_length=1, verbose_name='Estado de orden')),
                ('amountAssigned', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto asignado')),
            ],
            options={
                'verbose_name': 'seguimiento de requerimiento',
                'verbose_name_plural': 'seguimientos de requerimientos',
            },
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('requirementName', models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Nombre de requerimiento')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Cantidad')),
                ('amountRequested', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto solicitado')),
                ('amountAssigned', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto asignado')),
                ('currencyType', models.CharField(blank=True, choices=[('0', 'S/.'), ('1', '$'), ('2', '€')], max_length=1, null=True, verbose_name='Moneda')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Fecha de entrega')),
                ('typeRequest', models.CharField(blank=True, choices=[('0', 'simple'), ('1', 'contabilidad')], max_length=2, null=True, verbose_name='Tipo de solicitud')),
                ('dt0', models.DateTimeField(auto_now_add=True, verbose_name='F. solicitada')),
                ('tag1', models.CharField(blank=True, choices=[('0', 'espera'), ('1', 'aceptado'), ('2', 'denegado'), ('3', 'observado'), ('4', 'creado')], default='0', max_length=1, null=True, verbose_name='Ap adquisiciones')),
                ('dt1', models.DateTimeField(blank=True, null=True, verbose_name='F. adquisiciones')),
                ('tag2', models.CharField(blank=True, choices=[('0', 'espera'), ('1', 'aceptado'), ('2', 'denegado'), ('3', 'observado'), ('4', 'creado')], default='4', max_length=1, null=True, verbose_name='Ap contabilidad')),
                ('dt2', models.DateTimeField(blank=True, null=True, verbose_name='F. contabilidad ')),
                ('tag3', models.CharField(blank=True, choices=[('0', 'espera'), ('1', 'aceptado'), ('2', 'denegado'), ('3', 'observado'), ('4', 'creado')], default='4', max_length=1, null=True, verbose_name='Ap finanzas')),
                ('dt3', models.DateTimeField(blank=True, null=True, verbose_name='F. finanzas')),
                ('tag4', models.CharField(blank=True, choices=[('0', 'espera'), ('1', 'aceptado'), ('2', 'denegado'), ('3', 'observado'), ('4', 'creado')], default='4', max_length=1, null=True, verbose_name='Ap desembolsado')),
                ('dt4', models.DateTimeField(blank=True, null=True, verbose_name='F. desembolso')),
                ('observations', models.CharField(blank=True, default='Ninguna', max_length=100, null=True, verbose_name='Observaciones')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='cotizaciones_pdfs/')),
                ('idCommissions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actividades.commissions')),
            ],
            options={
                'verbose_name': 'Requerimiento de pago',
                'verbose_name_plural': 'Requerimientos de pagos',
            },
        ),
    ]
