# Generated by Django 5.0.6 on 2024-07-10 22:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_alter_paymentrequest_tagorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='tagOrder',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('0', 'solicitado'), ('1', 'aceptado'), ('2', 'denegado')], default='0', max_length=1, null=True), blank=True, default=[], null=True, size=None),
        ),
    ]
