# Generated by Django 5.0.6 on 2024-07-12 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_remove_paymentrequest_amountreconcilied_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='tag1',
            field=models.CharField(blank=True, choices=[('0', 'espera'), ('1', 'aceptado'), ('2', 'denegado'), ('3', 'observado')], default='0', max_length=1, null=True, verbose_name='Ap adquisiciones'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='tag2',
            field=models.CharField(blank=True, choices=[('0', 'espera'), ('1', 'aceptado'), ('2', 'denegado'), ('3', 'observado')], default='0', max_length=1, null=True, verbose_name='Ap contabilidad'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='tag3',
            field=models.CharField(blank=True, choices=[('0', 'espera'), ('1', 'aceptado'), ('2', 'denegado'), ('3', 'observado')], default='0', max_length=1, null=True, verbose_name='Ap finanzas'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='tag4',
            field=models.CharField(blank=True, choices=[('0', 'espera'), ('1', 'aceptado'), ('2', 'denegado'), ('3', 'observado')], default='0', max_length=1, null=True, verbose_name='Ap desembolsado'),
        ),
    ]
