# Generated by Django 5.0.6 on 2024-07-12 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_paymentrequest_typerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='typeRequest',
            field=models.CharField(blank=True, choices=[('0', 'simple'), ('1', 'contabilidad')], max_length=2, null=True, verbose_name='Tipo de solicitud'),
        ),
    ]
