# Generated by Django 5.0.6 on 2024-07-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0009_alter_paymentrequest_observations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='idAttendant',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='idClient',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='idTransformer',
        ),
        migrations.RemoveField(
            model_name='purchaseorders',
            name='idOrders',
        ),
        migrations.RemoveField(
            model_name='serviceorders',
            name='idOrders',
        ),
        migrations.DeleteModel(
            name='OrderTracking',
        ),
        migrations.RemoveField(
            model_name='purchaseorders',
            name='idCommissions',
        ),
        migrations.RemoveField(
            model_name='purchaseorders',
            name='idProjects',
        ),
        migrations.RemoveField(
            model_name='purchaseorders',
            name='idWorker',
        ),
        migrations.DeleteModel(
            name='PurchaseTracking',
        ),
        migrations.RemoveField(
            model_name='serviceorders',
            name='idClient',
        ),
        migrations.RemoveField(
            model_name='serviceorders',
            name='idCommissions',
        ),
        migrations.RemoveField(
            model_name='serviceorders',
            name='idProjects',
        ),
        migrations.RemoveField(
            model_name='serviceorders',
            name='idWorker',
        ),
        migrations.DeleteModel(
            name='ServiceTracking',
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='tag1',
            field=models.CharField(blank=True, choices=[('0', 'espera'), ('1', 'aceptado'), ('2', 'denegado'), ('3', 'observado'), ('4', 'creado')], default='0', max_length=1, null=True, verbose_name='Ap adquisiciones'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='tag2',
            field=models.CharField(blank=True, choices=[('0', 'espera'), ('1', 'aceptado'), ('2', 'denegado'), ('3', 'observado'), ('4', 'creado')], default='4', max_length=1, null=True, verbose_name='Ap contabilidad'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='tag3',
            field=models.CharField(blank=True, choices=[('0', 'espera'), ('1', 'aceptado'), ('2', 'denegado'), ('3', 'observado'), ('4', 'creado')], default='4', max_length=1, null=True, verbose_name='Ap finanzas'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='tag4',
            field=models.CharField(blank=True, choices=[('0', 'espera'), ('1', 'aceptado'), ('2', 'denegado'), ('3', 'observado'), ('4', 'creado')], default='4', max_length=1, null=True, verbose_name='Ap desembolsado'),
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.DeleteModel(
            name='PurchaseOrders',
        ),
        migrations.DeleteModel(
            name='ServiceOrders',
        ),
    ]
