# Generated by Django 5.0.6 on 2024-07-14 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0010_remove_orders_idattendant_remove_orders_idclient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='pdf_file',
            field=models.FileField(null=True, upload_to='cotizaciones_pdfs/'),
        ),
    ]
