# Generated by Django 5.0.6 on 2024-07-14 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0011_paymentrequest_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='cotizaciones_pdfs/'),
        ),
    ]
