# Generated by Django 5.0.6 on 2024-12-18 21:09

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0033_expensesubcategories_incomesubcategories_and_more'),
        ('pedidos', '0012_alter_paymentrequest_pdf_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='currencyType',
            field=models.CharField(blank=True, choices=[('0', 'S/.'), ('1', '$'), ('2', '€')], max_length=1, null=True, verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='paymentType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movimientos.expensesubcategories'),
        ),
        migrations.CreateModel(
            name='RequestList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('listName', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de lista')),
                ('tag1', models.CharField(blank=True, choices=[('0', 'Solicitado'), ('1', 'Atendido'), ('2', 'Denegado'), ('3', 'Observado'), ('4', 'Creado')], default='0', max_length=1, null=True, verbose_name='Adquisiciones')),
                ('dt1', models.DateTimeField(blank=True, null=True, verbose_name='F. adquisiciones')),
                ('tag2', models.CharField(blank=True, choices=[('0', 'Solicitado'), ('1', 'Atendido'), ('2', 'Denegado'), ('3', 'Observado'), ('4', 'Creado')], default='4', max_length=1, null=True, verbose_name='Contabilidad')),
                ('dt2', models.DateTimeField(blank=True, null=True, verbose_name='F. contabilidad ')),
                ('tag3', models.CharField(blank=True, choices=[('0', 'Solicitado'), ('1', 'Atendido'), ('2', 'Denegado'), ('3', 'Observado'), ('4', 'Creado')], default='4', max_length=1, null=True, verbose_name='Finanzas')),
                ('dt3', models.DateTimeField(blank=True, null=True, verbose_name='F. gereFinanzasncia')),
                ('tag4', models.CharField(blank=True, choices=[('0', 'Solicitado'), ('1', 'Atendido'), ('2', 'Denegado'), ('3', 'Observado'), ('4', 'Creado')], default='4', max_length=1, null=True, verbose_name='Gerencia')),
                ('dt4', models.DateTimeField(blank=True, null=True, verbose_name='F. Gerencia')),
                ('idPetitioner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lista_solicitante', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lista de solicitudes',
                'verbose_name_plural': 'Listas de solicitudes',
            },
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='idList',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lista', to='pedidos.requestlist'),
        ),
    ]
