# Generated by Django 5.0.6 on 2024-12-19 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0034_alter_expensesubcategories_category'),
        ('pedidos', '0013_alter_paymentrequest_currencytype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='paymentType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EsubCategory', to='movimientos.expensesubcategories'),
        ),
    ]
