# Generated by Django 5.0.6 on 2024-12-15 14:41

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0013_paymentrequest_idlist_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('observations', models.CharField(blank=True, default='Ninguna', max_length=100, null=True, verbose_name='Nombre de lista')),
                ('tag1', models.CharField(blank=True, choices=[('0', 'espera'), ('1', 'Atendido'), ('2', 'denegado'), ('3', 'observado'), ('4', 'creado')], default='0', max_length=1, null=True, verbose_name='Ap adquisiciones')),
                ('dt1', models.DateTimeField(blank=True, null=True, verbose_name='F. adquisiciones')),
                ('tag2', models.CharField(blank=True, choices=[('0', 'espera'), ('1', 'Atendido'), ('2', 'denegado'), ('3', 'observado'), ('4', 'creado')], default='4', max_length=1, null=True, verbose_name='Ap contabilidad')),
                ('dt2', models.DateTimeField(blank=True, null=True, verbose_name='F. contabilidad ')),
                ('tag3', models.CharField(blank=True, choices=[('0', 'espera'), ('1', 'Atendido'), ('2', 'denegado'), ('3', 'observado'), ('4', 'creado')], default='4', max_length=1, null=True, verbose_name='Ap finanzas')),
                ('dt3', models.DateTimeField(blank=True, null=True, verbose_name='F. finanzas')),
                ('tag4', models.CharField(blank=True, choices=[('0', 'espera'), ('1', 'Atendido'), ('2', 'denegado'), ('3', 'observado'), ('4', 'creado')], default='4', max_length=1, null=True, verbose_name='Ap desembolsado')),
                ('dt4', models.DateTimeField(blank=True, null=True, verbose_name='F. desembolso')),
                ('idPetitioner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lista_solicitante', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lista de solicitudes',
                'verbose_name_plural': 'Listas de solicitudes',
            },
        ),
    ]
