# Generated by Django 5.0.6 on 2024-12-15 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0014_requestlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestlist',
            old_name='observations',
            new_name='listName',
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='idList',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.requestlist'),
        ),
        migrations.AlterField(
            model_name='requestlist',
            name='dt3',
            field=models.DateTimeField(blank=True, null=True, verbose_name='F. gerencia'),
        ),
        migrations.AlterField(
            model_name='requestlist',
            name='dt4',
            field=models.DateTimeField(blank=True, null=True, verbose_name='F. Finanzas'),
        ),
        migrations.AlterField(
            model_name='requestlist',
            name='tag1',
            field=models.CharField(blank=True, choices=[('0', 'Creado'), ('1', 'Atendido'), ('2', 'Denegado'), ('3', 'Observado')], default='0', max_length=1, null=True, verbose_name='Ap adquisiciones'),
        ),
        migrations.AlterField(
            model_name='requestlist',
            name='tag2',
            field=models.CharField(blank=True, choices=[('0', 'Creado'), ('1', 'Atendido'), ('2', 'Denegado'), ('3', 'Observado')], default='4', max_length=1, null=True, verbose_name='Ap contabilidad'),
        ),
        migrations.AlterField(
            model_name='requestlist',
            name='tag3',
            field=models.CharField(blank=True, choices=[('0', 'Creado'), ('1', 'Atendido'), ('2', 'Denegado'), ('3', 'Observado')], default='4', max_length=1, null=True, verbose_name='Ap gerencia'),
        ),
        migrations.AlterField(
            model_name='requestlist',
            name='tag4',
            field=models.CharField(blank=True, choices=[('0', 'Creado'), ('1', 'Atendido'), ('2', 'Denegado'), ('3', 'Observado')], default='4', max_length=1, null=True, verbose_name='Ap desembolsado'),
        ),
    ]
