# Generated by Django 5.0.6 on 2024-12-16 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0015_rename_observations_requestlist_listname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlist',
            name='listName',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de lista'),
        ),
    ]
