# Generated by Django 5.0.6 on 2024-12-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0016_alter_requestlist_listname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlist',
            name='tag1',
            field=models.CharField(blank=True, choices=[('0', 'Solicitado'), ('1', 'Atendido'), ('2', 'Denegado'), ('3', 'Observado'), ('4', 'Creado')], default='0', max_length=1, null=True, verbose_name='Ap adquisiciones'),
        ),
        migrations.AlterField(
            model_name='requestlist',
            name='tag2',
            field=models.CharField(blank=True, choices=[('0', 'Solicitado'), ('1', 'Atendido'), ('2', 'Denegado'), ('3', 'Observado'), ('4', 'Creado')], default='4', max_length=1, null=True, verbose_name='Ap contabilidad'),
        ),
        migrations.AlterField(
            model_name='requestlist',
            name='tag3',
            field=models.CharField(blank=True, choices=[('0', 'Solicitado'), ('1', 'Atendido'), ('2', 'Denegado'), ('3', 'Observado'), ('4', 'Creado')], default='4', max_length=1, null=True, verbose_name='Ap gerencia'),
        ),
        migrations.AlterField(
            model_name='requestlist',
            name='tag4',
            field=models.CharField(blank=True, choices=[('0', 'Solicitado'), ('1', 'Atendido'), ('2', 'Denegado'), ('3', 'Observado'), ('4', 'Creado')], default='4', max_length=1, null=True, verbose_name='Ap desembolsado'),
        ),
    ]
