# Generated by Django 5.0.6 on 2024-12-17 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0017_alter_requestlist_tag1_alter_requestlist_tag2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='idList',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lista', to='pedidos.requestlist'),
        ),
        migrations.AlterField(
            model_name='requestlist',
            name='dt3',
            field=models.DateTimeField(blank=True, null=True, verbose_name='F. gereFinanzasncia'),
        ),
        migrations.AlterField(
            model_name='requestlist',
            name='dt4',
            field=models.DateTimeField(blank=True, null=True, verbose_name='F. Gerencia'),
        ),
        migrations.AlterField(
            model_name='requestlist',
            name='tag1',
            field=models.CharField(blank=True, choices=[('0', 'Solicitado'), ('1', 'Atendido'), ('2', 'Denegado'), ('3', 'Observado'), ('4', 'Creado')], default='0', max_length=1, null=True, verbose_name='Adquisiciones'),
        ),
        migrations.AlterField(
            model_name='requestlist',
            name='tag2',
            field=models.CharField(blank=True, choices=[('0', 'Solicitado'), ('1', 'Atendido'), ('2', 'Denegado'), ('3', 'Observado'), ('4', 'Creado')], default='4', max_length=1, null=True, verbose_name='Contabilidad'),
        ),
        migrations.AlterField(
            model_name='requestlist',
            name='tag3',
            field=models.CharField(blank=True, choices=[('0', 'Solicitado'), ('1', 'Atendido'), ('2', 'Denegado'), ('3', 'Observado'), ('4', 'Creado')], default='4', max_length=1, null=True, verbose_name='Finanzas'),
        ),
        migrations.AlterField(
            model_name='requestlist',
            name='tag4',
            field=models.CharField(blank=True, choices=[('0', 'Solicitado'), ('1', 'Atendido'), ('2', 'Denegado'), ('3', 'Observado'), ('4', 'Creado')], default='4', max_length=1, null=True, verbose_name='Gerencia'),
        ),
    ]
