# Generated by Django 5.0.6 on 2024-12-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0018_alter_paymentrequest_idlist_alter_requestlist_dt3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
