# Generated by Django 5.0.6 on 2025-05-05 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientosBancarios', '0003_alter_bankmovements_equivalentamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankmovements',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='vouchers_pdfs/'),
        ),
        migrations.DeleteModel(
            name='BankVoucher',
        ),
    ]
