# Generated by Django 5.0.6 on 2025-05-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientosBancarios', '0005_remove_conciliation_amountreconcilied_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conciliation',
            name='amountEUR',
        ),
        migrations.RemoveField(
            model_name='conciliation',
            name='amountPEN',
        ),
        migrations.RemoveField(
            model_name='conciliation',
            name='amountUSD',
        ),
        migrations.AddField(
            model_name='conciliation',
            name='amountReconcilied',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto conciliado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conciliation',
            name='equivalentAmount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Monto equivalente'),
        ),
    ]
