# Generated by Django 5.0.6 on 2025-05-20 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimientosBancarios', '0006_remove_conciliation_amounteur_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankmovements',
            options={'ordering': ['date'], 'verbose_name': 'Movimiento bancario', 'verbose_name_plural': 'Movimientos bancarios'},
        ),
    ]
