# Generated by Django 5.0.6 on 2025-05-20 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimientosBancarios', '0007_alter_bankmovements_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conciliation',
            options={'ordering': ['created'], 'verbose_name': 'Conciliacion', 'verbose_name_plural': 'Conciliaciones'},
        ),
    ]
