# Generated by Django 5.0.6 on 2025-08-25 23:09

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        #('cuentas', '0004_remove_account_accountbalance_and_more'),
        ('documentos', '0001_initial'),
        #('stakeholders', '0003_bankaccountsclient_bankaccountssupplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseSubCategories',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nameSubCategoy', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nombre de subcategoria')),
                ('category', models.CharField(blank=True, choices=[('0', 'Producto'), ('1', 'Compras activos'), ('2', 'Fijos'), ('3', 'Variables'), ('4', 'Impuestos'), ('5', 'Cambio de moneda'), ('6', 'Deducciones'), ('7', 'Retiros'), ('8', 'Otros')], default='8', max_length=1, null=True, verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Categoria de gasto',
                'verbose_name_plural': 'Categorias de gastos',
            },
        ),
        migrations.CreateModel(
            name='IncomeSubCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nameSubCategoy', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre de subcategoria')),
            ],
            options={
                'verbose_name': 'Categoria de ingreso',
                'verbose_name_plural': 'Categorias de ingresos',
            },
        ),
        migrations.CreateModel(
            name='BankMovements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripción EEC')),
                ('transactionType', models.CharField(blank=True, choices=[('0', 'egreso'), ('1', 'ingreso')], max_length=1, verbose_name='Tipo de movimiento')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('equivalentAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto equivalente')),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='saldo')),
                ('amountReconcilied', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto conciliado')),
                ('opNumber', models.CharField(blank=True, max_length=15, null=True, verbose_name='Numero de operacion')),
                ('justification', models.CharField(blank=True, max_length=250, null=True, verbose_name='Justification')),
                ('conciliated', models.BooleanField(default=False, verbose_name='Conciliado?')),
                ('flagUpdate', models.BooleanField(default=False, verbose_name='Actualizado?')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='vouchers_pdfs/')),
                ('idAccount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finantiL_idAccount', to='cuentas.account')),
                ('originDestination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Finantial_originDestination', to='stakeholders.client')),
            ],
            options={
                'verbose_name': 'Movimiento bancario',
                'verbose_name_plural': 'Movimientos bancarios',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Conciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('type', models.CharField(choices=[('0', 'documento'), ('1', 'movimiento')], max_length=1, verbose_name='Tipo de conciliacion')),
                ('amountReconcilied', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto conciliado')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('equivalentAmount', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Monto equivalente')),
                ('idDoc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doc_conciliation', to='documentos.financialdocuments')),
                ('idMovArrival', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mov_destino', to='movimientosBancarios.bankmovements')),
                ('idMovOrigin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mov_origen', to='movimientosBancarios.bankmovements')),
            ],
            options={
                'verbose_name': 'Conciliacion',
                'verbose_name_plural': 'Conciliaciones',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='DocumentsUploaded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('fileName', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de archivo')),
                ('observations', models.CharField(blank=True, max_length=100, null=True, verbose_name='Observaciones')),
                ('idAccount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DocUpload_idAccount', to='cuentas.account')),
            ],
            options={
                'verbose_name': 'Documento subido',
                'verbose_name_plural': 'Documentos subidos',
            },
        ),
        migrations.AddField(
            model_name='bankmovements',
            name='idDoc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Finantial_uploadDoc', to='movimientosBancarios.documentsuploaded'),
        ),
        migrations.AddField(
            model_name='bankmovements',
            name='expenseSubCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movimientosBancarios.expensesubcategories'),
        ),
        migrations.AddField(
            model_name='bankmovements',
            name='incomeSubCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movimientosBancarios.incomesubcategories'),
        ),
    ]
