# Generated by Django 5.0.6 on 2025-08-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientosBancarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conciliation',
            name='type',
            field=models.CharField(choices=[('0', 'documento'), ('1', 'movimiento'), ('2', 'Com. Bancarias'), ('3', 'Impuestos')], max_length=1, verbose_name='Tipo de conciliacion'),
        ),
    ]
