# Generated by Django 5.0.6 on 2025-07-21 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clientContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phoneNumber', models.CharField(blank=True, null=True, verbose_name='Telefono')),
            ],
        ),
        migrations.CreateModel(
            name='supplierContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phoneNumber', models.CharField(blank=True, null=True, verbose_name='Telefono')),
            ],
        ),
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tradeName', models.CharField(blank=True, null=True, verbose_name='Razon Social')),
                ('numberIdClient', models.CharField(blank=True, null=True, unique=True, verbose_name='Número de Id de cliente')),
                ('typeDocument', models.CharField(blank=True, choices=[('0', 'RUC'), ('1', 'TIN'), ('2', 'DNI'), ('3', 'CE'), ('4', 'OTRO')], max_length=1, null=True, verbose_name='Tipo de documento')),
                ('location', models.CharField(blank=True, choices=[('0', 'nacional'), ('1', 'extrangero')], max_length=1, null=True, verbose_name='Por origen')),
                ('status', models.CharField(blank=True, choices=[('0', 'Activo'), ('1', 'No activo')], default='0', max_length=1, null=True, verbose_name='Estado Proveedor')),
                ('country', models.CharField(blank=True, null=True, verbose_name='País')),
                ('brandName', models.CharField(blank=True, null=True, verbose_name='Marca')),
                ('phoneNumber', models.CharField(blank=True, null=True, verbose_name='Telefono')),
                ('webPage', models.CharField(blank=True, null=True, verbose_name='Página Web')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stakeholders.clientcontact')),
            ],
            options={
                'ordering': ['tradeName'],
            },
        ),
        migrations.CreateModel(
            name='supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tradeName', models.CharField(blank=True, null=True, verbose_name='Razon Social')),
                ('numberIdSupplier', models.CharField(blank=True, null=True, unique=True, verbose_name='Numero de proveedor')),
                ('typeDocument', models.CharField(blank=True, choices=[('0', 'RUC'), ('1', 'TIN'), ('2', 'DNI'), ('3', 'CE'), ('4', 'OTRO')], max_length=1, null=True, verbose_name='Tipo de documento')),
                ('location', models.CharField(blank=True, choices=[('0', 'nacional'), ('1', 'extrangero')], max_length=1, null=True, verbose_name='Por origen')),
                ('status', models.CharField(blank=True, choices=[('0', 'Activo'), ('1', 'No activo')], default='0', max_length=1, null=True, verbose_name='Estado Proveedor')),
                ('country', models.CharField(blank=True, null=True, verbose_name='País')),
                ('brandName', models.CharField(blank=True, null=True, verbose_name='Marca')),
                ('phoneNumber', models.CharField(blank=True, null=True, verbose_name='Telefono')),
                ('webPage', models.CharField(blank=True, null=True, verbose_name='Página Web')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stakeholders.suppliercontact')),
            ],
            options={
                'ordering': ['tradeName'],
            },
        ),
    ]
