# Generated by Django 5.0.6 on 2025-07-21 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='contact',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_contact', to='stakeholders.suppliercontact'),
        ),
    ]
