# Generated by Django 5.0.6 on 2025-08-25 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholders', '0002_alter_supplier_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='bankAccountsClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankName', models.CharField(blank=True, choices=[('0', 'BCP'), ('1', 'BBVA'), ('2', 'INTERBANK'), ('3', 'SCOTIABANK'), ('4', 'COMERCIO'), ('5', 'BANBIF'), ('6', 'PICHINCHA'), ('7', 'GNB'), ('8', 'MIBANCO'), ('9', 'FALABELLA'), ('10', 'CITIBANK'), ('11', 'RIPLEY')], max_length=2, null=True, verbose_name='Banco')),
                ('typeCurrency', models.CharField(blank=True, choices=[('0', 'PEN'), ('1', 'USD'), ('2', 'EUR')], max_length=1, null=True, verbose_name='Tipo de moneda')),
                ('typeAccount', models.CharField(blank=True, choices=[('0', 'Ahorros'), ('1', 'Corriente'), ('2', 'Sueldo'), ('3', 'Ahorros JSAT'), ('4', 'Ahorros DAVINCHY')], max_length=1, null=True, verbose_name='Tipo de cuenta')),
                ('account', models.CharField(blank=True, null=True, verbose_name='Nro Cuenta')),
                ('accountCCI', models.CharField(blank=True, null=True, verbose_name='Nro CCI')),
                ('idClient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CuentaBancariaCliente', to='stakeholders.client')),
            ],
        ),
        migrations.CreateModel(
            name='bankAccountsSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankName', models.CharField(blank=True, choices=[('0', 'BCP'), ('1', 'BBVA'), ('2', 'INTERBANK'), ('3', 'SCOTIABANK'), ('4', 'COMERCIO'), ('5', 'BANBIF'), ('6', 'PICHINCHA'), ('7', 'GNB'), ('8', 'MIBANCO'), ('9', 'FALABELLA'), ('10', 'CITIBANK'), ('11', 'RIPLEY')], max_length=2, null=True, verbose_name='Banco')),
                ('typeCurrency', models.CharField(blank=True, choices=[('0', 'PEN'), ('1', 'USD'), ('2', 'EUR')], max_length=1, null=True, verbose_name='Tipo de moneda')),
                ('typeAccount', models.CharField(blank=True, choices=[('0', 'Ahorros'), ('1', 'Corriente'), ('2', 'Sueldo'), ('3', 'Ahorros JSAT'), ('4', 'Ahorros DAVINCHY')], max_length=1, null=True, verbose_name='Tipo de cuenta')),
                ('account', models.CharField(blank=True, null=True, verbose_name='Nro Cuenta')),
                ('accountCCI', models.CharField(blank=True, null=True, verbose_name='Nro CCI')),
                ('idSupplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CuentaBancariaCliente', to='stakeholders.supplier')),
            ],
        ),
    ]
