# Generated by Django 5.0.6 on 2025-08-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholders', '0004_alter_client_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='status',
            field=models.CharField(blank=True, choices=[('0', 'Activo'), ('1', 'No activo')], default='1', max_length=1, null=True, verbose_name='Estado Proveedor'),
        ),
    ]
