# Generated by Django 5.0.6 on 2025-09-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholders', '0005_alter_supplier_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='location',
            field=models.CharField(blank=True, choices=[('0', 'nacional'), ('1', 'extrangero')], default='1', max_length=1, null=True, verbose_name='Por origen'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='location',
            field=models.CharField(blank=True, choices=[('0', 'nacional'), ('1', 'extrangero')], default='0', max_length=1, null=True, verbose_name='Por origen'),
        ),
    ]
