# Generated by Django 5.0.6 on 2025-09-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholders', '0006_alter_client_location_alter_supplier_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='numberIdSupplier',
            field=models.CharField(default='', unique=True, verbose_name='Numero de proveedor'),
            preserve_default=False,
        ),
    ]
