# Generated by Django 5.0.6 on 2026-03-19 15:35

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholders', '0007_alter_supplier_numberidsupplier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccountsclient',
            options={'verbose_name': 'Cuenta bancaria de cliente', 'verbose_name_plural': 'Cuentas bancarias de clientes'},
        ),
        migrations.RemoveField(
            model_name='bankaccountsclient',
            name='typeAccount',
        ),
        migrations.AddField(
            model_name='bankaccountsclient',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='bankaccountsclient',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='bankaccountsclient',
            name='account',
            field=models.CharField(default='', max_length=30, verbose_name='Número de cuenta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankaccountsclient',
            name='idClient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='stakeholders.client'),
        ),
        migrations.AlterField(
            model_name='bankaccountssupplier',
            name='idSupplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CuentaBancariaProveedor', to='stakeholders.supplier'),
        ),
    ]
